<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTituloPosteoCobroenEfectivo</name>
   <tag></tag>
   <elementGuidId>4a8b431f-1f3d-40da-bb82-997852723d7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;FUNDS.TRANSFER,POSTEO.DEPOSITO&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dealtitle']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>619d5ad0-48b1-4a72-92b4-6fa97ac3ab5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>3e18a93f-8b24-4ac7-9917-a5a56f3494ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>1f1d4854-7677-4096-9b8b-2815d3d2f6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>FUNDS.TRANSFER,POSTEO.DEPOSITO</value>
      <webElementGuid>f3f87994-0aba-4874-a506-22bab1fb7098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:help(&quot;FUNDS.TRANSFER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);</value>
      <webElementGuid>4ef3b79b-aae4-4c96-8f7c-406a243164b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Posteo Cobro en Efectivo</value>
      <webElementGuid>6954ec78-4d06-4703-8f34-4eedcd4d9857</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dealtitle&quot;)/a[1]</value>
      <webElementGuid>63638290-3d9e-476d-b401-5ca896f46807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dealtitle']/a</value>
      <webElementGuid>ec119656-0acf-4c30-949f-7100aba9bab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Posteo Cobro en Efectivo')]</value>
      <webElementGuid>7a9b1f2c-a68c-41a5-bd4c-d4c457bdcb57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FT/22210/074553487'])[1]/preceding::a[1]</value>
      <webElementGuid>8e330074-1eda-4ffc-b92f-9cb005e1ffaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.073 Jujuy)'])[1]/preceding::a[1]</value>
      <webElementGuid>1491202d-2015-411a-a25f-21fea9c4e63d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Posteo Cobro en Efectivo']/parent::*</value>
      <webElementGuid>62b5556f-9be2-4696-b5ac-15ebd2a2bc08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:help(&quot;FUNDS.TRANSFER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);')]</value>
      <webElementGuid>aeca8f00-4bab-467b-829b-c0717a358358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>9b5a37d5-5d48-4aa7-93bb-da1b79b4a16f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'FUNDS.TRANSFER,POSTEO.DEPOSITO' and @href = 'javascript:help(&quot;FUNDS.TRANSFER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);' and (text() = 'Posteo Cobro en Efectivo' or . = 'Posteo Cobro en Efectivo')]</value>
      <webElementGuid>f1b88da0-772d-4ee6-a25d-c3696178159e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
