<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTxnCompleta</name>
   <tag></tag>
   <elementGuidId>c0fd1f1c-1e26-4ce8-b895-f9ca9b115263</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3175df88-3544-49f9-95c8-733910bea71f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>86719406-1409-40c0-914c-34ee939a62e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Txn Completa: 10014 12:54:44 26 DEC 2023 BCCL.CQ.CHRECH.REP.BCRA,MODFIRM I </value>
      <webElementGuid>03073ec8-f526-4b03-ae4f-83633b063a8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appreq&quot;)/div[@class=&quot;display_box display_box_BCCLCQCHRECHREPBCRA display_box_BCCLCQCHRECHREPBCRA_MODFIRM&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@id=&quot;messages&quot;]/tbody[1]/tr[2]/td[2]/table[2]/tbody[1]/tr[1]/td[@class=&quot;message&quot;]</value>
      <webElementGuid>a6e9ee79-4c99-4bf8-b240-5955d637b92a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      <webElementGuid>f3249773-7943-4a5e-bf37-e4809894266b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.019 La Plata)'])[1]/following::td[7]</value>
      <webElementGuid>3d741fbe-190e-4340-a50b-b2f633463794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingreso de firmantes'])[1]/following::td[14]</value>
      <webElementGuid>78cf4426-34b4-4897-aa35-e68360f933e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::td[2]</value>
      <webElementGuid>4808b6f4-75a1-4333-ab3b-cd1e3bf60708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::td[2]</value>
      <webElementGuid>3937718a-5b29-4798-bd08-1f20d6a0e49e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Txn Completa: 10014 12:54:44 26 DEC 2023 BCCL.CQ.CHRECH.REP.BCRA,MODFIRM I']/parent::*</value>
      <webElementGuid>68230ff4-49b4-4514-8952-d412ba6c727f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td</value>
      <webElementGuid>09125ec8-f28b-49aa-baee-c16f455e14df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Txn Completa: 10014 12:54:44 26 DEC 2023 BCCL.CQ.CHRECH.REP.BCRA,MODFIRM I ' or . = 'Txn Completa: 10014 12:54:44 26 DEC 2023 BCCL.CQ.CHRECH.REP.BCRA,MODFIRM I ')]</value>
      <webElementGuid>72214cc2-b57b-4346-917e-6ff3ad4cf213</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
