<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkTesoreroGeneral</name>
   <tag></tag>
   <elementGuidId>74766a34-6646-403c-9531-be6151021bb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@onclick='ProcessMouseClick(event)'])[148]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5e2aa66-97d8-4857-86c6-cb3b4a2ec28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ProcessMouseClick(event)</value>
      <webElementGuid>9ec1674a-a118-4ad1-869d-3f74b731e7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>ProcessKeyPress(event)</value>
      <webElementGuid>b880162e-3b1a-4bf9-86fb-47ebfb77eeec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TESORERO GENERAL</value>
      <webElementGuid>cb9c086b-33a8-45ad-8a94-3234dacd7a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[1]</value>
      <webElementGuid>c021f8f6-ca5f-4433-9028-0950c6b9b50e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@onclick='ProcessMouseClick(event)'])[148]</value>
      <webElementGuid>84a9d7dc-b208-4048-a9e5-dd92e11a63d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul[7]/li/ul/li[4]/ul/li[4]/span</value>
      <webElementGuid>03efae7f-af61-4948-b9e8-1bc6987ea057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REVERSO RECEPCION REMESAS'])[1]/following::span[1]</value>
      <webElementGuid>3fdad699-aaed-40f6-8fa4-c65a1dbcaf21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RECEPCION DE REMESAS'])[1]/following::span[1]</value>
      <webElementGuid>8d8a71d3-1316-497a-93c4-d80686e8580c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATENCION A TESOROS'])[2]/preceding::span[1]</value>
      <webElementGuid>47920a37-7f72-47e0-b545-75d75c105af4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATENCION PEDIDOS DE REMESAS'])[2]/preceding::span[2]</value>
      <webElementGuid>d0ec7e7b-4d78-4029-a58b-1978d9918747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TESORERO GENERAL']/parent::*</value>
      <webElementGuid>a432819f-36a9-4ba8-9190-6a3038d0368c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/ul/li[4]/span</value>
      <webElementGuid>69fc7353-a185-4c64-a05f-27ac220fbf26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TESORERO GENERAL' or . = 'TESORERO GENERAL')]</value>
      <webElementGuid>16c040b0-ec39-40ee-bf69-658a3618553f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
