<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbtnNo</name>
   <tag></tag>
   <elementGuidId>6b514be2-d988-40eb-8e58-2fa196bcb9af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='radio:tab1:UVHI.REGUL.DOCUM'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b373049-d8f6-42af-9790-bc5690b93e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioCheckStyle radioCheckStyle_BCCLANSESBEN radioCheckStyle_BCCLANSESBEN_UPDATEUVHIREGDOC</value>
      <webElementGuid>c6a1d282-ec82-4c78-9107-25c8cc6fc9ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a3579794-983c-4f5c-9340-45913ad03b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>b3eeb129-6703-4dd8-ade1-f63fa414106a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:toggleRadio(event)</value>
      <webElementGuid>be98d9b8-0a01-4a88-b00c-1e6b3791e7c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript:enableFocus(this)</value>
      <webElementGuid>9dede015-84c3-422e-bfbf-42d5f0e9264d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:disableFocus(this)</value>
      <webElementGuid>23e92385-8c0b-4be2-a238-34f3103980a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8cf32a57-7ff0-4cea-b993-ca5044c521a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ac86cc66-fc0d-4fa1-841e-14d3687d2bf7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio:tab1:UVHI.REGUL.DOCUM</value>
      <webElementGuid>ec9d22ef-3486-455a-921e-73a715f30929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio:tab1:UVHI.REGUL.DOCUM</value>
      <webElementGuid>69850959-30ec-45e2-acaf-ec31d32b6d58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>NO</value>
      <webElementGuid>db05332a-9665-41a5-8de5-c366a8fef754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>
          javascript:clearEnrichment(event);
        </value>
      <webElementGuid>fe300884-d670-4602-a31a-87b3c6bfc0f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'','issueToken');</value>
      <webElementGuid>7125f7be-1193-4f88-afa5-316d35130802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('','','','issueToken')</value>
      <webElementGuid>15dafc60-b1fb-4c65-a474-f6f122469091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[12]/td[3]/table[1]/tbody[1]/tr[1]/td[2]/input[@id=&quot;radio:tab1:UVHI.REGUL.DOCUM&quot;]</value>
      <webElementGuid>8e3da563-9b73-4c11-9d92-6d5f9100637b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='radio:tab1:UVHI.REGUL.DOCUM'])[2]</value>
      <webElementGuid>ec638c0f-22b6-4405-b5a7-0c119102f4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[12]/td[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>a9a02ee6-ffd5-4f1f-9de4-eb83406dbefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>69be8375-e933-4c60-9fd8-53ddb8118648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@selected = 'false' and @type = 'radio' and @id = 'radio:tab1:UVHI.REGUL.DOCUM' and @name = 'radio:tab1:UVHI.REGUL.DOCUM']</value>
      <webElementGuid>7fdd9002-6d4a-49c4-b6a9-14276a37e1c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
