<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAceptarRegistro</name>
   <tag></tag>
   <elementGuidId>06380d0f-a07a-40d3-acf2-4b5bc75151b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Aceptar el registro&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>74a55c1b-3fe4-4fd6-bf7d-45c9e968da35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/txncommit.gif
															</value>
      <webElementGuid>97b743ba-ce66-4819-ae36-ac633e1f1a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aceptar el registro</value>
      <webElementGuid>04be5a0f-b8da-4e04-889c-ec5d30957e1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aceptar el registro</value>
      <webElementGuid>00eb5e97-4b53-4d92-b393-a835bdf443e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goButton&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[1]/img[1]</value>
      <webElementGuid>6476b2be-239d-4066-aee1-9be9ed87b949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td/a/img</value>
      <webElementGuid>2604dfde-2035-4d25-8280-00254578857c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aceptar el registro']</value>
      <webElementGuid>812d61de-2d17-4352-a784-f53fea8c9bb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>230dcbe3-082c-48fc-aa59-409c70a3675d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/tools/txncommit.gif
															' and @alt = 'Aceptar el registro' and @title = 'Aceptar el registro']</value>
      <webElementGuid>85df7410-327d-4cd4-b14a-cb63af3d2bbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
