<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxAutorizarLote</name>
   <tag></tag>
   <elementGuidId>2f4e7b19-483e-4959-9c7c-be6255051fd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drillbox:1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8b0508d7-2aa4-42b7-8cc4-0ed771c06cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drillbox:1_1</value>
      <webElementGuid>0ba112a6-3499-4ace-8ec2-04d6aad5a704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drillbox drillbox_BCCLEPERALTMLOTESNOFAA</value>
      <webElementGuid>bb19d5b8-e72f-4f2d-bd8a-6b5431902607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personas con ErroresModificar Persona PendienteAutorizar LoteVer Detalle LoteEliminar Lote</value>
      <webElementGuid>68b12c56-13ad-4bab-9f29-8520ac4e5a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drillbox:1_1&quot;)</value>
      <webElementGuid>3c459195-5c8a-4d89-8c22-8703496534b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drillbox:1_1']</value>
      <webElementGuid>37208de2-363e-4a6b-93dc-0a5151a0d88c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[13]/table/tbody/tr/td/select</value>
      <webElementGuid>3ecea4ed-596d-4614-8eeb-0d4e09f51bea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MASI ANSES'])[1]/following::select[1]</value>
      <webElementGuid>554fbc6c-62a3-49af-84c5-1ae5369eddb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T-TOTAL'])[1]/following::select[1]</value>
      <webElementGuid>bc132aca-b3a9-4e93-8c42-5e688f72154e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::select[1]</value>
      <webElementGuid>6fba216a-7ed7-43b8-a9f1-1b28fa988fa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::select[1]</value>
      <webElementGuid>49b102ca-5378-4ce7-b8da-15bcb882b011</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>ffccc381-005d-4015-a574-cf4eed77a690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drillbox:1_1' and (text() = 'Personas con ErroresModificar Persona PendienteAutorizar LoteVer Detalle LoteEliminar Lote' or . = 'Personas con ErroresModificar Persona PendienteAutorizar LoteVer Detalle LoteEliminar Lote')]</value>
      <webElementGuid>9d822702-5497-4b50-a39a-0e436726133c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
