<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxAUTODEBUGSTARTSTOP</name>
   <tag></tag>
   <elementGuidId>dd748c96-684b-47cb-a94a-d86e7c317bc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:SERVICE.CONTROL']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>daf79984-db0f-4231-9a63-f93d97689756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_TSASERVICE</value>
      <webElementGuid>44b6a100-f406-479c-9a88-8a569e7145a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:SERVICE.CONTROL</value>
      <webElementGuid>f35ec327-45bf-4396-bca5-626a8dbfeb61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:SERVICE.CONTROL</value>
      <webElementGuid>637410fc-76e6-4560-a146-63cc8c13e5b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ea4c7727-b01a-4717-9fb9-6b42b73ae41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>9fc2b1a1-8ea6-47dc-8af5-9d00f549cbcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>STOP</value>
      <webElementGuid>5b845f22-87e3-45b3-9014-a75c7e5ae4b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>STOP</value>
      <webElementGuid>2f70a87c-85a3-4202-a693-b58437eccc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_SERVICE.CONTROL</value>
      <webElementGuid>afad559e-b7b1-433f-89dc-80877ea8712b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'SERVICE.CONTROL','issueToken');</value>
      <webElementGuid>dd8c6c5d-db07-4681-ba0b-f3dc2d121e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>be84a2d8-07ae-46c7-a179-54eaf38eeb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('SERVICE.CONTROL','','','issueToken')</value>
      <webElementGuid>eb1a91ec-f13c-4c0c-9c2b-78114bab21ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  AUTODEBUGSTARTSTOP</value>
      <webElementGuid>f5dc0d36-c219-451c-8914-1fa070b57301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:SERVICE.CONTROL&quot;)</value>
      <webElementGuid>d1616cda-6f9c-47d4-bdef-632f63c006e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:SERVICE.CONTROL']</value>
      <webElementGuid>9c6af670-e256-469a-ad72-2b8c1c4bb96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[6]/td[3]/select</value>
      <webElementGuid>41aae0f0-3ee2-4539-a292-37dc861ca471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Service Control'])[1]/following::select[1]</value>
      <webElementGuid>4138fed1-c7a4-4ad6-99b4-86b76ea8d3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USUARIO GENERICO DE TELLER'])[1]/following::select[1]</value>
      <webElementGuid>80f80a26-7fe3-4b57-98eb-a4fc101c5456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Time'])[1]/preceding::select[1]</value>
      <webElementGuid>c14deec5-6380-45e8-a628-c33a8b8f23cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time Out'])[1]/preceding::select[1]</value>
      <webElementGuid>bbe42f3d-a3d4-4f5c-9f4d-0a004d806326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d6c11a7c-db03-4ba3-9131-c6b8bdf7b8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:SERVICE.CONTROL' and @id = 'fieldName:SERVICE.CONTROL' and (text() = '  AUTODEBUGSTARTSTOP' or . = '  AUTODEBUGSTARTSTOP')]</value>
      <webElementGuid>49c63621-09b1-4c78-919f-39e0c7b89219</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
