<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblSegundaMarca</name>
   <tag></tag>
   <elementGuidId>4029f116-c7bb-40ef-9c54-bf68381db8cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r2']/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>07d29092-b39b-49c7-b35d-ab7a96ba9e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CABAL</value>
      <webElementGuid>2ff5bb2e-e39b-4c17-bd22-7511a45d153a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r2&quot;)/td[2]</value>
      <webElementGuid>587c6e66-cd11-45a4-ac6d-a5e29e12abc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r2']/td[2]</value>
      <webElementGuid>4bb4699f-f662-49bd-a8ec-0a8e0f540eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[1]/following::td[5]</value>
      <webElementGuid>1aaaf485-87bf-497c-8914-9452aac6efb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E'])[1]/following::td[7]</value>
      <webElementGuid>f2907528-0a8e-48fa-9e61-c49b07ad60e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CREDITO INDIVIDUOS'])[2]/preceding::td[1]</value>
      <webElementGuid>0f2f8d18-1805-4e95-b6fd-04c685727d24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FALZONE NICOLAS GABRIEL'])[1]/preceding::td[2]</value>
      <webElementGuid>363c9cd5-4786-470f-8038-c4ce2cb8ffd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>14cb5d33-004c-40f9-9747-cc04e81fa3fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'CABAL' or . = 'CABAL')]</value>
      <webElementGuid>45107caf-57b2-44ce-b933-a6f15605a2bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
