<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkD3-PagoChequeCamara</name>
   <tag></tag>
   <elementGuidId>8cc20fbf-5449-4cb7-a945-4b85a2228169</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@onclick='ProcessMouseClick(event)'])[227]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>7fa7365c-414c-4157-8e9a-292a39ddf6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ProcessMouseClick(event)</value>
      <webElementGuid>ff080208-ec15-4609-8399-936724a34b0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>ProcessKeyPress(event)</value>
      <webElementGuid>08d4dd19-14f4-4d32-bfcf-8b53da437244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>D3 - PAGO CHEQUE CAMARA</value>
      <webElementGuid>cde8a6b9-0537-4ff9-98c6-5c0f02b88e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[1]</value>
      <webElementGuid>f4a9fc21-c454-4a58-a1cf-65c55ff147ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@onclick='ProcessMouseClick(event)'])[227]</value>
      <webElementGuid>ef145b42-2aad-4a70-a632-c7665c720902</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul[7]/li/ul/li[20]/span</value>
      <webElementGuid>d7cb8a07-4885-44a2-a098-dbdd89d64ec2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta de Sobregiros'])[1]/following::span[1]</value>
      <webElementGuid>1ad8e1fd-950b-42bb-a342-397cb2e49072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Acumuladores por Acuerdo'])[1]/following::span[1]</value>
      <webElementGuid>a76cd847-3e4a-467a-b61f-36cb4d02f2f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago Cheques Camara'])[2]/preceding::span[1]</value>
      <webElementGuid>e1794e7b-d409-44ca-893f-9858d8985dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CHECKS PAGADOS'])[2]/preceding::span[2]</value>
      <webElementGuid>1baa4543-33a8-4ce2-8885-ea8f80e249c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='D3 - PAGO CHEQUE CAMARA']/parent::*</value>
      <webElementGuid>a8d47f53-bef8-4f15-a3b7-7e70ab3e79cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[20]/span</value>
      <webElementGuid>60edc82f-b211-428c-8804-452fb1e6b6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'D3 - PAGO CHEQUE CAMARA' or . = 'D3 - PAGO CHEQUE CAMARA')]</value>
      <webElementGuid>117e6b22-c77c-4ec8-abe6-364979c565d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
