<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTituloBCCL.E.MR.PARTIDAS.PEND.CANCELADAS</name>
   <tag></tag>
   <elementGuidId>7a2897a4-dd36-427b-82ca-7892db63c859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.caption.caption_BCCLEMRPARTIDASPENDCANCELADAS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='enqsel']/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9b1a4271-84d4-4f8c-8ebb-978507aea0df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caption caption_BCCLEMRPARTIDASPENDCANCELADAS</value>
      <webElementGuid>8533dfbb-6106-4126-ac3f-058de3344b8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BCCL.E.MR.PARTIDAS.PEND.CANCELADAS</value>
      <webElementGuid>3c892777-6fd9-4d3b-885a-f46e9bbc05d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqsel&quot;)/table[@class=&quot;enqsel-main enqsel-main_BCCLEMRPARTIDASPENDCANCELADAS&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;display_box display_box_BCCLEMRPARTIDASPENDCANCELADAS enqsel-selections enqsel-selections_BCCLEMRPARTIDASPENDCANCELADAS&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;header-table header-table_BCCLEMRPARTIDASPENDCANCELADAS&quot;]/tbody[1]/tr[@class=&quot;caption caption_BCCLEMRPARTIDASPENDCANCELADAS&quot;]/td[1]/table[1]/tbody[1]/tr[1]/td[@class=&quot;caption caption_BCCLEMRPARTIDASPENDCANCELADAS&quot;]</value>
      <webElementGuid>e73dd0a8-f0fb-4721-996e-d4af4478ba28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enqsel']/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td</value>
      <webElementGuid>88bc73b6-87e9-4d6c-ad46-ca52c33fba51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favoritos'])[1]/following::td[5]</value>
      <webElementGuid>270114d3-047f-4e83-a008-e5568e013b7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mas Opciones'])[1]/preceding::td[2]</value>
      <webElementGuid>50093bcf-316b-44ad-a26e-f9d3740d76ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva Seleccion'])[1]/preceding::td[3]</value>
      <webElementGuid>dd4e2eb4-bf6f-4827-80dd-3924ca46eb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/table/tbody/tr/td/table/tbody/tr/td</value>
      <webElementGuid>954b8690-c038-4be6-9b19-57811c0c41f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'BCCL.E.MR.PARTIDAS.PEND.CANCELADAS' or . = 'BCCL.E.MR.PARTIDAS.PEND.CANCELADAS')]</value>
      <webElementGuid>f6e1dc5d-403c-444f-8889-79ca1b4c848a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
