<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxMotivoBloqueo</name>
   <tag></tag>
   <elementGuidId>760630dc-2477-4565-8bbf-9a2422fc2fed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:MOTIV.BLOQUEO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb81e64b-4063-4898-806a-30f0b43a02cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_BCCLMMIMM dealbox_BCCLMMIMM_BLOQUEADO</value>
      <webElementGuid>256aaedc-9ff4-428f-925e-af9e918dc83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:MOTIV.BLOQUEO</value>
      <webElementGuid>9e69a14f-8a7e-4b17-bbc5-df7c1c240368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:MOTIV.BLOQUEO</value>
      <webElementGuid>8e00465d-5f52-49df-b0eb-8850c37c9db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3411687f-5758-4fac-be61-4b1095210e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>mainTab</value>
      <webElementGuid>9e1fda44-efda-4453-aedc-29a8bd0714a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_MOTIV.BLOQUEO</value>
      <webElementGuid>db0d39f8-52dc-4782-bd6e-940ff275da9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'MOTIV.BLOQUEO','issueToken');</value>
      <webElementGuid>03b04bd3-90a1-4312-9f80-0ea221e8cba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>2831341e-66f3-4b99-848d-608af710cd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('MOTIV.BLOQUEO','','','issueToken')</value>
      <webElementGuid>9849aa5d-1128-4b20-af83-867b00a51c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  CAUCIONCUSTODIAEMBARGOORDEN DE NO PAGAR</value>
      <webElementGuid>297ec017-198a-42cc-a31a-a879ccd1d0f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:MOTIV.BLOQUEO&quot;)</value>
      <webElementGuid>2795117e-18cd-4f37-9652-9a25e3bd5a3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:MOTIV.BLOQUEO']</value>
      <webElementGuid>66e37eb2-c5a4-4610-b985-befe70be8383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='mainTab']/tbody/tr[2]/td[3]/select</value>
      <webElementGuid>7d46acee-9dd6-4bbd-8787-52ddb4fb29ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motivo del Bloqueo'])[1]/following::select[1]</value>
      <webElementGuid>8d7a9228-e12c-4de7-844f-2597fb4818f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI'])[1]/following::select[1]</value>
      <webElementGuid>8abdd337-b0f3-434f-a452-6922975686a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id. Persona'])[1]/preceding::select[1]</value>
      <webElementGuid>f0ec1bc3-c21a-426d-b03e-4baf40fe6590</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Circular'])[1]/preceding::select[1]</value>
      <webElementGuid>6ad97203-c265-4eef-972d-c7f6be91f656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7feede33-0ec0-4807-a586-1d32b0a6bcb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:MOTIV.BLOQUEO' and @id = 'fieldName:MOTIV.BLOQUEO' and (text() = '  CAUCIONCUSTODIAEMBARGOORDEN DE NO PAGAR' or . = '  CAUCIONCUSTODIAEMBARGOORDEN DE NO PAGAR')]</value>
      <webElementGuid>211d7cdb-6f47-4b4f-b58a-67724d4f5e27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
