<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkEntregaSocioPorNroPieza</name>
   <tag></tag>
   <elementGuidId>7a11a4d3-f78e-4ff2-8412-01e15546a685</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;javascript:menu_history('CONTRACT','BCCL.AP.PIEZAS,BCCL.V.AP.ENTREGA.AL.SOCIO');processMenuHeaderText('Entrega al Socio por Nro. de PIEZA')&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[1]/a[1][count(. | //*[@href = concat(&quot;javascript:docommand(&quot; , &quot;'&quot; , &quot;BCCL.AP.PIEZAS,BCCL.V.AP.ENTREGA.AL.SOCIO&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Entrega al Socio por Nro. de PIEZA ' or . = 'Entrega al Socio por Nro. de PIEZA ') and @ref_element = 'Object Repository/02-Dashboard/AdminPiezasConTarjetas/frmAdminPiezasConTarjetas']) = count(//*[@href = concat(&quot;javascript:docommand(&quot; , &quot;'&quot; , &quot;BCCL.AP.PIEZAS,BCCL.V.AP.ENTREGA.AL.SOCIO&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Entrega al Socio por Nro. de PIEZA ' or . = 'Entrega al Socio por Nro. de PIEZA ') and @ref_element = 'Object Repository/02-Dashboard/AdminPiezasConTarjetas/frmAdminPiezasConTarjetas'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>693a687f-c44c-4742-a0b9-365a52fae249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:menu_history('CONTRACT','BCCL.AP.PIEZAS,BCCL.V.AP.ENTREGA.AL.SOCIO');processMenuHeaderText('Entrega al Socio por Nro. de PIEZA')</value>
      <webElementGuid>a4ea8937-6504-4b89-8258-093ed3fb0b19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:docommand('BCCL.AP.PIEZAS,BCCL.V.AP.ENTREGA.AL.SOCIO');</value>
      <webElementGuid>a2ecb2e8-2d79-4432-a6ff-9ed5a68de356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrega al Socio por Nro. de PIEZA </value>
      <webElementGuid>d4440ee0-d7db-4e4f-8759-04b8632821df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>556a9461-1e36-4aa9-9ea6-3e5394118be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/02-Dashboard/AdminPiezasConTarjetas/frmAdminPiezasConTarjetas</value>
      <webElementGuid>3d12a46a-ac01-4dd3-818e-2adcb10ddf2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;javascript:menu_history('CONTRACT','BCCL.AP.PIEZAS,BCCL.V.AP.ENTREGA.AL.SOCIO');processMenuHeaderText('Entrega al Socio por Nro. de PIEZA')&quot;]</value>
      <webElementGuid>cf9892ff-77e3-483e-ac05-b5a1650397ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul[14]/li/ul/li[3]/ul/li/a</value>
      <webElementGuid>77852c1c-4412-4881-9ce8-6e05bc2ea2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Entrega al Socio por Nro. de PIEZA')]</value>
      <webElementGuid>c05bc644-1f5c-4939-9f48-6101700bbef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrega de TARJETAS al SOCIO'])[1]/following::a[1]</value>
      <webElementGuid>14409405-f468-4b62-a3cf-0d407023645b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envio o Entrega a AC de Card-Carrier'])[1]/following::a[1]</value>
      <webElementGuid>7172dd2a-8bff-4b38-a139-dc38fad5f88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultas al Maestro de Card-Carrier'])[1]/preceding::a[1]</value>
      <webElementGuid>27c8d69e-1d33-4772-b4d9-787e53d4d6da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccion por Nombre / Documento / Sucursal'])[1]/preceding::a[1]</value>
      <webElementGuid>06007553-821e-4d22-8557-91418506ece2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrega al Socio por Nro. de PIEZA']/parent::*</value>
      <webElementGuid>d5c48e32-1fc3-41cb-8501-fbd5ae730abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:docommand('BCCL.AP.PIEZAS,BCCL.V.AP.ENTREGA.AL.SOCIO');&quot;)]</value>
      <webElementGuid>7ee85c38-6f5c-4a9a-b0cb-c12b7e63a4d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[14]/li/ul/li[3]/ul/li/a</value>
      <webElementGuid>9cca4fae-b63a-40f4-b845-0820a147522f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:docommand(&quot; , &quot;'&quot; , &quot;BCCL.AP.PIEZAS,BCCL.V.AP.ENTREGA.AL.SOCIO&quot; , &quot;'&quot; , &quot;);&quot;) and (text() = 'Entrega al Socio por Nro. de PIEZA ' or . = 'Entrega al Socio por Nro. de PIEZA ')]</value>
      <webElementGuid>e18b0ffd-f330-458d-b45b-aab1c06e7dec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
