<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblFinalizada</name>
   <tag></tag>
   <elementGuidId>c89eaa5e-f559-46de-a16b-bd0fb18ce93f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.bccl-verde.bccl-verde_BCCLEESTADOPANTALLAS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r2']/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2efc9f6e-7ce4-4adb-a42d-eee579cb6ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bccl-verde bccl-verde_BCCLEESTADOPANTALLAS</value>
      <webElementGuid>704af8c4-4323-48d9-a82a-a8b858b2f3a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>23d5eb39-1254-43d3-9e2c-345cade5f7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FINALIZADA</value>
      <webElementGuid>902addab-dcc6-46a6-a42a-800737e5c94e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r2&quot;)/td[@class=&quot;bccl-verde bccl-verde_BCCLEESTADOPANTALLAS&quot;]</value>
      <webElementGuid>acb462ff-0a50-4da8-b907-0fc730b0ab57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/44-TOB/Verificacion de Firmas/frmFirmas</value>
      <webElementGuid>345b38ad-613d-4f1b-96d0-7e56774deb9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r2']/td[2]</value>
      <webElementGuid>7b7323ed-4a14-4d64-810c-5451bd401452</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FT22210119250769'])[1]/following::td[1]</value>
      <webElementGuid>041a1f19-0657-4a35-b30b-220eeef626a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forzado de Firmas:'])[1]/following::td[3]</value>
      <webElementGuid>1243f941-73fd-45e2-ab26-c201aef52830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaccion Original:'])[1]/preceding::td[1]</value>
      <webElementGuid>621b593a-ddcf-4773-855b-dedf925019d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FT22210119250769'])[2]/preceding::td[3]</value>
      <webElementGuid>6676d1d6-7da1-4e01-b18a-68c84c9bc219</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='FINALIZADA']/parent::*</value>
      <webElementGuid>b26a8e12-663e-4eca-87c3-304f1afa0db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>fa13df78-b8a5-4b3a-83d5-183817dac8cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'FINALIZADA' or . = 'FINALIZADA')]</value>
      <webElementGuid>262b8926-6ce9-4b47-98e1-9e4169691572</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
