<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>tdReferencia</name>
   <tag></tag>
   <elementGuidId>3783a876-c774-4ebe-8141-1f3525b0d133</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#r1 > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r1']/td</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'TI22206000000009' or . = 'TI22206000000009')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9f49e2f2-3ae5-4469-90b3-79882a0a5678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TI22206000000009</value>
      <webElementGuid>6543d8e8-4534-4bdb-b968-acdaa58be79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[1]</value>
      <webElementGuid>d9256e9d-8670-4c9f-941f-9bc70cd72926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td</value>
      <webElementGuid>af0f2ad9-f10b-4188-a0a2-f3a7879feee0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre Beneficiario'])[1]/following::td[1]</value>
      <webElementGuid>d336cb4a-f8bb-498b-ab02-f7ec3afa25d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id Beneficiario'])[1]/following::td[1]</value>
      <webElementGuid>78264913-fbcd-4464-9c3e-313a7680709d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FT22206903662588'])[1]/preceding::td[1]</value>
      <webElementGuid>db52cea7-a5b6-4f14-88f3-8f1ed7216833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denom.: METALURGICASIAM SA - CUI: 30711351937'])[1]/preceding::td[5]</value>
      <webElementGuid>0d190b9b-4643-4a60-8b70-7a20b6bd194b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TI22206000000009']/parent::*</value>
      <webElementGuid>4030b586-f52c-461b-9156-496875974d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td</value>
      <webElementGuid>2501e692-c4a0-4318-992c-328f6abe7788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'TI22206000000009' or . = 'TI22206000000009')]</value>
      <webElementGuid>f8767c6d-459c-404f-aa12-b8e908597678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
