<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtFechaValorBaja</name>
   <tag></tag>
   <elementGuidId>664ff493-74ce-4fcb-a0d6-0379586b2d93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:FECHA.VALOR.BAJA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ebe443ce-a86c-41d8-b47e-bb2c9f3c8d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9fa48d94-afc5-4052-a264-76c584158556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>554f3c54-2e52-4b24-be84-12a64a0c2e47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:FECHA.VALOR.BAJA</value>
      <webElementGuid>ed593b4c-0474-4708-bbba-d56670cb69e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:FECHA.VALOR.BAJA</value>
      <webElementGuid>ba4b840e-bc79-445e-b366-1b3dc451b09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>db726866-d546-4a12-8762-9b201beda159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_BCCLIPPARTIDAS dealbox_BCCLIPPARTIDAS_BAJACC</value>
      <webElementGuid>66772b73-92e8-4c62-9a6e-77c863e2345a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>1ff11d38-154b-4a42-b4e8-9a7e95b920f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>monthdesc</name>
      <type>Main</type>
      <value>ENE FEB MAR ABR MAY JUN JUL AGO SEP OCT NOV DIC</value>
      <webElementGuid>c43483f0-0556-4f11-bd9e-63313e363ffe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a38e6372-f679-4c21-9fc5-7504b349a109</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_FECHA.VALOR.BAJA</value>
      <webElementGuid>80a9b47e-9960-480b-bc7b-2195a40a2416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'FECHA.VALOR.BAJA','issueToken');</value>
      <webElementGuid>15abfa5f-71f9-470f-8765-2ad244e40b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>7885d52c-b4c7-495d-aba5-22290b2853a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('FECHA.VALOR.BAJA','','','issueToken')</value>
      <webElementGuid>6c57c838-458a-4bb9-afa8-845d3f56a228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:FECHA.VALOR.BAJA&quot;)</value>
      <webElementGuid>26aab98a-80c7-418b-8023-17a8e10c8f89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:FECHA.VALOR.BAJA']</value>
      <webElementGuid>3dc4e843-b202-4130-b7d3-256d325b7c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[15]/td[3]/input</value>
      <webElementGuid>f0dafa8e-f62d-4a41-a28b-b7c1c7502dd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[3]/input</value>
      <webElementGuid>47924503-6e70-4c67-907d-c5d0b4439f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:FECHA.VALOR.BAJA' and @name = 'fieldName:FECHA.VALOR.BAJA' and @type = 'text']</value>
      <webElementGuid>1a9602fa-0736-48c3-a995-aac4a82da101</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
