<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblL.DESC.ESP.CR</name>
   <tag></tag>
   <elementGuidId>d2e871b2-bd6e-4eca-9d38-942378ee58d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[42]/td[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fa9e3ec2-ef6f-4f89-8c41-e3fab2d24448</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled_dealbox disabled_dealbox_FUNDSTRANSFER</value>
      <webElementGuid>c72fd75c-8c19-4a54-8f43-2614e3fd6c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>27335616583-VAR-APELLIDO NOMBRE</value>
      <webElementGuid>dd8dd8dd-ecc7-4dd3-9ba2-291ed482efe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[42]/td[3]/span[@class=&quot;disabled_dealbox disabled_dealbox_FUNDSTRANSFER&quot;]</value>
      <webElementGuid>b217f036-7c12-42bc-92c5-e27298299068</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[42]/td[3]/span</value>
      <webElementGuid>44a33ced-fa11-4d37-9cad-426b5c5b0411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L Desc Esp Cr'])[1]/following::span[1]</value>
      <webElementGuid>58272d69-5ebc-4c82-9e39-2150c06c2b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L Desc Esp Db'])[1]/following::span[3]</value>
      <webElementGuid>7d0bb36b-f2cd-4195-b50b-a85ae83dd122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount Debited'])[1]/preceding::span[2]</value>
      <webElementGuid>c9cfcf21-1483-4317-944c-a758bcc3e18c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS 600,00'])[1]/preceding::span[2]</value>
      <webElementGuid>0b583e79-e91a-4cf5-8339-4b2f85bad1cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='27335616583-VAR-APELLIDO NOMBRE']/parent::*</value>
      <webElementGuid>8554620c-6e96-48be-859a-92c8da004794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[42]/td[3]/span</value>
      <webElementGuid>fa51226a-ae5b-4b10-b671-2397d847829c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '27335616583-VAR-APELLIDO NOMBRE' or . = '27335616583-VAR-APELLIDO NOMBRE')]</value>
      <webElementGuid>eebc903e-7f46-4891-aa68-81d382622f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
