<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAceptarRegistro</name>
   <tag></tag>
   <elementGuidId>a8fb2231-f4ef-43b6-b1fe-d8561ab5fcae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Aceptar el registro&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3a305a3a-e5f5-444a-9bc9-e84e9bb50435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/txncommit.gif
															</value>
      <webElementGuid>d484733b-b861-4cb2-ac2c-881291fd4df6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Aceptar el registro</value>
      <webElementGuid>1df8ebde-ef3d-4981-b1b9-71971b8d2e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aceptar el registro</value>
      <webElementGuid>575e787d-155d-4b9e-8e24-cc72dfd2348c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goButton&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[1]/img[1]</value>
      <webElementGuid>01fb28f0-833d-45d1-9295-86bc40860967</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td/a/img</value>
      <webElementGuid>c5d22800-70fb-4744-a164-7faebea725aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Aceptar el registro']</value>
      <webElementGuid>73a76d95-4df9-484a-9e67-91d2fc79ad57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>7ba894ee-3f3f-4505-8216-883cffd16584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/tools/txncommit.gif
															' and @alt = 'Aceptar el registro' and @title = 'Aceptar el registro']</value>
      <webElementGuid>73a1c0bb-0da8-4d77-b592-64b983a644c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
