<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCONRESTRICCIONBLOQUEODEBITOS</name>
   <tag></tag>
   <elementGuidId>de55493a-77dc-4c62-8a72-d512e94b9c5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;OVE2&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OVE3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>7b1f626e-31b1-4848-9dc0-b59509e9199b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overrideOn</value>
      <webElementGuid>30549767-6fa6-423c-91fb-11aebf659bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>58862bc1-62db-4679-a723-7579fb808f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4507e4bb-8bf8-4d6d-b21e-bc0111835be9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OVE2</value>
      <webElementGuid>30ee1ef4-febb-412e-a980-1fa87596ea6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CUENTA 00890014534 CON RESTRICCION BLOQUEO DEBITOS</value>
      <webElementGuid>25810c18-13ae-4b6c-84ab-d2f0d280ab73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OVE2&quot;)</value>
      <webElementGuid>18e155c9-39a5-49b9-bce6-c42da943ec4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='OVE2']</value>
      <webElementGuid>7a21de78-db09-4157-bb13-83ba74e9007a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='error_box']/table/tbody/tr[3]/td/table[2]/tbody/tr[2]/td[2]</value>
      <webElementGuid>3d0a3e3a-bd6c-4b90-81be-d904678a709e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Caja Sobregirada'])[1]/following::td[2]</value>
      <webElementGuid>2f346231-be92-497e-bd31-a89dcf71dbf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar Alertas'])[1]/following::td[5]</value>
      <webElementGuid>0223a0c3-8ead-4d0a-84c9-da717222283e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaccion requiere autorizacion por monto. Nivel NIV1'])[1]/preceding::td[2]</value>
      <webElementGuid>df00a78e-7aec-4e2b-a5d4-fbe02d8250f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ATESORAMIENTO DEBAJO DEL MINIMO POR $ 181.190,15'])[1]/preceding::td[4]</value>
      <webElementGuid>b28074d7-1582-461d-a3f7-0c1ec35a75a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CUENTA 00890014534 CON RESTRICCION BLOQUEO DEBITOS']/parent::*</value>
      <webElementGuid>db969cc7-94dd-4a3a-8683-2c04cbacd4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>f566cb34-3637-4d4c-b6bd-7ff1308a6f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'OVE2' and (text() = 'CUENTA 00890014534 CON RESTRICCION BLOQUEO DEBITOS' or . = 'CUENTA 00890014534 CON RESTRICCION BLOQUEO DEBITOS')]</value>
      <webElementGuid>82e88e69-1013-482c-97ff-4400ce3d87ad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
