<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCONRESTRICCIONBLOQUEOTOTAL</name>
   <tag></tag>
   <elementGuidId>3c13df3a-430a-4092-8679-1ddd1e761d0b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;OVE1&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OVE2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>984d2daa-8bf5-4c6a-95ce-cf402d094097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>overrideOn</value>
      <webElementGuid>a6396d07-67b7-4571-a0fa-b3ceb405df4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f8ab2fd9-9919-4958-89fe-04287e229a65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d9a438e-37e9-4588-93d7-82e520c39313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OVE1</value>
      <webElementGuid>af8fe825-9940-46db-a3e5-44a5ee92fa4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CUENTA 00890052464 CON RESTRICCION BLOQUEO TOTAL</value>
      <webElementGuid>888fe3c2-25d3-4e93-bf42-c2f7b2ba790d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OVE1&quot;)</value>
      <webElementGuid>56aae3a4-a858-495e-b132-0aaea181b51c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='OVE1']</value>
      <webElementGuid>5f73bf6f-5981-4723-b3cc-6730ba568b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='error_box']/table/tbody/tr[3]/td/table[2]/tbody/tr/td[2]</value>
      <webElementGuid>bb470ee9-1cb1-4337-8c37-9b3622b42a5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar Alertas'])[1]/following::td[3]</value>
      <webElementGuid>206818d4-e4de-489d-acd6-4355601b2453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.089 M.del Plata Ctr)'])[1]/following::td[7]</value>
      <webElementGuid>4f4b9ce0-4760-4828-877e-e8adb9ae98f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaccion requiere autorizacion por monto. Nivel NIV1'])[1]/preceding::td[2]</value>
      <webElementGuid>078b242a-5514-4817-800a-fa5da02cda78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MOV A APLICAR SOBRE CTA 00890052464 TIPO BLOQUEO TOTAL REQUIERE AUTORIZACION'])[1]/preceding::td[4]</value>
      <webElementGuid>ffe521ae-a66b-41ac-92db-c043d400b076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CUENTA 00890052464 CON RESTRICCION BLOQUEO TOTAL']/parent::*</value>
      <webElementGuid>3d597648-cb2a-4970-857e-b6ae9f037138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]</value>
      <webElementGuid>9cc5d0c1-c748-4915-9bb1-9349b0aecd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'OVE1' and (text() = 'CUENTA 00890052464 CON RESTRICCION BLOQUEO TOTAL' or . = 'CUENTA 00890052464 CON RESTRICCION BLOQUEO TOTAL')]</value>
      <webElementGuid>3ef67c6b-71a4-4b33-8d83-26a064efda7c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
