<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNroDocumentoDepositante</name>
   <tag></tag>
   <elementGuidId>a0c33592-4ca4-4515-b2e3-f16f9461e5ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:L.NDOC.DEP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6f613425-64c7-4479-b7a5-188d16fc6626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cc23ac05-a794-4970-b83d-4e57bdf28223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>3aa403b9-1533-46a6-a386-d1a08168f6ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:L.NDOC.DEP</value>
      <webElementGuid>4f906cf4-f525-4605-9c8d-aab6d0ee4d83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:L.NDOC.DEP</value>
      <webElementGuid>8a5d022e-ec5b-4c61-bc16-e7163439ebd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>c82a2b4a-8781-44b3-bbbd-5953eda6bd14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_TELLER dealbox_TELLER_DEPOSITOEFECTIVOVENTANILLA</value>
      <webElementGuid>c6e84b10-3333-474b-9776-6ac4db03e21b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>c99aca97-52c6-4353-b12c-156b0ce0f1c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24930388-88f2-4a35-93df-fd204bfc62fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_L.NDOC.DEP</value>
      <webElementGuid>66e6e460-0311-47fb-babb-ca2d5384021c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'L.NDOC.DEP','issueToken');</value>
      <webElementGuid>b2daf7f1-8a4e-4f7b-8dfd-6554feb1dfa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>89c6c2e1-f9bc-4eec-927e-84c16eb65e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('L.NDOC.DEP','','','issueToken')</value>
      <webElementGuid>ab46779c-1efe-4007-a6ea-9682d75d9c64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:L.NDOC.DEP&quot;)</value>
      <webElementGuid>b73285be-ea49-46b4-8f24-24db65a73bb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:L.NDOC.DEP']</value>
      <webElementGuid>84267b16-edca-47c3-94d9-2b15105fb10c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[11]/td[3]/input</value>
      <webElementGuid>05ef1075-d250-42d4-a38b-3a0926aa05b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td[3]/input</value>
      <webElementGuid>f835334f-f69b-4a65-8d0e-d54afb811375</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:L.NDOC.DEP' and @name = 'fieldName:L.NDOC.DEP' and @type = 'text']</value>
      <webElementGuid>3628e120-2c1a-43e1-a397-a042687912b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
