<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanDenominaciones</name>
   <tag></tag>
   <elementGuidId>3ff8c0db-caaf-4934-9b10-f502f9de45a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nonactive-tab > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='headtab']/tbody/tr/td[2]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>97423877-ed26-4967-a498-5d88398af7fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Denominaciones CR</value>
      <webElementGuid>e5afb057-d7c9-469f-9fe1-b5450c2dd2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headtab&quot;)/tbody[1]/tr[1]/td[2]/a[@class=&quot;nonactive-tab&quot;]/span[1]</value>
      <webElementGuid>9e8df8b1-504e-4d2b-93e5-4e2c69138693</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='headtab']/tbody/tr/td[2]/a/span</value>
      <webElementGuid>2b136bd7-d0e2-4d77-8ba7-fd99bc519fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Faltantes en Dispositivos PN'])[1]/following::span[1]</value>
      <webElementGuid>94a00ad3-cbf5-4ecf-9e18-10786ce1b605</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.073 Jujuy)'])[1]/following::span[2]</value>
      <webElementGuid>0360d337-8326-4d70-a46f-6ea0ed14743c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit'])[1]/preceding::span[1]</value>
      <webElementGuid>8db58de6-385b-41a9-9be3-2992386b667e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha'])[1]/preceding::span[2]</value>
      <webElementGuid>218c361f-8782-41d7-8f87-739b5b3319c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Denominaciones CR']/parent::*</value>
      <webElementGuid>8ba207f0-2134-4589-8d93-5abeb70fb4f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/span</value>
      <webElementGuid>ba525590-523b-40e2-bd33-485ddd8fad86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Denominaciones CR' or . = 'Denominaciones CR')]</value>
      <webElementGuid>1e37d26f-fd23-46ed-a0f1-1e28e368f595</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
