<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTxncompleta</name>
   <tag></tag>
   <elementGuidId>9c989622-d26b-42b5-b0fc-5d1958109196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>39faee1b-e23c-4e4c-8cde-d26abbd58f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>051b2e7f-88af-415a-bc23-5b4df09388c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Txn Completa: 254598140 16:34:22 06 JUN 2024 BCCL.CQ.CHEQUES.RECHAZADOS,RCHFIL A </value>
      <webElementGuid>bbf5cbf3-2ee9-4836-8da9-7038ea9e26b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appreq&quot;)/div[@class=&quot;display_box display_box_BCCLCQCHEQUESRECHAZADOS display_box_BCCLCQCHEQUESRECHAZADOS_RCHFIL&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@id=&quot;messages&quot;]/tbody[1]/tr[2]/td[2]/table[2]/tbody[1]/tr[1]/td[@class=&quot;message&quot;]</value>
      <webElementGuid>b8d7a676-cf89-4c26-8189-89242a0fa45a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      <webElementGuid>1b8b1997-74ec-4b01-850d-1b3d56e542dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.001 Centro)'])[1]/following::td[7]</value>
      <webElementGuid>5e3c621a-6251-49fd-9d61-815415b383b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rechazo de cheques de caja en filial'])[1]/following::td[14]</value>
      <webElementGuid>c07e8823-af15-4b06-b642-96207116c884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Txn Completa: 254598140 16:34:22 06 JUN 2024 BCCL.CQ.CHEQUES.RECHAZADOS,RCHFIL A']/parent::*</value>
      <webElementGuid>eb02584a-b310-4e3c-80f4-d87f7ece4f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td</value>
      <webElementGuid>b44466ff-d77b-4fab-8262-4b739ea9805f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Txn Completa: 254598140 16:34:22 06 JUN 2024 BCCL.CQ.CHEQUES.RECHAZADOS,RCHFIL A ' or . = 'Txn Completa: 254598140 16:34:22 06 JUN 2024 BCCL.CQ.CHEQUES.RECHAZADOS,RCHFIL A ')]</value>
      <webElementGuid>055c51bd-d28e-43f3-8949-31342732d57c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
