<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblMoneda</name>
   <tag></tag>
   <elementGuidId>cd66e650-2d4b-4ec6-873a-94b5920993a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>2b978d74-90e0-488a-9c81-8af98740ce17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>c725bbf1-c3cb-4e4e-8db7-c157b08c522d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>cb5b0bf5-efeb-4b4f-8649-7a65009cca5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText2</value>
      <webElementGuid>282e1122-71fd-4587-92d1-6f8e6e46a106</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Moneda</value>
      <webElementGuid>df47b850-b889-4d0e-9c3c-ef27302b11f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText2&quot;)</value>
      <webElementGuid>13b45b66-f963-4eca-8cdc-3bdbbf396df3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText2']</value>
      <webElementGuid>17ffefca-15e1-4983-864a-a69e3d69e3d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader2']/table/tbody/tr/th</value>
      <webElementGuid>e40f7394-a5d1-414f-b30f-89d178e1ea7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codigo IP'])[1]/following::th[3]</value>
      <webElementGuid>cac4c2c5-b813-4fd8-a074-de8bbdc1f331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como XML'])[2]/following::th[6]</value>
      <webElementGuid>8a1874b1-bb22-472d-a6dd-1b8220a8200f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Monto acumulado'])[1]/preceding::th[2]</value>
      <webElementGuid>2f8abf44-7b67-4cc9-953a-3afd56b1170c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo'])[1]/preceding::th[5]</value>
      <webElementGuid>9e8d5475-f4ba-4a0e-b08c-9e10f59e2eef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Moneda']/parent::*</value>
      <webElementGuid>a647f848-71bc-4599-b82d-9af50c40dcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/table/tbody/tr/th</value>
      <webElementGuid>3ef9ea42-6f9a-4a4c-959d-9374171f99f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText2' and (text() = 'Moneda' or . = 'Moneda')]</value>
      <webElementGuid>9a46b964-d81a-4153-b5f6-942e6cc3cd9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
