<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbx1005</name>
   <tag></tag>
   <elementGuidId>d32be40b-87c9-423b-a3fc-20873a9ee764</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dropDownRow3']/td/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropDownRow3 > td.coloumntddata.coloumntddata_BCCLEPRODSUBPROD > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>437cfaf5-adc8-4b86-b296-a77652bf82a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1005</value>
      <webElementGuid>360af0fd-86c2-4a4f-bea5-74f687be548b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownRow3&quot;)/td[@class=&quot;coloumntddata coloumntddata_BCCLEPRODSUBPROD&quot;]/b[1]</value>
      <webElementGuid>2f60d9cf-0ce2-470e-89cf-7a48bb2a56e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dropDownRow3']/td/b</value>
      <webElementGuid>4146a758-060d-4938-b5c8-e8b96f101b9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Corriente Pagocoop'])[1]/following::b[1]</value>
      <webElementGuid>f3c26084-edde-4798-9f43-f9b893ca6055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Cte Comercial para Endosos'])[1]/following::b[2]</value>
      <webElementGuid>195f0f82-c082-4ef6-8423-38dd56aff3e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Corriente Entidades C Social'])[1]/preceding::b[1]</value>
      <webElementGuid>4284da3b-6136-4319-8a67-0c0e2cc3e35b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta Corriente Practica'])[1]/preceding::b[2]</value>
      <webElementGuid>bfe104b1-755f-44f8-961c-22d50b1d67cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1005']/parent::*</value>
      <webElementGuid>468b5efc-6b55-4ec1-b5d5-4aea421af535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/b</value>
      <webElementGuid>47f9fbb5-cf7c-445d-b606-6a89291e0419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '1005' or . = '1005')]</value>
      <webElementGuid>08ae7fbf-7858-47d1-8be1-d5db32fcffd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
