<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAutorizarRegistro</name>
   <tag></tag>
   <elementGuidId>bc4d6357-5ea3-4fba-8250-7e317144a0ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td[4]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Autoriza el registro&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f98db938-19fc-4dd1-901d-77ca885cd5a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/txnauthorise.gif
															</value>
      <webElementGuid>2e2d5e9d-b007-4c70-b74c-fd8eefb5e0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Autoriza el registro</value>
      <webElementGuid>e1c111e0-26cc-4db5-9927-9fce4d436d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Autoriza el registro</value>
      <webElementGuid>97efa50d-7020-4a8f-867b-d298359d20d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goButton&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[4]/a[1]/img[1]</value>
      <webElementGuid>0bd1f864-bd0b-45d3-993a-3690066a8716</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td[4]/a/img</value>
      <webElementGuid>0a2100e3-c82c-4a07-933f-3c9cbbc6038b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Autoriza el registro']</value>
      <webElementGuid>e271539d-ed8a-4591-b9fb-ba1d6baf1d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/a/img</value>
      <webElementGuid>32a0e76c-1eac-472c-9a74-830db1af0a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/tools/txnauthorise.gif
															' and @alt = 'Autoriza el registro' and @title = 'Autoriza el registro']</value>
      <webElementGuid>b467517a-cf52-4351-be9c-c34ef62c8200</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
