<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTrxCompleta</name>
   <tag></tag>
   <elementGuidId>e516fe82-4510-43d9-a712-fe792eef7138</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c207cdce-8715-4526-9b33-9b8ee6435a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>445f2260-2462-4406-b6b6-08c2d9ce1222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Txn Completa: BOLSIN.00320070112 17:37:23 01 FEB 2023 BCCL.EB.COM.PER.ESP,BAJA R </value>
      <webElementGuid>73f58b99-3bfc-48e5-9aee-a63dc1b92b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appreq&quot;)/div[@class=&quot;display_box display_box_BCCLEBCOMPERESP display_box_BCCLEBCOMPERESP_BAJA&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@id=&quot;messages&quot;]/tbody[1]/tr[2]/td[2]/table[2]/tbody[1]/tr[1]/td[@class=&quot;message&quot;]</value>
      <webElementGuid>d6e65bda-1320-458d-bd74-527deab5bb83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      <webElementGuid>99ebcfde-2c17-4aac-8bda-4820026ccf9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.074 Caseros Centro)'])[1]/following::td[7]</value>
      <webElementGuid>bd5d7598-f10e-427a-b2d4-bf4f80596500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCCL.EB.COM.PER.ESP,BAJA'])[1]/following::td[14]</value>
      <webElementGuid>46d69dc3-8dcb-45fb-bf7d-5db3b4f3a1ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::td[2]</value>
      <webElementGuid>048cce42-cd0f-4b2c-89f4-9b06bf1588b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::td[2]</value>
      <webElementGuid>7739f4b0-844a-454f-93be-21823205b30a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Txn Completa: BOLSIN.00320070112 17:37:23 01 FEB 2023 BCCL.EB.COM.PER.ESP,BAJA R']/parent::*</value>
      <webElementGuid>c4763c8c-2dfc-4391-8072-371246769b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td</value>
      <webElementGuid>642bfe3a-b650-4a17-b2b5-8967e7a3d385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Txn Completa: BOLSIN.00320070112 17:37:23 01 FEB 2023 BCCL.EB.COM.PER.ESP,BAJA R ' or . = 'Txn Completa: BOLSIN.00320070112 17:37:23 01 FEB 2023 BCCL.EB.COM.PER.ESP,BAJA R ')]</value>
      <webElementGuid>ee61a080-7f6f-45bb-a2e0-8d7e5cb5f22a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
