<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblFecha</name>
   <tag></tag>
   <elementGuidId>46f2cbeb-dbe4-4f53-bc5d-f3ecd8cef783</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='fieldCaption:VALUE.DATE.1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a3da5612-4289-43cd-87ec-a92d1b8b0fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>fd140447-73d5-4a41-8d17-06fee0b66f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>5285bba2-65e1-40cb-aace-e99a6a52ee67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field field_TELLER field_TELLER_SOBRANTESCAJA</value>
      <webElementGuid>4b2015c1-8ed1-4de1-8c08-9c13eec16d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldCaption:VALUE.DATE.1</value>
      <webElementGuid>dfd9aa0a-ac69-46a3-a2bc-00533d701611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldCaption:VALUE.DATE.1</value>
      <webElementGuid>f6b7b24f-1253-4fdb-b09b-3fdcb146d12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>106dc404-6194-4ea2-b803-ba866fcfdef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:help('VALUE.DATE.1','','','issueToken')</value>
      <webElementGuid>a7fda02f-bdae-4561-bd50-cec6c40d1e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Fecha</value>
      <webElementGuid>16dac697-18d3-48f8-b7f2-13bb26bf20a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha</value>
      <webElementGuid>f136bfec-1768-4330-aa69-1036d8a64551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldCaption:VALUE.DATE.1&quot;)</value>
      <webElementGuid>25a8fb4e-7ad2-42f5-a0f6-4d4a37782a67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='fieldCaption:VALUE.DATE.1']</value>
      <webElementGuid>4703ba4e-bbf6-4ac9-bc30-47b556d36830</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td[2]/label/a</value>
      <webElementGuid>b7846c8a-e310-49d3-9c02-9c5f6f034352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fecha')]</value>
      <webElementGuid>5c900311-140b-4e18-810d-5705ecb813d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit'])[1]/following::a[1]</value>
      <webElementGuid>78b706d1-c335-4617-880d-f60abb13b5df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sobrantes de Cajero'])[2]/following::a[2]</value>
      <webElementGuid>485b3436-020a-4002-a54f-962a3ba957df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moneda'])[1]/preceding::a[1]</value>
      <webElementGuid>d5082592-8940-488a-87ea-14cae8d7f68c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[1]/preceding::a[2]</value>
      <webElementGuid>0ba38440-3624-4068-bcc7-7703c50080d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fecha']/parent::*</value>
      <webElementGuid>20a6ae24-e1e0-4f5e-8a6a-cecb19429d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:help('VALUE.DATE.1','','','issueToken')&quot;)]</value>
      <webElementGuid>5fd45732-daa7-4153-b327-fa47ee412c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>a4056675-a6c5-40fa-a59f-465c6c7d8743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'fieldCaption:VALUE.DATE.1' and @id = 'fieldCaption:VALUE.DATE.1' and @href = concat(&quot;javascript:help(&quot; , &quot;'&quot; , &quot;VALUE.DATE.1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;issueToken&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Fecha' and (text() = 'Fecha' or . = 'Fecha')]</value>
      <webElementGuid>c2525f5f-516b-4647-8eb5-4176d0f211a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
