<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblDivisaPosicion3</name>
   <tag></tag>
   <elementGuidId>1d2506e6-c4a9-4bfd-a4bf-d4f851540695</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='selectiondisplay']/tbody/tr[3]/td/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2a174817-b6ea-4055-b796-4714c37a413e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>value:3:1:1</value>
      <webElementGuid>7ccabbd3-7269-47b2-ac1a-14a6762a4f22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Divisa</value>
      <webElementGuid>feef07e3-ed84-445b-a4b6-8264e5e41495</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectiondisplay&quot;)/tbody[1]/tr[3]/td[1]/span[1]/label[1]</value>
      <webElementGuid>dbdcfac7-19cc-410e-8ba7-7aae00f6ec22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay']/tbody/tr[3]/td/span/label</value>
      <webElementGuid>ae47edac-e67e-42de-a5b0-1cd1ea2a0365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='igual'])[2]/following::label[1]</value>
      <webElementGuid>4589ee02-ac68-44dd-b728-316c7a7b8f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nro de Caja'])[4]/following::label[1]</value>
      <webElementGuid>b1ddf366-c6a6-44b6-b125-82365f1d90ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='igual'])[3]/preceding::label[1]</value>
      <webElementGuid>ab3a8120-4a00-4446-a91a-b4efac5cc75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Categoria'])[4]/preceding::label[1]</value>
      <webElementGuid>8a5a50bd-16dc-40f7-bab4-4161c80fab82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/span/label</value>
      <webElementGuid>dadc5a4b-92b9-40cc-9d96-5b6cba361129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Divisa' or . = 'Divisa')]</value>
      <webElementGuid>793c9a33-d1f5-48cc-b863-e8c36ae634d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
