<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtvalue111_TipoComision</name>
   <tag></tag>
   <elementGuidId>02794b9a-65a1-45e5-9c88-80eb1628f5d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='value:1:1:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>73dba90a-69c3-4943-96e7-1f8044ed6200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b6da424b-6fec-4c6f-b45f-36cfdebed7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>2419b8bf-eb47-4b36-b51d-c4dd43616813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>5ec40c54-7a7e-4ec1-b2e6-401a75fa1bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>a3b1d19d-97c4-4017-927d-527e6d037832</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frequencydropfieldname</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>a01c9f1a-6eaa-4b78-9d63-d1e7555ea9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqseldata enqseldata_BCCLEACCOMBONIFICACION</value>
      <webElementGuid>7b3fb83e-8952-4e97-a127-39de73dc694f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;value:1:1:1&quot;)</value>
      <webElementGuid>f75566de-7fb2-46f7-a508-fe1ac33f0879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ae27748-23d9-4829-a855-ae645412e0bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d68f2f1f-1578-4bed-ab0d-d3f9b03bec8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>23531ca1-6dfa-4be7-a41b-3e6b02f63ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>5c4d4260-572c-4c48-a42f-39d6920c77aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>432804ee-4d3f-4a9d-aaaa-31fb895f4f85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frequencydropfieldname</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>c787a81a-5906-4a3e-8a48-24b5bad516c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqseldata enqseldata_BCCLEACCOMBONIFICACION</value>
      <webElementGuid>ba99dd16-427e-4089-b610-fc7ba2b9d5cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;value:1:1:1&quot;)</value>
      <webElementGuid>251d9cce-5299-4411-ae9f-93a69609644e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='value:1:1:1']</value>
      <webElementGuid>f349b9c4-df12-4cba-8c9c-0bb8869d51cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay']/tbody/tr/td[3]/input</value>
      <webElementGuid>9036bb33-3239-4339-b185-289cf2d976d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>0d3959ff-eeb8-47d8-b561-0f371919f138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'value:1:1:1' and @id = 'value:1:1:1']</value>
      <webElementGuid>a8022f35-408a-44b8-879a-134a5a5ea8fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
