<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCuenta</name>
   <tag></tag>
   <elementGuidId>02411dcb-1f47-4872-a7e9-7cc0250a0a0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[20]/td[3]/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#r1 > td:nth-child(1)</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'ALTA' or . = 'ALTA')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5cc17154-ed9e-4bb8-a39b-6dfe4c2e643b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled_dealbox disabled_dealbox_ACCOUNT disabled_dealbox_ACCOUNT_BCCLCTAMODCCPJ</value>
      <webElementGuid>d6a3005c-a1ca-453e-8451-f29353f4ab94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALTA</value>
      <webElementGuid>4817eafd-d3d2-4ec0-8273-62509b3d7c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[20]/td[3]/span[@class=&quot;disabled_dealbox disabled_dealbox_ACCOUNT disabled_dealbox_ACCOUNT_BCCLCTAMODCCPJ&quot;]</value>
      <webElementGuid>bbfe9a25-0d02-4165-af26-a7796140dddc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[20]/td[3]/span</value>
      <webElementGuid>43726054-5db9-40c3-a6b6-40cc2796c284</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emision Echeq'])[1]/following::span[1]</value>
      <webElementGuid>5d360c47-4c94-4c52-a2bf-a5ea9ca1f848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[1]/following::span[1]</value>
      <webElementGuid>9a80ca81-807a-499c-a230-f8f0108ea256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Emision Echeq'])[1]/preceding::span[1]</value>
      <webElementGuid>ed428fd4-bc3d-4ecf-bcce-ff4823352f19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pieza Unica'])[1]/preceding::span[2]</value>
      <webElementGuid>8c76eb47-db3e-4d07-a1ac-8a84c9be1a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ALTA']/parent::*</value>
      <webElementGuid>b65e8659-2b9b-467d-b903-8bd21d084760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td[3]/span</value>
      <webElementGuid>d9b49072-d4c5-4c9b-a3e4-eaee76c7db9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ALTA' or . = 'ALTA')]</value>
      <webElementGuid>0cb8d00b-ffb1-4dab-bc80-a99f99292dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
