<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblMontoBloqueoValor</name>
   <tag></tag>
   <elementGuidId>e20a6459-3402-4a25-943a-439380c3387f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r1']/td[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>b5630e89-5204-44b0-8111-4b9f9abe66b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>02bb2afe-7902-4a66-8793-d52b2eda5d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>200,00</value>
      <webElementGuid>218b965d-acc9-4e88-97f6-510036a019de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[7]</value>
      <webElementGuid>9cbb3c20-01da-450c-a543-7d941cfa0311</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[7]</value>
      <webElementGuid>bee0faaa-1d9c-4bed-93d2-36baba034c07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BLOQUEO PARCIAL'])[1]/following::td[1]</value>
      <webElementGuid>bdfc6224-9fb0-4db3-8615-2d04eb7a2767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A METOLA'])[2]/following::td[2]</value>
      <webElementGuid>eef6dc13-cec6-429a-bd8f-decefa200a97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bloqueo General'])[1]/preceding::td[1]</value>
      <webElementGuid>fff2295f-cdfa-4612-b54a-4631dd537609</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bloqueo Parcial'])[1]/preceding::td[2]</value>
      <webElementGuid>1c9b95b0-7b6b-4a79-9745-1bab5f8af479</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='200,00']/parent::*</value>
      <webElementGuid>fedd83f9-99ad-441e-a225-f6d4af744776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>983f77c9-d886-4504-85bb-85a53c0eed24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '200,00' or . = '200,00')]</value>
      <webElementGuid>a272aa0b-5638-4d22-9581-954c6bab9a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
