<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTIPOBLOQUEO2</name>
   <tag></tag>
   <elementGuidId>8afd20b8-3748-430b-8c38-6c064d54b2fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.captionError</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='errors']/tbody/tr/td[3]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9133c088-3b78-427f-8375-2137aedc34a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>captionError</value>
      <webElementGuid>2c8f84b3-5a8a-491a-845b-1abd4bd2502c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7dbf3067-475f-428c-9a45-ebf942685da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TIPO BLOQUEO 2 NO PUEDE APLICARSE DESBLOQ GENERAL</value>
      <webElementGuid>464c7ec8-4982-4166-9229-33417defa44e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errors&quot;)/tbody[1]/tr[1]/td[@class=&quot;errorText&quot;]/span[@class=&quot;captionError&quot;]</value>
      <webElementGuid>edd793da-bd28-4633-9855-63cf6198c1eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='errors']/tbody/tr/td[3]/span</value>
      <webElementGuid>43087955-c631-4f50-be2b-dc0a5648b68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Bloqueo.1'])[1]/following::span[1]</value>
      <webElementGuid>80a2af71-d067-45de-be25-7cb0c7b9bd2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.076 Martinez)'])[1]/following::span[1]</value>
      <webElementGuid>58bc171e-72ae-4fa0-8569-d8130b938211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origen Bloqueo'])[1]/preceding::span[1]</value>
      <webElementGuid>435d71e8-5f64-47b5-8a7c-dd0ec225f0af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUCURSAL PROCESO 076 DIFIERE A SUCURSAL ORIG BLOQUEO'])[1]/preceding::span[1]</value>
      <webElementGuid>d42fb0a1-d472-4d27-aeb1-f18001357c6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='TIPO BLOQUEO 2 NO PUEDE APLICARSE DESBLOQ GENERAL']/parent::*</value>
      <webElementGuid>4ab0abe6-57b0-411a-afc8-dd0cf703bf0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span</value>
      <webElementGuid>2b648e8b-454b-418b-b225-9af427ff3e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'TIPO BLOQUEO 2 NO PUEDE APLICARSE DESBLOQ GENERAL' or . = 'TIPO BLOQUEO 2 NO PUEDE APLICARSE DESBLOQ GENERAL')]</value>
      <webElementGuid>a8b18582-a1c5-441c-92b3-737f226ac98b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
