<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblFechaValor</name>
   <tag></tag>
   <elementGuidId>ee47f8cc-fde8-4166-88c1-3605f92e4bec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r1']/td[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>36ad21d0-848f-4891-ba43-6656583e46c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01-09-2023</value>
      <webElementGuid>609ab2fe-e3a1-43b7-9a74-73a9d00d9c0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[7]</value>
      <webElementGuid>e10a3356-d97f-4972-8829-eb43ff5a041b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[7]</value>
      <webElementGuid>4513370d-086d-4318-858d-ae1b055e17d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impuesto Ley 25.413 Alic Gral s/Debitos'])[1]/following::td[3]</value>
      <webElementGuid>bab13579-fc84-4a48-bd80-b850bf86f1e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FT23244408569813'])[1]/following::td[5]</value>
      <webElementGuid>caf9bf60-c7ae-460a-bfe6-433862d1b913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FT23244610858557'])[1]/preceding::td[5]</value>
      <webElementGuid>4fc65fc3-2e09-460d-b5a4-58bf34fa6d9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impuesto Ley 25.413 Alic Gral s/Debitos'])[2]/preceding::td[7]</value>
      <webElementGuid>3eacf1a6-6314-4d2f-b8d4-51224854f7bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]</value>
      <webElementGuid>17960e33-a219-45f0-9ace-26183aba0ae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '01-09-2023' or . = '01-09-2023')]</value>
      <webElementGuid>1ad9f481-df45-40f5-90d4-dfe25f91ddc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
