<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbEstadoDropdown</name>
   <tag></tag>
   <elementGuidId>5474a7fb-12d7-4baa-80dd-64160b0e6e05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.dropdown_button.dropdown_button_BCCLACCONSULTAXESTADO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='selectiondisplay']/tbody/tr[2]/td[4]/a/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@class = 'dropdown_button dropdown_button_BCCLACCONSULTAXESTADO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>24f8577b-ea96-4495-b549-c15cf9e76fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/dropdown.gif</value>
      <webElementGuid>488ef4c6-9f93-4acd-9a8a-9943d6e57fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_BCCLACCONSULTAXESTADO</value>
      <webElementGuid>f1d2cdc4-30aa-4de3-b47a-14f5faf5882f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectiondisplay&quot;)/tbody[1]/tr[2]/td[4]/a[1]/img[@class=&quot;dropdown_button dropdown_button_BCCLACCONSULTAXESTADO&quot;]</value>
      <webElementGuid>867b7155-4544-451f-9f00-d376ddf858a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay']/tbody/tr[2]/td[4]/a/img</value>
      <webElementGuid>08c8dcb7-02d5-4e81-846a-627609cbb691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>61b4fe2c-842e-4d45-8043-9b43a2a7cefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/deal/dropdown.gif']</value>
      <webElementGuid>cb2d1291-dfbb-4f13-95ec-a5d8638f9c41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
