<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnObservaciones</name>
   <tag></tag>
   <elementGuidId>d53d25ad-6714-4423-a380-281c53b007a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#image8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='image8']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>c55ee788-447d-4b50-9104-ea44490c503e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image8</value>
      <webElementGuid>4c709863-8e08-4d56-87e0-e5950db7cec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columnno</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>0d22c57a-f7ad-44a8-8368-3d1ca2c84b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hideable</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>8bda8a8a-f977-4793-bddc-ca7f0cd86f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/expand.gif</value>
      <webElementGuid>952bdf45-f3b6-4bfa-8047-1f3bc688c136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c663c6d4-c431-4dfd-8820-a32e51e1bfcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Observaciones</value>
      <webElementGuid>09ec5021-5a95-4203-87ae-e0104983de07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Observaciones</value>
      <webElementGuid>c49ad2a1-8326-467d-a55d-4df5f5f2a835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image8&quot;)</value>
      <webElementGuid>0cf75035-2db0-444d-aed8-b8fd332e51ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='image8']</value>
      <webElementGuid>5bea6736-32f3-4d4b-b4aa-a2d1a64ac561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader8']/table/tbody/tr/th[2]/a/img</value>
      <webElementGuid>16a69deb-aacf-4cf5-bf97-5d82afb9ef4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Observaciones']</value>
      <webElementGuid>42b3a6c9-8d31-44fb-ac1e-5602e4525bbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/a/img</value>
      <webElementGuid>2716d44c-3df9-4382-ad28-9d1dadb0c532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'image8' and @src = '../plaf/images/bccl/tools/expand.gif' and @alt = 'Observaciones' and @title = 'Observaciones']</value>
      <webElementGuid>e83aefce-841a-42a2-808f-803ddd2e4338</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
