<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnLupaF2</name>
   <tag></tag>
   <elementGuidId>1a5ab54f-2b80-4285-aa41-f2ae9befe6d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Pantalla de Seleccion&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='enquiryData']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f1345a10-d346-4f73-b28b-acfbd054d06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/select.gif</value>
      <webElementGuid>48f415f7-b74b-4b69-8fb3-c111e4769d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pantalla de Seleccion</value>
      <webElementGuid>608d9b02-b496-4b93-8f37-ab3c9f6b9a69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pantalla de Seleccion</value>
      <webElementGuid>ae4528eb-f1e3-4a17-8c89-1d3d211af6e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enquiryData&quot;)/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[1]/td[2]/a[@class=&quot;keyboardlinks-scanned&quot;]/img[1]</value>
      <webElementGuid>fe910a19-6250-451b-b691-729131a36ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/39-Cuentas/Mantenimiento/frmBusquedaPersonaFisica2</value>
      <webElementGuid>3bd23a7f-4f5a-40c3-81b2-42a7c4130e5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enquiryData']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>3c37bd19-e5f9-4530-9d0b-50f1ac0b9706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pantalla de Seleccion']</value>
      <webElementGuid>3dc028eb-684c-4314-bb44-a83830d2cf8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/img</value>
      <webElementGuid>b3d201d9-52ab-4359-9781-977b7c9d210c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/tools/select.gif' and @alt = 'Pantalla de Seleccion' and @title = 'Pantalla de Seleccion']</value>
      <webElementGuid>2a62ee57-b82e-47a6-bd2f-7ce632b75964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
