<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblDomicilioF3S3</name>
   <tag></tag>
   <elementGuidId>a1cc5770-f885-452e-a757-c6aba646e9d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dropDownRow1']/td/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>7d3af510-e5b1-48e2-826a-5a312d43d64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1002548728-1-CALLE 1002548728</value>
      <webElementGuid>36d6c57e-e7fe-4601-a52b-d765b19754d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownRow1&quot;)/td[1]/b[1]</value>
      <webElementGuid>b591dd7b-edf2-41d0-92ca-7c717b6f60be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/39-Cuentas/Mantenimiento/frmBusquedaPersonaFisica3</value>
      <webElementGuid>ae8629b8-2236-407d-9660-5d8422eee75f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dropDownRow1']/td/b</value>
      <webElementGuid>a11cebdd-fed1-4f51-b224-d8cda5864762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Otro Details'])[1]/following::b[1]</value>
      <webElementGuid>1c1c5e83-1f16-47c7-b531-bb42ee4ddc22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Domicilios'])[1]/following::b[1]</value>
      <webElementGuid>bd027221-0e6b-4406-be6d-f5186c6b4d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CALLE 1002548728-791-LOCALIDAD 1002548728-BUENOS AIRES'])[1]/preceding::b[1]</value>
      <webElementGuid>dadc4448-37cd-4a2a-b392-82c110a62f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1002548728-1-CALLE 1002548728']/parent::*</value>
      <webElementGuid>6c5e542a-5725-4799-a93e-d389eefc87ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>e8865f51-037a-4ef0-aee4-cecb1d2c1690</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '1002548728-1-CALLE 1002548728' or . = '1002548728-1-CALLE 1002548728')]</value>
      <webElementGuid>24959f80-9573-45b9-8f78-33119ff44828</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
