<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtCantidadCienPesos</name>
   <tag></tag>
   <elementGuidId>06d55a23-3e17-4fdb-bb26-0758c375cd35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>#fieldName\:DR\.UNIT\:10</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fieldName\:DR\.UNIT\:10</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2ee5e30-a6e5-4e3e-bfc3-75d9978bf716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7d91465d-10ea-4d53-9937-7a59659c9002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>596b2e0e-5cad-4087-a39a-dc129226063a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:DR.UNIT:11</value>
      <webElementGuid>452f2f65-3d07-4d0b-85e8-94f4fa7c1105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:DR.UNIT:11</value>
      <webElementGuid>1dd9b361-162a-44eb-8aba-b7bb045d802b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab2</value>
      <webElementGuid>1bda6256-41fb-4495-af47-04fe6a3ab9c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>08171fc0-df13-49e2-8e82-948c5123abf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7f12e895-1064-418d-bba4-9475ce777e10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>637ffd2d-c3fb-4108-a1dd-1b9eb5e3def7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_TELLER dealbox_TELLER_ENVIOCAJA</value>
      <webElementGuid>ca63669a-529b-43e9-be34-c0eb8ed4efdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>010</value>
      <webElementGuid>bd5aa558-9985-4483-a006-71d382cd23d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d887bacb-3728-49c7-bd74-99e928be2b26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_DR.UNIT:11</value>
      <webElementGuid>6de48e7a-28a8-484d-80e6-ea7f1ccec8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'DR.UNIT','issueToken');</value>
      <webElementGuid>26ad7dce-15dc-42ee-8099-07ce0451c838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>065553de-b77c-45a4-a2ac-a65923d1404e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('DR.UNIT','','','issueToken')</value>
      <webElementGuid>7959767b-6e87-4e7e-999a-7efb7b1f5a90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:DR.UNIT:11&quot;)</value>
      <webElementGuid>16a5cdca-f286-4fda-9d5b-7f34106f8d23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:DR.UNIT:11']</value>
      <webElementGuid>69268b11-f613-456a-b43f-addf6ac6115e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab2']/tbody/tr[22]/td[4]/input</value>
      <webElementGuid>ddd7a4c2-7dbc-4541-a0bb-b5f33883894d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[22]/td[4]/input</value>
      <webElementGuid>80f05962-7481-42d7-8d2c-cebe562039e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:DR.UNIT:11' and @name = 'fieldName:DR.UNIT:11' and @type = 'text']</value>
      <webElementGuid>29611061-84a3-4a3e-9874-38f8d42eeb1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
