<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblSuc</name>
   <tag></tag>
   <elementGuidId>c06e6ad1-037b-44e8-91d0-aaeef05a2b19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>fb5b5310-a991-434a-821f-4d63f10ffa05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>ec3756ce-7779-43b3-b9bc-9a269e0a2f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>77d2a308-64ba-42fd-a52b-2c251890cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText1</value>
      <webElementGuid>5afe21cf-27d5-48c2-865c-8781f592c824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Suc.</value>
      <webElementGuid>a32705f7-af1a-4bca-abb4-5a0dd522734c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText1&quot;)</value>
      <webElementGuid>46705e7b-cc25-4dca-8dd7-5406a28c1116</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText1']</value>
      <webElementGuid>dbf57827-fc1b-4480-b1cf-d5328aa0f0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader1']/table/tbody/tr/th</value>
      <webElementGuid>8197a521-053e-4b65-86b5-5e9bfb5b5054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como XML'])[2]/following::th[3]</value>
      <webElementGuid>91ba8776-ed72-4696-9ad7-5b1cf9ca198a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como HTML'])[2]/following::th[3]</value>
      <webElementGuid>a4c61c1d-436b-4e3c-bd42-be16d91cb5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Rech.'])[1]/preceding::th[2]</value>
      <webElementGuid>427e622b-e5b6-496c-beba-bacff32048f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Origen'])[1]/preceding::th[5]</value>
      <webElementGuid>f748de38-3861-41d2-8220-606af21d353a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Suc.']/parent::*</value>
      <webElementGuid>01ce0732-cd42-4579-ac27-3d6194d01db3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th</value>
      <webElementGuid>4d74c45b-98d4-427c-8c05-2e60feac2f20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText1' and (text() = 'Suc.' or . = 'Suc.')]</value>
      <webElementGuid>b5b765a7-49f1-4d76-baf6-1c3ec6de4ce5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
