<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDrilldown</name>
   <tag></tag>
   <elementGuidId>086ab9a2-9a2c-406b-a877-05857adde11a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Select Drilldown&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r1']/td[8]/table/tbody/tr/td[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5b7b3a4c-d688-4a88-bcd9-54b72288afb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Select Drilldown</value>
      <webElementGuid>1c342d9e-e329-4b0f-b692-10bad0ddd9d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/menu/go.gif</value>
      <webElementGuid>221adf43-1750-4492-b5f2-490206e6e628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_BCCLEVERCUENTAAMBI&quot;]/table[1]/tbody[1]/tr[@class=&quot;enqdrilldowncell enqdrilldowncell_BCCLEVERCUENTAAMBI&quot;]/td[2]/a[@class=&quot;iconLink&quot;]/img[1]</value>
      <webElementGuid>0ef0ca6f-54c9-4791-be9c-bc5a43de9cbf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[8]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>36fa583c-eebc-45d9-81c8-32b423032e32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Select Drilldown']</value>
      <webElementGuid>33c353a5-c17b-4efd-956c-abf2516088da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>371fa6de-00d2-4821-b771-9b014fb16f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Select Drilldown' and @src = '../plaf/images/bccl/menu/go.gif']</value>
      <webElementGuid>6bd41af4-5a17-4e88-a43a-f18e76c54da7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
