<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnExpandirMultivalor</name>
   <tag></tag>
   <elementGuidId>b926f18d-a871-4112-86c4-404a8af73522</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Expandir Multivalor&quot;] > img.ascell.ascell_BCCLEBGRUPOCODOPE.ascell_BCCLEBGRUPOCODOPE_ALTA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[3]/td[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad4efc60-cb84-4d4b-a367-143037ff0ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ascell ascell_BCCLEBGRUPOCODOPE ascell_BCCLEBGRUPOCODOPE_ALTA</value>
      <webElementGuid>c755b9e0-4e81-40f3-9a19-4107864a2508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/mvexpansion.gif</value>
      <webElementGuid>9ae10c1f-c463-4d96-ae5e-45d5f35f303f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Expandir Multivalor</value>
      <webElementGuid>e7bd7c7e-1e4f-47bf-9fa8-dca82c6dfe14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Expandir Multivalor</value>
      <webElementGuid>4135e57a-9493-4dbf-a79b-6187e98c7253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[3]/td[@class=&quot;action_container action_container_BCCLEBGRUPOCODOPE action_container_BCCLEBGRUPOCODOPE_ALTA&quot;]/a[1]/img[@class=&quot;ascell ascell_BCCLEBGRUPOCODOPE ascell_BCCLEBGRUPOCODOPE_ALTA&quot;]</value>
      <webElementGuid>cf25e982-6f21-480f-9dc4-cab83763298b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[3]/td[3]/a/img</value>
      <webElementGuid>a04ed7c2-652a-4331-8090-529ae2992180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Expandir Multivalor']</value>
      <webElementGuid>d2ee6aad-bf98-4963-a72c-a53cc0c94223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/img</value>
      <webElementGuid>5a448ef5-2e02-4552-8b73-91c893745ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/deal/mvexpansion.gif' and @alt = 'Expandir Multivalor' and @title = 'Expandir Multivalor']</value>
      <webElementGuid>26e2bef4-c148-4588-85ae-b2d246d3599e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
