<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkRegistrarDenuncia</name>
   <tag></tag>
   <elementGuidId>0e190b9c-60b0-44cc-90ed-ff27d005ac9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.enqDrillLink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r1']/td[12]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b4f9c86d-e9c4-4c00-ba51-267351aafbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqDrillLink</value>
      <webElementGuid>8f41f6bf-513f-4984-b0b3-0f981fdef38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>53243866-5383-4a8c-ad39-9a14d4e4d05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:drilldown('1','1_1')</value>
      <webElementGuid>d7d60ffe-9080-4755-bd39-2bfa2ab879aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registrar Denuncia</value>
      <webElementGuid>d35b2373-70e7-4721-98e5-13f6e45ae7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_BCCLAPEAPESTADODENUNCIA&quot;]/a[@class=&quot;enqDrillLink&quot;]</value>
      <webElementGuid>bcd8faa2-f4e3-4c58-ab62-cd744ade0e20</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[12]/a</value>
      <webElementGuid>c488217c-034c-4507-815c-e3a4b8c1cf0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Registrar Denuncia')]</value>
      <webElementGuid>f16ffc21-593d-4e07-bd49-922588e0d904</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::a[1]</value>
      <webElementGuid>cf74c700-495a-4571-b52f-dd57a17e9751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BARRETO LUCAS EZEQUIEL'])[1]/following::a[1]</value>
      <webElementGuid>af04064b-b137-4044-a715-217e95bf42d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favoritos'])[1]/preceding::a[1]</value>
      <webElementGuid>557fb055-07a2-450c-b296-dd357eb9f2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCCL.AP.E.AP.ESTADO.DENUNCIA'])[2]/preceding::a[1]</value>
      <webElementGuid>4d272ba6-d8ba-4919-827e-6f9b965e9d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registrar Denuncia']/parent::*</value>
      <webElementGuid>dec1e82c-86c3-4dc8-8b3e-0c15d6ece5ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:drilldown('1','1_1')&quot;)]</value>
      <webElementGuid>d8545dfc-92bd-4617-9181-c8d9c133ca3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[12]/a</value>
      <webElementGuid>10adaab4-b877-481e-a29e-770683862f3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:drilldown(&quot; , &quot;'&quot; , &quot;1&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;1_1&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Registrar Denuncia' or . = 'Registrar Denuncia')]</value>
      <webElementGuid>4f66ef28-7413-4421-b4bf-d78e1f3962b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
