<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblSecuencia</name>
   <tag></tag>
   <elementGuidId>1456ea74-984f-42f5-afaa-f83d7d80decb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText2']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Secuencia' or . = 'Secuencia')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>225fc085-332f-4a7b-b13e-25ff61845d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>3c2097d5-c34f-40d4-91b3-6f3f785b0fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>8a7ccb85-fd59-4953-8c2d-35ab4be576bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText2</value>
      <webElementGuid>8d6f6a38-3242-4387-aafe-a93179bef1d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Secuencia</value>
      <webElementGuid>38bdf713-f893-4ae8-a348-3f8438916c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText2&quot;)</value>
      <webElementGuid>d10cb35d-9759-4df7-a305-4a2a736699c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText2']</value>
      <webElementGuid>5cf0ada2-f4e6-4a56-9e62-0e03219ab79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader2']/table/tbody/tr/th</value>
      <webElementGuid>bb551b92-edf0-4bd3-addc-c32f6cc1b887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='@ID'])[1]/following::th[3]</value>
      <webElementGuid>40ff3b57-bf52-4c4c-9491-f9734098ed00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cod. Empresa'])[1]/preceding::th[2]</value>
      <webElementGuid>daaf46d3-f8e3-405f-8622-186eab26e0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cod. Sub Empresa'])[1]/preceding::th[5]</value>
      <webElementGuid>cbb15fc0-6f95-4acf-ab60-9964d88a77dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Secuencia']/parent::*</value>
      <webElementGuid>82c5a702-3617-4982-ae53-1199175820c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/table/tbody/tr/th</value>
      <webElementGuid>3e4b1f5c-c788-4b7c-aaea-7bdba0e2b813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText2' and (text() = 'Secuencia' or . = 'Secuencia')]</value>
      <webElementGuid>642c62d4-644f-4cdf-bd98-7faa637f1130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
