<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblSECUENCIA</name>
   <tag></tag>
   <elementGuidId>18cc51d2-7aa5-45ee-abf1-247446e5160a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText3']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>62165a4f-dd6c-4f13-bb94-c8681038957d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>3db83188-d648-4992-98be-6fe279ae1dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>5da32925-8d50-4ffd-9de1-9e4b9e66e313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText3</value>
      <webElementGuid>5e11fc7e-3b6a-4570-8c04-43e8cbeef315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SECUENCIA</value>
      <webElementGuid>f98fbd89-324d-43c1-a4a1-95f5f3901628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText3&quot;)</value>
      <webElementGuid>c30c2415-bd9c-4d54-8b08-11a45a977872</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText3']</value>
      <webElementGuid>08597402-5aae-4515-82f5-b643ad40712e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader3']/table/tbody/tr/th</value>
      <webElementGuid>4491457d-e3c4-4470-a00b-72ddbb4df862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TARJETA'])[1]/following::th[3]</value>
      <webElementGuid>2f917f2e-93c8-4263-b54d-c18d69f27c72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID'])[1]/following::th[6]</value>
      <webElementGuid>3582498c-8712-4bf4-9c0b-ee28a6e72941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MONTO DEPOSITADO'])[1]/preceding::th[2]</value>
      <webElementGuid>1b2ec0c9-a992-4f31-accc-6480be7c8e3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MONTO REAL DEPOSITO'])[1]/preceding::th[5]</value>
      <webElementGuid>d4d12ee2-fad8-46cf-b0c5-e4edd0825f29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SECUENCIA']/parent::*</value>
      <webElementGuid>62390523-b8fe-45f3-89cc-740db089084f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/table/tbody/tr/th</value>
      <webElementGuid>2297f7af-9f70-4c2a-966f-b5d3702148f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText3' and (text() = 'SECUENCIA' or . = 'SECUENCIA')]</value>
      <webElementGuid>05be5609-e428-47e6-9a81-352fca061214</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
