<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAudit</name>
   <tag></tag>
   <elementGuidId>66dadb86-83c0-4341-b330-066f30652da4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='headtab']/tbody/tr/td[3]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.nonactive-tab > span:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a436fa3e-eaf9-4d51-ab4e-52db8b14e40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Audit</value>
      <webElementGuid>404f5d43-f21a-4f0f-a0a1-cf4b13d6931b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headtab&quot;)/tbody[1]/tr[1]/td[3]/a[@class=&quot;nonactive-tab&quot;]/span[1]</value>
      <webElementGuid>d62d5767-8cca-49ab-8d1e-777a0051b64c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='headtab']/tbody/tr/td[3]/a/span</value>
      <webElementGuid>81e404c3-a187-44bc-a48f-4f086d95f0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impuestos y Comisiones'])[1]/following::span[1]</value>
      <webElementGuid>53064060-f859-4ab8-a67a-920f5398cd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresos Varios de Caja'])[2]/following::span[2]</value>
      <webElementGuid>5054345b-e9fd-44ce-8aec-01151d9dcd6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha'])[1]/preceding::span[1]</value>
      <webElementGuid>78da2fd4-c661-4b88-b297-6be3d45ac326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moneda'])[1]/preceding::span[3]</value>
      <webElementGuid>24a3554b-882c-4eea-bbb4-eff4fafea8d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Audit']/parent::*</value>
      <webElementGuid>1e09c0dd-9625-4492-a351-a4bfe29a481e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/span</value>
      <webElementGuid>b42952bc-ffb1-4cb0-a1a3-185924d975d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Audit' or . = 'Audit')]</value>
      <webElementGuid>8e2138fa-4935-4193-9cc6-9bf46e690367</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
