<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkAceptarAlertas</name>
   <tag></tag>
   <elementGuidId>58705bd6-dffb-4ccc-a535-f9b2fe79edc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='errorImg']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.textbtn > a:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9ac850bb-446b-4f76-9c18-eba1fd552ad0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>63332c83-c06d-4a5f-b6ef-c67553bf2fcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>errorImg</value>
      <webElementGuid>6a7ccae5-2c38-4822-9102-893e933cb40a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:commitOverrides()</value>
      <webElementGuid>4ad1207a-723d-48ca-859a-82567e201d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar Alertas</value>
      <webElementGuid>02c3ec70-ff34-464b-b2cb-9c9d8aab353e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;errorImg&quot;)</value>
      <webElementGuid>e5c27418-2c4f-4e32-9f69-9fee9569c031</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='errorImg']</value>
      <webElementGuid>cc18f7cc-eeab-4770-a2c5-5db0a9ff8ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='error_box']/table/tbody/tr[3]/td/table/tbody/tr/td/a</value>
      <webElementGuid>9a751aa8-ed03-452d-9c7a-c22f45324b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Aceptar Alertas')]</value>
      <webElementGuid>d5ead8ba-23ea-4a86-a591-00f311816428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.089 M.del Plata Ctr)'])[1]/following::a[1]</value>
      <webElementGuid>ad74f922-5f96-432b-93ba-38fc1d0aa4ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RCP2220861400775'])[1]/following::a[1]</value>
      <webElementGuid>7d8b7201-ff89-484b-8f5b-a55c31901c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SE COBRARA 72.6 ARS POR COMISIONES Y SUS IMPUESTOS'])[1]/preceding::a[1]</value>
      <webElementGuid>666bfad9-6a56-405c-9d1f-5e6e3f1dbb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RESUMEN DE CUENTA A PEDIDO'])[2]/preceding::a[1]</value>
      <webElementGuid>b3dadf5d-70fe-453e-83e7-aa5a84bf4bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceptar Alertas']/parent::*</value>
      <webElementGuid>ca035386-60a0-4dc2-829c-0f595838e4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:commitOverrides()')]</value>
      <webElementGuid>b68ef7e6-2e06-4870-b4f4-c6b874363ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/a</value>
      <webElementGuid>7c2bf5e8-de47-4ecf-9d90-f63a9a91a057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'errorImg' and @href = 'javascript:commitOverrides()' and (text() = 'Aceptar Alertas' or . = 'Aceptar Alertas')]</value>
      <webElementGuid>0fd4eed4-d0c7-4e3a-8eef-b29532242d4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
