<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnModificarRegistro</name>
   <tag></tag>
   <elementGuidId>05f96373-2ca4-4c3b-87ca-c34d2c6b35aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Modifica registro&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1658a455-e67e-4216-8410-60a64c13e094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/txnedit.gif
															</value>
      <webElementGuid>7d40abb7-21d8-43c7-9c6e-e282ec6be204</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Modifica registro</value>
      <webElementGuid>f7638cbd-6cc9-45e6-9854-d5a62c60ed1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Modifica registro</value>
      <webElementGuid>9020a176-c0a1-45cc-aaa4-898936bab5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goButton&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[1]/a[1]/img[1]</value>
      <webElementGuid>4d985ca4-0d19-4a72-b02b-b622712cf000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td/a/img</value>
      <webElementGuid>99ec6280-e4c5-482b-b8a8-2176682ffcf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Modifica registro']</value>
      <webElementGuid>3f61a2e4-7e1f-451d-8f7a-21e5639b9fff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/img</value>
      <webElementGuid>efd50ec0-f068-4639-81f8-68703beeb38e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/tools/txnedit.gif
															' and @alt = 'Modifica registro' and @title = 'Modifica registro']</value>
      <webElementGuid>e358f6c6-57c9-487b-8086-d39f441708ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
