<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCUO</name>
   <tag></tag>
   <elementGuidId>b10c73d8-139a-4bc8-bb4f-0f05e44d0d92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dropDownRow6']/td/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#dropDownRow6 > td.coloumntddata.coloumntddata_BCCLEMOTIVOTINT > b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>ea646871-19b1-4f7c-93b4-4e0f8110f64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CUO</value>
      <webElementGuid>868eba04-0766-4da4-8007-80a143ee275d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownRow6&quot;)/td[@class=&quot;coloumntddata coloumntddata_BCCLEMOTIVOTINT&quot;]/b[1]</value>
      <webElementGuid>346027d8-6daa-4849-b296-f87529dcd7c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dropDownRow6']/td/b</value>
      <webElementGuid>a061b293-c94a-464f-8c15-de3ae9443f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compra con Transferencia'])[1]/following::b[1]</value>
      <webElementGuid>a8ad69c9-dce3-4e4a-a5ab-8d74219e6fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CCT'])[1]/following::b[1]</value>
      <webElementGuid>53b5e259-345d-4c7c-86e9-f5ec021a4e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuota'])[1]/preceding::b[1]</value>
      <webElementGuid>edf58211-f066-4ea6-99c9-ec99e3cf3813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DCT'])[1]/preceding::b[1]</value>
      <webElementGuid>3b89d6fc-cce3-4873-9bd5-977b38186b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CUO']/parent::*</value>
      <webElementGuid>64154357-49ee-4b26-b076-47bcade25cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/b</value>
      <webElementGuid>a3031e53-f3ca-4b78-92fb-e74e778453f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'CUO' or . = 'CUO')]</value>
      <webElementGuid>5671b1bb-4797-407a-87e9-a2b0bda404d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
