<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblPosicion4</name>
   <tag></tag>
   <elementGuidId>3515b48c-87fe-470e-a2b2-7478700c2560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='selectiondisplay']/tbody/tr[4]/td/span/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>f8c0cc84-98b0-4602-acf2-f8e500ee1261</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>value:4:1:1</value>
      <webElementGuid>342167b0-4a91-4177-998f-f068dc2f6c26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha Valor</value>
      <webElementGuid>a11411a9-23c6-4def-a0f4-55f384da67a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectiondisplay&quot;)/tbody[1]/tr[4]/td[1]/span[1]/label[1]</value>
      <webElementGuid>7a09d4a8-ea27-47e8-a900-0753b4ccc01a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay']/tbody/tr[4]/td/span/label</value>
      <webElementGuid>e6c5a90b-da9c-491b-ae3d-8a3e3ae2f494</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='igual'])[3]/following::label[1]</value>
      <webElementGuid>d6ccdbaa-f4a4-46db-8855-b146c318cfee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Circular'])[4]/following::label[1]</value>
      <webElementGuid>52bb8185-ecc7-4879-9599-21fe66e0c618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='igual'])[4]/preceding::label[1]</value>
      <webElementGuid>ec5c8a9e-7f17-4c84-8c95-3cd066268fda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AR0011074 : BCCL.MM.ACTIVOS.FVENC.MM'])[1]/preceding::label[1]</value>
      <webElementGuid>ed61b107-f7ca-44eb-91ce-09c7ddeb1b3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/span/label</value>
      <webElementGuid>c6f1c23e-cc93-41eb-a1eb-2da4173f15d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Fecha Valor' or . = 'Fecha Valor')]</value>
      <webElementGuid>0f7f91ad-e330-4b11-aa10-2d22719037e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
