<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblSucursal</name>
   <tag></tag>
   <elementGuidId>bd819a65-233d-466b-9e58-22b560077f59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Sucursal' or . = 'Sucursal')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>131955c6-1c48-40ee-96e4-0b74504ffcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>37b79ab7-b7d8-4d37-a3eb-9b28d632e938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>9815e09a-d075-41d6-8640-78ed50e9871f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText1</value>
      <webElementGuid>67e62541-ef8d-41c9-8fa4-2f69cbdcf33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sucursal</value>
      <webElementGuid>392bc62f-acae-4a29-9504-43783cb45e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText1&quot;)</value>
      <webElementGuid>a8e48ea3-c589-4f6f-abfc-172c91d38d93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText1']</value>
      <webElementGuid>17c91125-975b-4148-ae6c-9977e4661269</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader1']/table/tbody/tr/th</value>
      <webElementGuid>b79ecd56-d250-4546-9d59-83386b9af3f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como XML'])[2]/following::th[3]</value>
      <webElementGuid>a1508635-ea8c-44ac-bad9-ac274b7c1c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como HTML'])[2]/following::th[3]</value>
      <webElementGuid>05e28424-0869-4755-9494-7d22188c8b73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuenta'])[1]/preceding::th[2]</value>
      <webElementGuid>f909a9c3-d3ba-441f-8a95-ed769575502d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nombre Cuenta'])[1]/preceding::th[5]</value>
      <webElementGuid>7e91add2-8857-4d68-9e1f-92c45e0631e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sucursal']/parent::*</value>
      <webElementGuid>9df437f0-031b-4bfa-b49c-f4b729bf947d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th</value>
      <webElementGuid>aec5f0dc-e9ec-4083-8a8c-2d47aafeb68d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText1' and (text() = 'Sucursal' or . = 'Sucursal')]</value>
      <webElementGuid>e21ab40c-20c4-4b96-8490-03fede8707c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
