<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblNroPersona</name>
   <tag></tag>
   <elementGuidId>e84871d6-6967-4206-9cbe-c905f9bc192b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>d6a32465-1d09-43bc-a7b0-da2742b3c3f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>a9241bd2-f04d-4e03-93b4-2381420cee32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>79040e51-670c-4e84-8919-6c50518b165d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText1</value>
      <webElementGuid>ca1778e0-5daa-4da8-b447-9008bd44ae04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No. Persona</value>
      <webElementGuid>a3e46d42-4b19-4b69-af54-83750b5dbb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText1&quot;)</value>
      <webElementGuid>931fc2ba-4d13-40b5-9185-58837b74d1bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText1']</value>
      <webElementGuid>22da795a-efc6-467c-9ff7-30289c5d3b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader1']/table/tbody/tr/th</value>
      <webElementGuid>1bc625f4-8098-4705-aea6-ee18ed6e584b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como XML'])[2]/following::th[3]</value>
      <webElementGuid>8507ddf7-24af-49f4-8f7a-c55d2a1979fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como HTML'])[2]/following::th[3]</value>
      <webElementGuid>330a0718-d34c-4993-af75-9445068083dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='T.Doc.BUP'])[1]/preceding::th[2]</value>
      <webElementGuid>ca9649a5-d1b8-4542-b3a5-ccd704e03e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nro.Doc BUP'])[1]/preceding::th[5]</value>
      <webElementGuid>5aceb055-60f5-4c42-b51f-446c9b69f636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='No. Persona']/parent::*</value>
      <webElementGuid>e6711ee5-dfde-4327-bcc2-623b286b7448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th</value>
      <webElementGuid>f2bddff4-fdd9-4ec7-8014-c123fa61fd34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText1' and (text() = 'No. Persona' or . = 'No. Persona')]</value>
      <webElementGuid>803e55dc-73a1-42ca-a19f-aa5e960de639</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
