<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkEjecutar</name>
   <tag></tag>
   <elementGuidId>0a136ffb-a5e5-43c3-a919-57732397bd56</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='doHighlight(this);javascript:
						   toggleStateButton();doEnquiry()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.textbtn</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3decd06b-f3cc-4bc0-8046-995d9b5d7f4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Ejecutar</value>
      <webElementGuid>a8b2e156-d3ce-494c-bd99-f59e7e095808</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Ejecutar</value>
      <webElementGuid>250b8397-23bf-4af7-bb46-827ac3bdc6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textbtn</value>
      <webElementGuid>dbdef14b-4c2d-4136-86ed-ed0886af468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>c1429919-35d5-4e66-b942-098d6b1e1c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>b1a50c10-7a1b-43e3-8b65-584324d96de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>doHighlight(this);javascript:
						   toggleStateButton();doEnquiry()</value>
      <webElementGuid>d9501c68-1fa4-45b9-a83a-d4fa1be4f0a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>e8881c36-9ee5-49e8-aeb8-61988efd0083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ejecutar</value>
      <webElementGuid>f9fa5c14-e6d4-41f7-b12a-96c03fe51b8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqsel&quot;)/table[@class=&quot;enqsel-main enqsel-main_BCCLPEREVOLTAMEMP&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;display_box display_box_BCCLPEREVOLTAMEMP enqsel-selections enqsel-selections_BCCLPEREVOLTAMEMP&quot;]/tbody[1]/tr[1]/td[1]/table[@class=&quot;header-table header-table_BCCLPEREVOLTAMEMP&quot;]/tbody[1]/tr[@class=&quot;caption caption_BCCLPEREVOLTAMEMP&quot;]/td[3]/div[1]/table[1]/tbody[1]/tr[1]/td[1]/a[@class=&quot;textbtn&quot;]</value>
      <webElementGuid>5a5ce5f1-0db5-4d8c-93ef-6ce64ff70b0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='doHighlight(this);javascript:
						   toggleStateButton();doEnquiry()']</value>
      <webElementGuid>be1f0f85-8ec0-43d7-8cc2-7f2249fa77d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enqsel']/table/tbody/tr/td[2]/table/tbody/tr/td/table/tbody/tr/td[3]/div/table/tbody/tr/td/a</value>
      <webElementGuid>c3e80e9b-56c9-414e-aa81-5d89a5c4e08b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ejecutar')]</value>
      <webElementGuid>47491219-baab-4d4e-b429-37ee66df738d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nueva Seleccion'])[1]/following::a[1]</value>
      <webElementGuid>7eeb6402-dc0c-4314-b4ed-cc3300337339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mas Opciones'])[1]/following::a[2]</value>
      <webElementGuid>0d0f42d3-8fa8-4e71-8d0a-2d4767004899</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ordenar Por:'])[1]/preceding::a[1]</value>
      <webElementGuid>2981bebd-6868-4fb8-b6f8-7939e7dcb6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ejecutar']/parent::*</value>
      <webElementGuid>d94ecbc8-8409-493a-bcaf-cbebc2b59989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0)')]</value>
      <webElementGuid>f78c069f-57cf-4a1e-87f9-baf5ddb8934f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr/td/a</value>
      <webElementGuid>d1822538-b365-4af0-8532-5ddedefd00ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@alt = 'Ejecutar' and @title = 'Ejecutar' and @href = 'javascript:void(0)' and (text() = 'Ejecutar' or . = 'Ejecutar')]</value>
      <webElementGuid>87567b9a-322b-4993-8bcb-5c241f86f0b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
