<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtUsuario</name>
   <tag></tag>
   <elementGuidId>d22d2859-52e5-4833-8447-707b80ae5db1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='value:2:1:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42df89ca-f968-4e8a-a645-3bdfafd928a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>08374cbe-78d1-48c9-ac1a-19dfc9561773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value:2:1:1</value>
      <webElementGuid>d2e1693d-1067-433e-b5de-977869f774d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>value:2:1:1</value>
      <webElementGuid>9a828791-a1c7-4a2d-ae04-c38c49b2e974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ff2b1cbd-f299-4906-9a07-bb8bb335e07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frequencydropfieldname</name>
      <type>Main</type>
      <value>value:2:1:1</value>
      <webElementGuid>79ffc5d6-3087-4662-af75-d81b5c324a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqseldata enqseldata_BCCLEEBCONSREVE</value>
      <webElementGuid>7b11cd56-4b6f-42de-ba4e-e78ff3e47564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;value:2:1:1&quot;)</value>
      <webElementGuid>5cd1db9c-7cdf-4e3c-aeb2-bd1e8df03bf3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='value:2:1:1']</value>
      <webElementGuid>d82e0b38-af90-4958-9450-419a7c039129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay']/tbody/tr[2]/td[3]/input</value>
      <webElementGuid>11a3578c-2bd7-4970-8ef0-acd49c67ffd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/input</value>
      <webElementGuid>20fe9bf8-2dc3-46fc-95c4-feccebcacf5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'value:2:1:1' and @id = 'value:2:1:1']</value>
      <webElementGuid>ceb2848c-ec63-4ac8-b40e-06923e9fdede</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
