<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>frmDashboardMainMenu</name>
   <tag></tag>
   <elementGuidId>135bce0d-a626-40d4-ab1e-5010b560efb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html[1]/frameset[1]/frame[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>frame</value>
      <webElementGuid>c552983e-99a3-4938-9775-d28f11c39f5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>menu856624169702</value>
      <webElementGuid>2de09115-dea0-45f9-b563-74c1595cb70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>menu856624169702</value>
      <webElementGuid>0b7a5650-6626-467b-a58c-11a8c10c1196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>b7c16b9e-a8f8-46e3-8597-e46507e1bce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../jsps/genrequest.jsp?&amp;routineName=OS.NEW.USER&amp;routineArgs=MENU&amp;skin=bccl&amp;compId=AR0011043&amp;compScreen=COMPOSITE.SCREEN_B.0043_856624169703&amp;contextRoot=&amp;windowName=menu856624169702&amp;user=B.0043&amp;WS_replaceAll=&amp;WS_parentComposite=</value>
      <webElementGuid>938fce92-f26e-4722-b7fc-4b9586a2a949</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[1]</value>
      <webElementGuid>11609090-d4c1-4247-8be2-4500ce35929b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//frame[@id='menu856624169702']</value>
      <webElementGuid>e325d6d8-3e17-48a4-a5f4-de92594f57a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//frame[2]</value>
      <webElementGuid>42d127f7-b52d-472e-afce-8e0d8035d9d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>/html[1]/frameset[1]/frame[2]</value>
      <webElementGuid>cf40d393-fcf4-4364-a10a-0936b70a708a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
