<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkMovimientosAutomaticos</name>
   <tag></tag>
   <elementGuidId>296fd701-f1a1-40f9-80d2-3af53ce1568c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@onclick='ProcessMouseClick(event)'])[84]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.menuMargin:nth-child(22) > li:nth-child(1) > span:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a884de06-f6fb-4455-887a-0b9c0825eb8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ProcessMouseClick(event)</value>
      <webElementGuid>dcf3f88f-7b43-4ec8-9e9e-74da349cb7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>ProcessKeyPress(event)</value>
      <webElementGuid>abfccb14-d675-44bf-aa72-5b00484e7bd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Movimientos Automaticos</value>
      <webElementGuid>ab4731c4-cdcf-4d11-82f7-a519dc7a2aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/span[1]</value>
      <webElementGuid>8603fb87-6d91-415a-a259-37c59b0dd8df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/02-Dashboard/frmDashboardMenu</value>
      <webElementGuid>c161e2f8-1f9b-46a4-8e69-f3b6a42cf538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@onclick='ProcessMouseClick(event)'])[84]</value>
      <webElementGuid>b94d7ca6-7631-475a-8ce6-383e19d63330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul[22]/li/span</value>
      <webElementGuid>d0b540dc-d7f2-4401-bfef-ba52ce5d925a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta de Bonificaciones'])[1]/following::span[1]</value>
      <webElementGuid>f010f7f1-a043-4d97-b546-2144a91fb0db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alta/Modificacion de Bonificaciones'])[1]/following::span[1]</value>
      <webElementGuid>8638f9e7-60ac-49e9-9a0e-b759c8bf00ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultar Aceptados'])[1]/preceding::span[1]</value>
      <webElementGuid>7899786a-19e8-4134-9918-0e503815b302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultar Rechazados'])[1]/preceding::span[1]</value>
      <webElementGuid>bce9f38c-ffbe-4bbb-89c0-664c57a71f02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Movimientos Automaticos']/parent::*</value>
      <webElementGuid>c1f3c908-d48e-49a6-becf-225fab80aaa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[22]/li/span</value>
      <webElementGuid>a82aad62-4998-44b7-9f70-88ce7395e57c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Movimientos Automaticos' or . = 'Movimientos Automaticos')]</value>
      <webElementGuid>8c5788f6-f018-4837-9165-6111e7c91f48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
