<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkPersonas</name>
   <tag></tag>
   <elementGuidId>2a6e7c12-e8e9-44a2-9b67-5a4232ad9f1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.clsHasKids > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@onclick='ProcessMouseClick(event)']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Personas' or . = 'Personas') and @ref_element = 'Object Repository/02-Dashboard/frmDashboardMenu']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3682f84f-c62d-419e-acdd-508734683162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ProcessMouseClick(event)</value>
      <webElementGuid>46349138-dd57-4362-abd0-bcb32e908162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Personas</value>
      <webElementGuid>3b3f7b0d-7118-446f-9437-789695523f43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/span[1]</value>
      <webElementGuid>abb6acd3-fc90-4807-b3c8-ef026540629f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/02-Dashboard/frmDashboardMenu</value>
      <webElementGuid>dd5e4da9-3968-494e-b1fe-f9b1d7823926</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@onclick='ProcessMouseClick(event)']</value>
      <webElementGuid>e2087dfd-67d5-4bda-83ea-4499403a50f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul/li/span</value>
      <webElementGuid>c55fe379-9009-4911-bd85-2261d433a184</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alta'])[1]/preceding::span[1]</value>
      <webElementGuid>5ff2aae4-07e9-48f7-b689-a0343f00b440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alta Persona Fisica'])[1]/preceding::span[2]</value>
      <webElementGuid>f6492fb5-c115-400d-8bee-36f57388b1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Personas']/parent::*</value>
      <webElementGuid>f9efd6c4-2392-40f6-908f-5782e834c334</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>778f8522-fcea-42fa-9420-fb5d41481ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Personas' or . = 'Personas')]</value>
      <webElementGuid>be2c5fbd-1fa3-4434-a741-251fc8766af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
