<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnConcepto</name>
   <tag></tag>
   <elementGuidId>dd36a044-7f62-44e7-8042-cdecba753660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[11]/td[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.dropdown_button.dropdown_button_BCCLOPCAMBIO.dropdown_button_BCCLOPCAMBIO_FILIALCTACTA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>33fcb1e0-dc25-4f00-ae3b-98f8f6023ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>ee3e94a9-a985-4e02-8539-c02bfe62ae36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>42684328-b9a4-46e3-8f15-db77b9579077</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_BCCLOPCAMBIO dropdown_button_BCCLOPCAMBIO_FILIALCTACTA</value>
      <webElementGuid>da974995-9637-41b8-9157-c88386170846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>enquiryDropdown(event)</value>
      <webElementGuid>e2a49f79-82c2-43f4-a979-ccd6ff69b320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lista de Registros</value>
      <webElementGuid>85234ff2-c321-4444-bf34-d671dd4b2aa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/dropdown.gif</value>
      <webElementGuid>8349ec34-5ff0-4bb7-8b80-d53733e60908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>62cad72e-addb-4a95-9afc-d1aec2c8b9df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enquiryfield</name>
      <type>Main</type>
      <value>BCCL.E.CONCEPTOS.OPCAM</value>
      <webElementGuid>9b5eabe7-711d-40e6-b7fb-cbea807adb40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropfield</name>
      <type>Main</type>
      <value>fieldName:CONCEPTO</value>
      <webElementGuid>ee7e3e06-6fe3-4771-80f5-b7731fc66f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriafield</name>
      <type>Main</type>
      <value>USO.FILIAL</value>
      <webElementGuid>e4badf0b-3617-4746-8056-1d923839f5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriaopfield</name>
      <type>Main</type>
      <value>EQ</value>
      <webElementGuid>be0963ce-1bbd-4d4d-a5d0-c10961d0672d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatafield</name>
      <type>Main</type>
      <value>fieldName:</value>
      <webElementGuid>1bf2d0d3-785d-4b44-b584-8c361895cc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatastring</name>
      <type>Main</type>
      <value>'SI'</value>
      <webElementGuid>c15ae255-ae4c-4aa4-a3df-be0dacbae340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enqfieldname</name>
      <type>Main</type>
      <value>fieldName:CONCEPTO</value>
      <webElementGuid>222dc20d-c8d8-4ea0-8b9d-dcd74ac13969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>0527ed4b-0cb3-4667-8eb9-bf3a60db7f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noinputdropfield</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>e520ec11-f9ec-4dc3-9dd5-078a7b8b1bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[11]/td[3]/a[1]/img[@class=&quot;dropdown_button dropdown_button_BCCLOPCAMBIO dropdown_button_BCCLOPCAMBIO_FILIALCTACTA&quot;]</value>
      <webElementGuid>27deb7b3-7c67-43c4-9ec5-7ffa8b5fb1d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[11]/td[3]/a/img</value>
      <webElementGuid>f568778d-44df-41c9-a351-8095851daea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Lista de Registros']</value>
      <webElementGuid>5cf24264-4129-42d4-8f29-57711514f3e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/img</value>
      <webElementGuid>f28b2e5c-1241-427a-846e-070055e51688</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Lista de Registros' and @src = '../plaf/images/bccl/deal/dropdown.gif']</value>
      <webElementGuid>8a63545f-4e06-4a4f-b05b-17104ecf9cef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
