<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbSocioVende</name>
   <tag></tag>
   <elementGuidId>8cb76754-7aba-475f-96f8-c3a5c23dd62e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='radio:tab1:TIPO.OPER'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef153185-f15f-49ca-bcd1-ebda42248e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radioCheckStyle radioCheckStyle_BCCLOPCAMBIO radioCheckStyle_BCCLOPCAMBIO_CCOFICIOS</value>
      <webElementGuid>84bb4f29-8613-47fc-894f-af425feff70e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5df2e343-3ff7-4b39-a995-d4a970c8b981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>394c28ea-7d38-4479-8db4-0bac928a355e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>
          javascript:doFieldChangeEvent(event)
        </value>
      <webElementGuid>566c6e40-a49b-4061-8937-f22fb8ca5342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>javascript:enableFocus(this)</value>
      <webElementGuid>a314ab3c-80b0-405c-ab3e-a4a20c9917f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>javascript:disableFocus(this)</value>
      <webElementGuid>b385b8f2-87af-477c-912f-fb814a200ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>selected</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>179e999e-c071-4c8f-b29e-8d57a452ea75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9ec44b89-6a78-4348-965f-5eece861c852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radio:tab1:TIPO.OPER</value>
      <webElementGuid>fa2518fb-fb84-4433-a59f-af86488da532</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radio:tab1:TIPO.OPER</value>
      <webElementGuid>a727298d-af36-47d4-9201-e4f1b25d5749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>V</value>
      <webElementGuid>b971162f-cce7-4c44-8146-6ef71786656d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hot</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>96089c14-75f7-46ed-9530-786db16633f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b5e58846-5900-46c6-8b41-ad8390c3d4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'','issueToken');</value>
      <webElementGuid>d0bb2c19-6806-46ab-a886-39c50ff43efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('','','','issueToken')</value>
      <webElementGuid>a1e06d8c-b5a1-4332-9694-3bb30be22a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>6e36b08f-de90-497d-9f9e-ebbb446fe37e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[8]/td[3]/table[1]/tbody[1]/tr[1]/td[2]/input[@id=&quot;radio:tab1:TIPO.OPER&quot;]</value>
      <webElementGuid>99e74642-b272-4cb5-8d1f-51545a1aa303</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='radio:tab1:TIPO.OPER'])[2]</value>
      <webElementGuid>10bb3c8a-5e4a-4d7e-b343-bc78fc13bd7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[8]/td[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>058f7195-b5e1-432e-a979-75f0668ccdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[3]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>8fe88990-823f-4922-9ae2-f9de4872e63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@selected = 'true' and @type = 'radio' and @id = 'radio:tab1:TIPO.OPER' and @name = 'radio:tab1:TIPO.OPER' and @checked = 'true']</value>
      <webElementGuid>682ba809-d8d0-41a2-9a26-6ef4449d53ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
