<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtFecha</name>
   <tag></tag>
   <elementGuidId>ff65496f-884e-4d0b-a76c-c1edd7d0c15d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='value:1:1:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eee3b39-c8ee-4ee7-aa18-290b8acc7909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1bd12b5b-52f9-43ff-8ea4-b3572a6a1ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>fd77eae8-038a-4990-9fa6-0314744e588d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>cc63101a-f4bf-40f5-9d7e-02a810c6b886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>73262bf4-ed78-4944-9c3c-74e3d1f63e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frequencydropfieldname</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>79bfd35e-abd9-4714-83df-b9304182bdf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqseldata enqseldata_BCCLETTREMESASRECFIRME</value>
      <webElementGuid>69489a4e-e845-4da8-b97e-e027b90210f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>monthdesc</name>
      <type>Main</type>
      <value>ENE FEB MAR ABR MAY JUN JUL AGO SEP OCT NOV DIC</value>
      <webElementGuid>98fc88c0-68e3-415e-8c4e-879d3cd143a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;value:1:1:1&quot;)</value>
      <webElementGuid>96fc6fb9-1c74-434e-99ae-ce43ecd0a334</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='value:1:1:1']</value>
      <webElementGuid>255b6ba6-8c13-4917-90a3-82ae32cd7e90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay']/tbody/tr/td[3]/input</value>
      <webElementGuid>6a2d9b79-0542-42af-b7d9-61a9040a9b2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>a05f88dc-fdd9-4d61-a2c8-c2b6f143427e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'value:1:1:1' and @id = 'value:1:1:1']</value>
      <webElementGuid>c9bec0be-f010-4c75-ae23-9302e5afb41c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
