<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxOperatoriaOrigen</name>
   <tag></tag>
   <elementGuidId>e3da97e9-c680-4b60-af56-dbedfc396d2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:L.ORIG.IMP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>85bc5296-3a3c-4eb5-a131-29a40bf13741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_FUNDSTRANSFER dealbox_FUNDSTRANSFER_BCCLIMPTOSCOBCTA</value>
      <webElementGuid>8d9527e0-5cb1-4ba0-8eb1-24da4cce883b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:L.ORIG.IMP</value>
      <webElementGuid>4a9cc3e6-3f19-45bf-a6f1-4e3cd723e621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:L.ORIG.IMP</value>
      <webElementGuid>c914aeca-c054-4691-a39d-b1e41f54a86d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ed706fe8-1298-4f2f-afd5-e30dec399654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>580293bb-4030-48ad-b587-f51a2819adef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_L.ORIG.IMP</value>
      <webElementGuid>219ab563-b9e6-4ae5-bf73-63be81213638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'L.ORIG.IMP','issueToken');</value>
      <webElementGuid>53b769b0-6880-47a4-865c-d6c236a56a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>765029f7-f212-4583-83e7-b671bedb9ad1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('L.ORIG.IMP','','','issueToken')</value>
      <webElementGuid>d9420dd6-d01d-4fa8-bcf6-3958136cfe62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  385-D-Ctas Ent Financieras386-C-Ctas Ent Financieras453-D-Trans Mismo titular454-D-Plazo Fijo456-D-Renov Pmos457-C-Trans X Fuera de cta458-C-COMEX459-C-FCI460-C-OTRAS Op Exentas473-C-Caja de Ahorro474-C-Trans Mismo titular475-C-Plazo Fijo476-D-Remuneraciones(CC)477-C-Renov Pmos478-D-Trans X Fuera de cta479-D-COMEX480-D-FCI481-D-OTRAS Op Exentas482-D-Entes Publicos483-D-Part Politicos485-C-Entes Publicos486-C-Part Politicos488-D-Ctas Benef RG 3900489-C-Ctas Benef RG 3900501-C-Trans Inmuebles502-D-Trans InmueblesCAUCION/PRENDASOLICITUDES DE CREDITOFIANZASMUTUOSPAGARE</value>
      <webElementGuid>e296ab1e-4581-4dbb-a13e-2a5c883d2451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:L.ORIG.IMP&quot;)</value>
      <webElementGuid>4159127d-a14a-40d8-9e72-9b92950426bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:L.ORIG.IMP']</value>
      <webElementGuid>a043815b-878a-445f-b612-b576fba70d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[24]/td[3]/select</value>
      <webElementGuid>7132d1fa-b2a9-40f4-b7d4-8de89eca6205</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Operatoria Origen'])[1]/following::select[1]</value>
      <webElementGuid>bcc0f587-4cc8-4400-b744-301895cfe16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cod. Operativo Cr'])[1]/following::select[1]</value>
      <webElementGuid>fe98b48d-9a96-44a6-839a-f614643a028b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alertas.1'])[1]/preceding::select[1]</value>
      <webElementGuid>9335b691-82c2-45e7-88d3-a245021ce79a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado del Registro'])[1]/preceding::select[1]</value>
      <webElementGuid>495b1cae-0907-4098-8f16-6af0541113eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[24]/td[3]/select</value>
      <webElementGuid>3cb638a6-c733-4df5-ac86-057d5b1f02f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:L.ORIG.IMP' and @id = 'fieldName:L.ORIG.IMP' and (text() = '  385-D-Ctas Ent Financieras386-C-Ctas Ent Financieras453-D-Trans Mismo titular454-D-Plazo Fijo456-D-Renov Pmos457-C-Trans X Fuera de cta458-C-COMEX459-C-FCI460-C-OTRAS Op Exentas473-C-Caja de Ahorro474-C-Trans Mismo titular475-C-Plazo Fijo476-D-Remuneraciones(CC)477-C-Renov Pmos478-D-Trans X Fuera de cta479-D-COMEX480-D-FCI481-D-OTRAS Op Exentas482-D-Entes Publicos483-D-Part Politicos485-C-Entes Publicos486-C-Part Politicos488-D-Ctas Benef RG 3900489-C-Ctas Benef RG 3900501-C-Trans Inmuebles502-D-Trans InmueblesCAUCION/PRENDASOLICITUDES DE CREDITOFIANZASMUTUOSPAGARE' or . = '  385-D-Ctas Ent Financieras386-C-Ctas Ent Financieras453-D-Trans Mismo titular454-D-Plazo Fijo456-D-Renov Pmos457-C-Trans X Fuera de cta458-C-COMEX459-C-FCI460-C-OTRAS Op Exentas473-C-Caja de Ahorro474-C-Trans Mismo titular475-C-Plazo Fijo476-D-Remuneraciones(CC)477-C-Renov Pmos478-D-Trans X Fuera de cta479-D-COMEX480-D-FCI481-D-OTRAS Op Exentas482-D-Entes Publicos483-D-Part Politicos485-C-Entes Publicos486-C-Part Politicos488-D-Ctas Benef RG 3900489-C-Ctas Benef RG 3900501-C-Trans Inmuebles502-D-Trans InmueblesCAUCION/PRENDASOLICITUDES DE CREDITOFIANZASMUTUOSPAGARE')]</value>
      <webElementGuid>3b561de7-452e-4540-9c0c-8e2d617a74e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
