<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgAceptarRegistroDestruccion</name>
   <tag></tag>
   <elementGuidId>cd248dd2-d3b2-4759-9ed5-3de07ef583b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='enq_toolHeader']/tbody/tr/td[3]/table/tbody/tr/td[2]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>afdae993-d7c9-46a6-ad63-b135c12543fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/menu/go.gif</value>
      <webElementGuid>658fe335-3a10-4fbb-8e6a-e2324e600b88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enq_toolHeader&quot;)/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[1]/td[2]/a[1]/img[1]</value>
      <webElementGuid>d1c0f301-8d3d-4e66-b03b-36c640ed2506</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='enq_toolHeader']/tbody/tr/td[3]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>b3528d49-894d-4edd-9633-79b9d2a04332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>3ddd4721-7a61-4f66-a6cd-7bc52a6795c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/menu/go.gif']</value>
      <webElementGuid>98f9a5a9-3048-4e09-8d57-b1bfc9626e97</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
