<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTituloPosteoPagoenEfectivo</name>
   <tag></tag>
   <elementGuidId>abac456a-57ac-4016-95ab-50bb0dca9eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;FUNDS.TRANSFER,POSTEO.RETIRO&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dealtitle']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2f6f0c17-5cb0-4c55-9e6a-051d9bba8276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>351d9701-8337-479d-ba28-8985e383a012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>42c7458c-1e85-4465-9a54-5f65a0dbac2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>FUNDS.TRANSFER,POSTEO.RETIRO</value>
      <webElementGuid>a6e57a5c-adac-4877-879d-becc5581b934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:help(&quot;FUNDS.TRANSFER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);</value>
      <webElementGuid>e52f8e04-e6ed-4925-af18-4ceedd49d11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Posteo Pago en Efectivo</value>
      <webElementGuid>291208ea-a897-4726-8da1-a9134df7e350</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dealtitle&quot;)/a[1]</value>
      <webElementGuid>fb42ad35-5da2-4453-aac3-14542d66f09f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dealtitle']/a</value>
      <webElementGuid>175b61e7-9076-4f21-ac75-2a84031c4244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Posteo Pago en Efectivo')]</value>
      <webElementGuid>b3ee89cd-d515-4c55-b109-0bd29e5a4801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FT/22210/074592204'])[1]/preceding::a[1]</value>
      <webElementGuid>ab9c3873-dad9-4a24-87e9-2eb45a493baa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.073 Jujuy)'])[1]/preceding::a[1]</value>
      <webElementGuid>8e9c740a-1fee-4c7b-b11b-06b56792411f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Posteo Pago en Efectivo']/parent::*</value>
      <webElementGuid>2ddea1e2-fc7e-44e1-b9c1-637618ab74ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:help(&quot;FUNDS.TRANSFER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);')]</value>
      <webElementGuid>7eb716c6-50dd-4ebe-85af-5e12cc57219a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>3ca71f87-24b2-4c52-952e-7ecc027a57af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'FUNDS.TRANSFER,POSTEO.RETIRO' and @href = 'javascript:help(&quot;FUNDS.TRANSFER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);' and (text() = 'Posteo Pago en Efectivo' or . = 'Posteo Pago en Efectivo')]</value>
      <webElementGuid>15f8c7ac-2c63-43e9-92e6-6e0e7174f312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
