<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>rbDolarEstadounidense</name>
   <tag></tag>
   <elementGuidId>6ed8d490-fdab-416c-98cb-568dace7329d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dropDownRow14']/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d6ef0835-0a6f-43e1-859a-8ed1e2df988e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coloumntddata coloumntddata_CURRENCYLIST</value>
      <webElementGuid>d438bb4c-2a89-421a-942e-3dddd1842966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dolar Estadounidense</value>
      <webElementGuid>5499236e-cda1-44a2-9968-c5739f83e06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownRow14&quot;)/td[@class=&quot;coloumntddata coloumntddata_CURRENCYLIST&quot;]</value>
      <webElementGuid>d9f333e7-2516-4ba1-9599-7fe8b8d7a30b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dropDownRow14']/td[2]</value>
      <webElementGuid>fbed483a-0390-4d1c-88ca-2beffbe61126</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='USD'])[1]/following::td[1]</value>
      <webElementGuid>a0d90c7d-9d88-4fe7-85c6-64801e7515f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dolar Convenio'])[1]/following::td[2]</value>
      <webElementGuid>86f71714-73ee-4cfd-986d-46c0a4b92685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UYU'])[1]/preceding::td[1]</value>
      <webElementGuid>e4ab1471-66a5-405f-9c7e-7e850fbc7576</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peso Uruguayo'])[1]/preceding::td[2]</value>
      <webElementGuid>2520477a-de33-4b51-8c10-97f0194b92c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dolar Estadounidense']/parent::*</value>
      <webElementGuid>28c3d620-7b32-4c16-861a-92b1a60f4862</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[2]</value>
      <webElementGuid>ca126407-8c55-46d4-aa8e-46fa6e8fa6c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Dolar Estadounidense' or . = 'Dolar Estadounidense')]</value>
      <webElementGuid>69e1a29a-415d-40e8-b14a-12156dee4b70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
