<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbAutorizarTransaccion</name>
   <tag></tag>
   <elementGuidId>20539a2f-903f-4395-be18-4b1813b5a445</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drillbox:1_1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c7009f54-86cd-4c3c-86e0-257164999733</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drillbox:1_1</value>
      <webElementGuid>7b967d07-0ecb-4181-8042-0e8a616eeba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drillbox drillbox_BCCLEAUTHORIZATION</value>
      <webElementGuid>eb90b0a7-0eb2-4d58-8978-67e71ffa17c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONSULTAR TRANSACCIONAUTORIZAR TRANSACCIONELIMINAR TRANSACCION</value>
      <webElementGuid>466984e0-b3ce-40e2-bc45-3fac68255218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drillbox:1_1&quot;)</value>
      <webElementGuid>711026e2-a4eb-44bd-a77a-ff47a43ec5c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drillbox:1_1']</value>
      <webElementGuid>33133ac7-af24-4b1e-aaf7-10d2a2663e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[9]/table/tbody/tr/td/select</value>
      <webElementGuid>ad9aa52a-d4fc-4e85-ab5f-ee344af71387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pendiente de Autorizacion'])[1]/following::select[1]</value>
      <webElementGuid>2c59f3fd-bc14-459e-92c0-8a2648c6666c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NIV5'])[1]/following::select[1]</value>
      <webElementGuid>61b2c42b-dae5-46fa-a06e-386f5b15b1c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[2]/preceding::select[1]</value>
      <webElementGuid>0c6cc21d-c55a-4818-9d7e-414ef5101d98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Solicitud de Chequera'])[2]/preceding::select[1]</value>
      <webElementGuid>d441291c-ad54-4f8f-b809-ddfd38e313bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d42fefd0-b27a-4880-8cbe-529ea460dfbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drillbox:1_1' and (text() = 'CONSULTAR TRANSACCIONAUTORIZAR TRANSACCIONELIMINAR TRANSACCION' or . = 'CONSULTAR TRANSACCIONAUTORIZAR TRANSACCIONELIMINAR TRANSACCION')]</value>
      <webElementGuid>1acfea55-ea83-433c-a50c-1035ada8a4a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
