<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnkEntregaTarjetasSocio</name>
   <tag></tag>
   <elementGuidId>470499ea-e97c-405d-bae3-c00152b5b381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//span[@onclick='ProcessMouseClick(event)'])[57]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[1][count(. | //*[(text() = 'Entrega de TARJETAS al SOCIO' or . = 'Entrega de TARJETAS al SOCIO') and @ref_element = 'Object Repository/02-Dashboard/AdminPiezasConTarjetas/frmAdminPiezasConTarjetas']) = count(//*[(text() = 'Entrega de TARJETAS al SOCIO' or . = 'Entrega de TARJETAS al SOCIO') and @ref_element = 'Object Repository/02-Dashboard/AdminPiezasConTarjetas/frmAdminPiezasConTarjetas'])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ff6e0162-155c-4b8e-8829-5ae82e8b6df9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ProcessMouseClick(event)</value>
      <webElementGuid>6cebfbb6-455f-47f9-9340-5c29be427a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>ProcessKeyPress(event)</value>
      <webElementGuid>0ddd620a-f876-4a36-9145-9e9a064f28f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Entrega de TARJETAS al SOCIO</value>
      <webElementGuid>ce9db75d-bb3f-4af2-b0f5-6f2d1ef91e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[1]</value>
      <webElementGuid>e1dd9a0a-20fd-4ed4-894b-4979f0ee3c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/02-Dashboard/1-AdminPiezasConTarjetas/frmAdminPiezasConTarjetas</value>
      <webElementGuid>59d9ca35-90c7-496f-92ff-52aee1c393bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@onclick='ProcessMouseClick(event)'])[57]</value>
      <webElementGuid>6d27b2e4-dfdf-4610-99ba-0ada06e3e5ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul[14]/li/ul/li[3]/span</value>
      <webElementGuid>8671d528-df41-4d2a-a503-84ed056ffc97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envio o Entrega a AC de Card-Carrier'])[1]/following::span[1]</value>
      <webElementGuid>d83e7b4c-d818-411a-a0fa-704e51943978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Envio a otra filal o al Activador Comercial'])[1]/following::span[1]</value>
      <webElementGuid>685441a7-e286-43f1-a1df-19f3287c47ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entrega al Socio por Nro. de PIEZA'])[1]/preceding::span[1]</value>
      <webElementGuid>20eecc15-be8d-4999-8117-cd93796669a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consultas al Maestro de Card-Carrier'])[1]/preceding::span[1]</value>
      <webElementGuid>9d57a209-e2e3-43e3-99f2-e8cc61ca59b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Entrega de TARJETAS al SOCIO']/parent::*</value>
      <webElementGuid>88841795-d647-4d30-b365-3ffb5fafa8ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ul[14]/li/ul/li[3]/span</value>
      <webElementGuid>6eab2b1a-12e2-4513-a331-cc949e235896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Entrega de TARJETAS al SOCIO' or . = 'Entrega de TARJETAS al SOCIO')]</value>
      <webElementGuid>df9d7310-68f6-407e-adf3-c9d65cde1c0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
