<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblMONEDA</name>
   <tag></tag>
   <elementGuidId>4e8c5682-1070-4397-8c65-dd0877b61aef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>4afd945d-44b4-4fea-87df-e78c40d76ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>0e748760-820c-475f-8506-f549bcba832e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>9dbea182-1861-4688-a173-a630f8ec8582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText5</value>
      <webElementGuid>723f7c73-accc-4fe5-8993-dad29e479570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MONEDA</value>
      <webElementGuid>e2a85bb5-38e5-45f4-86b9-688fee507fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText5&quot;)</value>
      <webElementGuid>4927d824-0cab-4e0a-b773-552444f9d309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText5']</value>
      <webElementGuid>f0a06ab1-24f2-42ae-aefd-9f0929407678</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader5']/table/tbody/tr/th</value>
      <webElementGuid>98158ae6-2435-4fd0-8fec-c64e82e9231d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUC DESTINO'])[1]/following::th[3]</value>
      <webElementGuid>b7590891-391f-48d9-a0bb-8654d154b514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUC ORIGEN'])[1]/following::th[6]</value>
      <webElementGuid>3d1d617b-4732-405a-aaef-86c634a18923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTE'])[1]/preceding::th[2]</value>
      <webElementGuid>643cfab6-16e2-436b-bb70-a37d15994272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESORO DE RECEPCION'])[1]/preceding::th[5]</value>
      <webElementGuid>91d30008-75e6-4f58-8a1e-8c75fdd8b2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MONEDA']/parent::*</value>
      <webElementGuid>48d9176c-8f4b-4cb0-96d3-fbc9cb374820</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/table/tbody/tr/th</value>
      <webElementGuid>c40ddae1-2fd0-48f4-8fe3-09bb46aadbbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText5' and (text() = 'MONEDA' or . = 'MONEDA')]</value>
      <webElementGuid>530f917a-b180-4e1e-b23b-1021b94e906e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
