<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxUltima Modificacion</name>
   <tag></tag>
   <elementGuidId>1e3ffeda-5d08-4b63-b4d8-9e816a2878e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drillbox:1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>89c278c3-f75c-4e3d-aa9c-ce40ec0068e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drillbox:1_1</value>
      <webElementGuid>a1a99b17-2be3-4880-92a0-e5f495b9f5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drillbox drillbox_BCCLEACFIRMHISTCAMBIOS</value>
      <webElementGuid>5a71af41-06b8-4d2d-a7b8-38d5a81c277b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ultima ModificacionVer HistoricoVersion Actual</value>
      <webElementGuid>d612e999-d2c6-4638-bafa-8b45b640a79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drillbox:1_1&quot;)</value>
      <webElementGuid>de3d4dac-e9ff-454c-806c-af4f4dbc252e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drillbox:1_1']</value>
      <webElementGuid>0dabdfae-0871-4cd6-bb37-65f41712deba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[6]/table/tbody/tr/td/select</value>
      <webElementGuid>9e40e1ce-d3d2-4f2a-bb17-3a6528e85ea9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[1]/following::select[1]</value>
      <webElementGuid>06da7dec-7861-4848-9729-4772cc648b55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cuentas Remuneradas Institucionales'])[1]/following::select[1]</value>
      <webElementGuid>507033d4-62ba-4a24-80f1-9b4db74e0a7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favoritos'])[1]/preceding::select[1]</value>
      <webElementGuid>058ae886-fe30-4fdf-bf42-ccef63f984a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta de Modificaciones a Ctas'])[2]/preceding::select[1]</value>
      <webElementGuid>9f997daa-b862-468d-84d8-62fcd1d325df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9752d338-2f1a-4f56-b3f4-1803de963d87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drillbox:1_1' and (text() = 'Ultima ModificacionVer HistoricoVersion Actual' or . = 'Ultima ModificacionVer HistoricoVersion Actual')]</value>
      <webElementGuid>8954682a-1239-4f48-9c12-57d5854ab50c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
