<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDropdownSectorBCRA</name>
   <tag></tag>
   <elementGuidId>63823579-c820-4fd6-81d7-229fea2b4fb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[15]/td[3]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3bcaafaf-7c83-4d2c-a0be-b59612abc65f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>20098484-9f0f-4fbe-9730-4ccac486588d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>44cfcb0a-392c-4d6e-b0f1-35c007f9b670</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_ACCOUNT dropdown_button_ACCOUNT_BCCLMODSUBACCCCPF</value>
      <webElementGuid>c57b7dd2-e650-4ffd-9c71-9a62045e72cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>enquiryDropdown(event)</value>
      <webElementGuid>48c33daa-05bc-4600-85ce-21da7ca501f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lista de Registros</value>
      <webElementGuid>4ef58956-cf41-484f-ae37-c71c06b1223d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/dropdown.gif</value>
      <webElementGuid>2e4a05de-dee2-4dfb-bbda-3310779cf58b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ce5a6e38-f141-49d6-a805-7f8191a011b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enquiryfield</name>
      <type>Main</type>
      <value>BCCL.E.AC.SEC.BCRA</value>
      <webElementGuid>97f282de-4279-4dae-b103-419a0e15b053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropfield</name>
      <type>Main</type>
      <value>fieldName:L.AC.TX.BCRA</value>
      <webElementGuid>48138c4e-ee07-4fc2-9be3-2a9c07384209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriafield</name>
      <type>Main</type>
      <value>@ID</value>
      <webElementGuid>62fca192-9a01-45eb-8a80-db34d2ed1b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriaopfield</name>
      <type>Main</type>
      <value>EQ</value>
      <webElementGuid>9afec86b-e62e-483f-9002-019f67d62d78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatafield</name>
      <type>Main</type>
      <value>fieldName:L.AC.PROD.CONFG</value>
      <webElementGuid>74b082f5-fa9b-4044-b688-1fa6f5d19ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enqfieldname</name>
      <type>Main</type>
      <value>fieldName:L.AC.TX.BCRA</value>
      <webElementGuid>b28653cc-b4ab-43df-94a7-5316f4f5125b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>cc57c056-18b0-4a38-a3db-bb57fd7a5940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[15]/td[3]/a[1]/img[@class=&quot;dropdown_button dropdown_button_ACCOUNT dropdown_button_ACCOUNT_BCCLMODSUBACCCCPF&quot;]</value>
      <webElementGuid>875a5f51-3246-4e07-8b5a-6579b6b8c164</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[15]/td[3]/a/img</value>
      <webElementGuid>288bf9a4-6eac-41cb-a46e-94fa06536017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Lista de Registros'])[4]</value>
      <webElementGuid>a1c6cc53-6b1e-4f2e-8809-f5e7c1a4a2c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[3]/a/img</value>
      <webElementGuid>145ac485-562b-4ae4-bc0d-c534687c7d4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Lista de Registros' and @src = '../plaf/images/bccl/deal/dropdown.gif']</value>
      <webElementGuid>0ae87f96-d667-422b-822d-91b3e1f4987f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
