<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblDescripcionAUTORIZADA</name>
   <tag></tag>
   <elementGuidId>2436db59-5ef9-4a5c-abc7-afda5482a61f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.bccl-verde.bccl-verde_BCCLEESTADOPANTALLAS</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r1']/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2f933fdf-c869-4d19-9279-acc3d762a9fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>bccl-verde bccl-verde_BCCLEESTADOPANTALLAS</value>
      <webElementGuid>9ec65b9d-7134-4c44-8e42-3262d758c5d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>right</value>
      <webElementGuid>49955a1a-2af9-4110-8b7f-d0a0685137a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AUTORIZADA</value>
      <webElementGuid>91f729e0-3ed4-422e-8cf5-4c0942aaf5ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[@class=&quot;bccl-verde bccl-verde_BCCLEESTADOPANTALLAS&quot;]</value>
      <webElementGuid>1f1560af-8d9b-4287-b92d-3c03e424f095</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[2]</value>
      <webElementGuid>36962338-78e9-4f50-b985-e56f88f713c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingreso de Transaccion: BRLOO001'])[1]/following::td[1]</value>
      <webElementGuid>430d1eaa-adf5-4f12-adff-ae3085f05bc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESTADO'])[1]/following::td[2]</value>
      <webElementGuid>5508dd1a-0928-4a48-b154-8f18a7a210bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::td[2]</value>
      <webElementGuid>6f033992-4088-47e8-9623-bc8376303ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::td[2]</value>
      <webElementGuid>4257646a-a02c-42a7-82a3-8d0b033bf40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AUTORIZADA']/parent::*</value>
      <webElementGuid>33e99529-530a-4ce3-8b9d-7752a2af0859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[2]</value>
      <webElementGuid>544ee53c-b08f-492b-843e-c62ee7a688c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'AUTORIZADA' or . = 'AUTORIZADA')]</value>
      <webElementGuid>0c0eeac6-2ce4-4f06-a7d4-85aa74fabc04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
