<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtComentarios</name>
   <tag></tag>
   <elementGuidId>8a498ccd-0d04-4e35-9e03-ab226d05adc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:NARRATIVE.1:1:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f5f8f3c-d5cc-4fed-94c4-4ef24664b6d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb7ebc86-1c18-410a-88cf-802f1f30e87e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>f73199dc-7449-40f8-9c83-494680e50008</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:NARRATIVE.1:1:1</value>
      <webElementGuid>8b09e3d1-1452-4dd0-b83d-287a9381fb0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:NARRATIVE.1:1:1</value>
      <webElementGuid>73ec18ee-5c6c-43ec-84ae-3b60b353016e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>ecb56abd-5589-4762-9d07-a3303c720a3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_TELLER dealbox_TELLER_RECEPCIONREMEOBANCO</value>
      <webElementGuid>e011aa1d-c9fd-4c70-97dc-9ffd5a655d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>34</value>
      <webElementGuid>f93ba518-5aa6-482f-b5ad-1f80c12610e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e6539e8a-4f65-40ca-9ab5-66e05b5fa3ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_NARRATIVE.1:1:1</value>
      <webElementGuid>adccd1ba-d132-4462-8808-b094e3ba35a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'NARRATIVE.1','issueToken');</value>
      <webElementGuid>bd35a7be-afb9-401b-bedf-7cb70e505203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>748403cd-daad-47a7-ad01-2cabee579da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('NARRATIVE.1','','','issueToken')</value>
      <webElementGuid>1d372a8b-44c2-4cf9-954d-4b4d8cad0ef6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:NARRATIVE.1:1:1&quot;)</value>
      <webElementGuid>3112eecc-e80a-4a02-9d6d-05038ae5701a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:NARRATIVE.1:1:1']</value>
      <webElementGuid>170c76c9-5a7e-4bdd-a303-dc5353dbf5b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[5]/td[3]/input</value>
      <webElementGuid>4559037d-e2f9-4eac-abb7-d45184d56d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[3]/input</value>
      <webElementGuid>d86f8802-4e7d-48c3-9ec5-0f98626e1bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:NARRATIVE.1:1:1' and @name = 'fieldName:NARRATIVE.1:1:1' and @type = 'text']</value>
      <webElementGuid>1c6048f8-ab31-405a-bf5f-04d6e6ff2628</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
