<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnSelectDrilldown</name>
   <tag></tag>
   <elementGuidId>511bb954-ea1c-408b-a70d-e076cefd097b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Select Drilldown&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r1']/td[11]/table/tbody/tr/td[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3f0eb38d-4adc-4d27-b539-5d98776b4a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Select Drilldown</value>
      <webElementGuid>a7cdfe77-6ae2-4b31-9e7d-a21c0564d7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/menu/go.gif</value>
      <webElementGuid>1343d97d-4a24-455a-877c-18c2fb219a83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r1&quot;)/td[@class=&quot;enqdrilldowncell enqdrilldowncell_BCCLECANDTCIERRE&quot;]/table[1]/tbody[1]/tr[@class=&quot;enqdrilldowncell enqdrilldowncell_BCCLECANDTCIERRE&quot;]/td[2]/a[@class=&quot;iconLink&quot;]/img[1]</value>
      <webElementGuid>6f51d5c4-803b-45cb-8844-890136161900</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[11]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>accd404a-e1fe-4308-becc-4547132ff537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Select Drilldown']</value>
      <webElementGuid>ee8e7144-0da6-4bc3-8dd2-23134b4ce12b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[11]/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>a913481d-32c4-4c46-9ed8-0f999f90be70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Select Drilldown' and @src = '../plaf/images/bccl/menu/go.gif']</value>
      <webElementGuid>84f7e4e0-028c-497a-8a16-f9ee1b3cc37f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
