<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxAsociado</name>
   <tag></tag>
   <elementGuidId>d7290b31-0715-49d3-8b94-5279d0c4b002</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:DECL.CONOCER.CLIE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f0cd9c00-c3f7-41ce-abe5-7727f14cf0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_BCCLMEPFTTRANSFER dealbox_BCCLMEPFTTRANSFER_BCCLALTAMEPDT0</value>
      <webElementGuid>51c04c56-5418-42e8-88d2-1c1368f49fe4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:DECL.CONOCER.CLIE</value>
      <webElementGuid>4aba40c8-3f4a-4173-b0f8-13967a3c14be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:DECL.CONOCER.CLIE</value>
      <webElementGuid>a6583005-7993-42ae-97a4-76ab2c92d92c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>31adab5e-86e9-4b84-b26c-4f9459edde72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>03a409bd-d872-4031-9391-3bd8fcf76819</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_DECL.CONOCER.CLIE</value>
      <webElementGuid>1407bde4-6790-46cf-972f-a2969bb2ecb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'DECL.CONOCER.CLIE','issueToken');</value>
      <webElementGuid>9af67af4-b0d3-4306-8290-3941a76ba7cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>7d5be4f4-ca0b-498e-931d-f0ba83da7d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('DECL.CONOCER.CLIE','','','issueToken')</value>
      <webElementGuid>2fae2ac0-5d99-40d4-9213-90167e368de8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  NOSI</value>
      <webElementGuid>ed20218c-b3e2-4fb2-976b-34311b9d224e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:DECL.CONOCER.CLIE&quot;)</value>
      <webElementGuid>12c2aad2-1564-49d8-8bf2-6cd6e88c4642</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:DECL.CONOCER.CLIE']</value>
      <webElementGuid>965cb520-570b-4e6c-83b0-bae172277d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[9]/td[3]/select</value>
      <webElementGuid>eb59941b-cad9-4168-b589-61c674315b83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Conozca a su Asociado'])[1]/following::select[1]</value>
      <webElementGuid>a91416c0-3a85-478f-87c0-9e3288e84137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Porcentaje Bonificacion'])[1]/following::select[1]</value>
      <webElementGuid>e4c8da89-860d-48d9-b731-9b2eacef4aaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU o Alias'])[1]/preceding::select[1]</value>
      <webElementGuid>bc2baac1-b37b-41d5-b05a-87ebb1b8faf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CBU Beneficiario'])[1]/preceding::select[1]</value>
      <webElementGuid>c6ea961b-c1eb-48d3-807b-4b418b617163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>b19be270-1758-4170-afc5-37dd61ce68e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:DECL.CONOCER.CLIE' and @id = 'fieldName:DECL.CONOCER.CLIE' and (text() = '  NOSI' or . = '  NOSI')]</value>
      <webElementGuid>98fd1377-6afe-486e-871a-fe6fe7e740aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
