<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblMonto</name>
   <tag></tag>
   <elementGuidId>d8be5b93-8b40-44eb-bd4c-33b3c3cf94ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText4']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>68d4d9b6-06a4-4c26-8e84-ed9f339d2c60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>970f6de8-4ef9-41ec-8947-e406e8e61ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>1e6b2ba0-5f68-4e2d-87d0-8b967e095218</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText4</value>
      <webElementGuid>5ae5d540-deeb-4e6d-ae4e-4ddcdd51b42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Monto</value>
      <webElementGuid>42f02527-5f55-438c-884e-34e7efcf3e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText4&quot;)</value>
      <webElementGuid>1e12b7b1-2b63-4fef-bc0d-700feb9080b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText4']</value>
      <webElementGuid>4010c2f0-915a-441c-af33-75ad6b5e80e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader4']/table/tbody/tr/th</value>
      <webElementGuid>d2c18468-cc18-48d8-a46d-14009cd34941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numero Acuerdo'])[1]/following::th[3]</value>
      <webElementGuid>d9cb8e71-0e02-402c-a778-90be13963694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripcion'])[1]/following::th[6]</value>
      <webElementGuid>9659380a-3221-4188-aa63-ef63b8198e36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha inicio'])[1]/preceding::th[2]</value>
      <webElementGuid>14e248f4-45c9-4ce7-b5bd-adae1df3dc1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha vence'])[1]/preceding::th[5]</value>
      <webElementGuid>4f1a4eda-cb2f-4000-9439-f83be2a39738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Monto']/parent::*</value>
      <webElementGuid>f82d7bfd-239f-47f6-a086-2711dd19598f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/table/tbody/tr/th</value>
      <webElementGuid>1e7df1cb-d70e-40c8-9ecd-b5190657a330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText4' and (text() = 'Monto' or . = 'Monto')]</value>
      <webElementGuid>1271d4dc-7600-4e55-ac10-0837dd910319</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
