<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblNumeroOperacionValidacion</name>
   <tag></tag>
   <elementGuidId>0c6222ba-2ef6-4643-83fb-35f2d95fe56e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.ENQ-H-DATA.ENQ-H-DATA_BCCLEMMENTRADASCONT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='enqheader']/tbody/tr/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>65f4f93f-6543-41b6-bd93-b142cfe80f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ENQ-H-DATA ENQ-H-DATA_BCCLEMMENTRADASCONT</value>
      <webElementGuid>cfb9e6f7-11b0-4c76-b9d1-1c8d7d9d8a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>11918739</value>
      <webElementGuid>06c733de-9ddd-4577-bfcc-391c3454510b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqheader&quot;)/tbody[1]/tr[1]/td[@class=&quot;ENQ-H-DATA ENQ-H-DATA_BCCLEMMENTRADASCONT&quot;]</value>
      <webElementGuid>8e36128b-072d-4204-a401-47bbce26c682</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='enqheader']/tbody/tr/td[2]</value>
      <webElementGuid>8cfe9e18-cb82-4a29-a975-b4eff23c9654</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Numero Operacion:'])[1]/following::td[1]</value>
      <webElementGuid>ea7d1fa9-35f2-4132-8cc6-bf152e366994</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como XML'])[2]/following::td[4]</value>
      <webElementGuid>de264e8f-3e73-47f8-8464-4ff848791629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ID Plazo Fijo:'])[1]/preceding::td[1]</value>
      <webElementGuid>270bc910-e974-4b72-8dc8-9381985425dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MM2214015412'])[1]/preceding::td[2]</value>
      <webElementGuid>017e0afe-0bc6-4a11-b50e-218830b4549d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='11918739']/parent::*</value>
      <webElementGuid>3bb3f457-1779-4f95-83ad-73c193bc1520</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/table/tbody/tr/td[2]</value>
      <webElementGuid>041b1fbf-1101-4080-900f-17a94407cd2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '11918739' or . = '11918739')]</value>
      <webElementGuid>45b41f32-57f6-477f-ba26-1b61caac27db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
