<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnVolver</name>
   <tag></tag>
   <elementGuidId>0c2d0812-679a-4ddd-8f0c-3eb5fd44d79e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td[8]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Volver a la pantalla de aplicacion&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>08510aa3-844d-495d-bcd7-fc16f2784e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/up.gif
															</value>
      <webElementGuid>96777cc8-9389-42df-ad3a-580e4d3abd06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Volver a la pantalla de aplicacion</value>
      <webElementGuid>8ca09b94-8996-45bc-a78f-f3246829d69e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Volver a la pantalla de aplicacion</value>
      <webElementGuid>45039087-99e2-4cf4-8fd4-4725d4bc6874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goButton&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[8]/a[1]/img[1]</value>
      <webElementGuid>29015370-4c38-436d-969e-1e076fdfa399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0096d593-c885-4e66-bd37-c5e90dd53db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/up.gif
															</value>
      <webElementGuid>3765b78c-ae4d-4f66-8d76-14c7835980b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Volver a la pantalla de aplicacion</value>
      <webElementGuid>5cf73e9e-32ad-4133-b0af-94a52ae3c28f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Volver a la pantalla de aplicacion</value>
      <webElementGuid>58ebe3e8-f122-4299-aa0d-b4ae8aabc6dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;goButton&quot;)/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[8]/a[1]/img[1]</value>
      <webElementGuid>f1b08257-857e-4815-9b8b-03cf6b91b9d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='goButton']/tbody/tr/td/table/tbody/tr/td[8]/a/img</value>
      <webElementGuid>36f1176c-bcec-4e0d-bac5-574465259f63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Volver a la pantalla de aplicacion']</value>
      <webElementGuid>6f01ec02-ecae-4675-9c18-7c278aa663a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/a/img</value>
      <webElementGuid>cd8716e9-b8be-4afd-85fb-46e7f9b364ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/tools/up.gif
															' and @alt = 'Volver a la pantalla de aplicacion' and @title = 'Volver a la pantalla de aplicacion']</value>
      <webElementGuid>cd8ff266-bef4-4d72-a148-9f622bf2a28c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
