<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTXNCompleta</name>
   <tag></tag>
   <elementGuidId>9fae8395-5679-4084-9c5f-a9ccee6ebc9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6685540f-9c4c-4439-aec2-8541e4294cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>ded757a9-50e2-4636-8d2f-923c549bdfef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Txn Completa: MEP2221020493681 17:16:32 29 JUN 2023 BCCL.MEP.FT.TRANSFER.HIS,BCCL.BAJA.MEP I </value>
      <webElementGuid>4e53f622-cb96-4c12-b173-93ae43455387</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appreq&quot;)/div[@class=&quot;display_box display_box_BCCLMEPFTTRANSFERHIS display_box_BCCLMEPFTTRANSFERHIS_BCCLBAJAMEP&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@id=&quot;messages&quot;]/tbody[1]/tr[2]/td[2]/table[2]/tbody[1]/tr[1]/td[@class=&quot;message&quot;]</value>
      <webElementGuid>f1c244b6-ee46-45f8-ad9d-bd48558eb78b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      <webElementGuid>63f68473-8ffd-4cac-9ac7-d32e80c5e694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.074 Caseros Centro)'])[1]/following::td[7]</value>
      <webElementGuid>ac1a5e03-f641-4d71-9cd0-76258bca577e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BCCL.MEP.FT.TRANSFER.HIS,BCCL.BAJA.MEP'])[1]/following::td[14]</value>
      <webElementGuid>bcf8d091-b9c8-43ba-b27c-36823be88fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='YA ESTA AUTORIZADO, VERIFIQUE'])[1]/preceding::td[1]</value>
      <webElementGuid>f744cb62-21a6-4c01-8318-c0390a539890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::td[3]</value>
      <webElementGuid>34a82283-12b3-47b8-a521-4a846ffff4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Txn Completa: MEP2221020493681 17:16:32 29 JUN 2023 BCCL.MEP.FT.TRANSFER.HIS,BCCL.BAJA.MEP I']/parent::*</value>
      <webElementGuid>c4ea9d4b-68cf-4f46-94c6-1f1edc3bf47f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td</value>
      <webElementGuid>c939c632-9a7f-45df-9ac0-9c42e790f30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Txn Completa: MEP2221020493681 17:16:32 29 JUN 2023 BCCL.MEP.FT.TRANSFER.HIS,BCCL.BAJA.MEP I ' or . = 'Txn Completa: MEP2221020493681 17:16:32 29 JUN 2023 BCCL.MEP.FT.TRANSFER.HIS,BCCL.BAJA.MEP I ')]</value>
      <webElementGuid>772bcc72-9b69-4881-9700-a1bfe3fdbefb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
