<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnCodigoIPDropdown</name>
   <tag></tag>
   <elementGuidId>67c64eba-466e-44c6-b504-37e59660dbdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.dropdown_button.dropdown_button_BCCLIPPARTIDAS.dropdown_button_BCCLIPPARTIDAS_ALTACA</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[2]/td[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>dceec902-0e27-4605-a076-c7578fd3735a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>c340f781-718b-4c1b-89d0-340a629b745c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>1fc25dab-f86a-43d9-8b14-7c7a1887a10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_BCCLIPPARTIDAS dropdown_button_BCCLIPPARTIDAS_ALTACA</value>
      <webElementGuid>51741e4d-823e-4597-b838-516edffa24ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>enquiryDropdown(event)</value>
      <webElementGuid>ec9baeef-c711-4b10-9b54-fe7bfd69b7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lista de Registros</value>
      <webElementGuid>e07c267b-eb28-4e9b-9ec0-f496d34e0e1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/dropdown.gif</value>
      <webElementGuid>f4b77383-b030-4c15-b50f-0af0f705af0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>126a9afb-d513-458c-9f54-059a927cda3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enquiryfield</name>
      <type>Main</type>
      <value>BCCL.E.IP.PARTIDAS.CODIGOSIP.A</value>
      <webElementGuid>858d0951-eb1d-4818-b152-72a0de8b13e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropfield</name>
      <type>Main</type>
      <value>fieldName:CODIGO.IP</value>
      <webElementGuid>d6d5e60f-a87f-4544-b749-8f1ba46993da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriafield</name>
      <type>Main</type>
      <value>TIPO.ALTA.BAJA</value>
      <webElementGuid>612b6aeb-0633-4781-b889-a3a1956a125a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriaopfield</name>
      <type>Main</type>
      <value>EQ</value>
      <webElementGuid>a8d9f85c-d0cc-4765-a4b1-efc0b5d7215d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatafield</name>
      <type>Main</type>
      <value>fieldName:TIPO.ALTA</value>
      <webElementGuid>ad4086cd-410c-4790-93c4-37ebe33a6a2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enqfieldname</name>
      <type>Main</type>
      <value>fieldName:CODIGO.IP</value>
      <webElementGuid>d53764d0-b1c0-494b-9899-1181fdf29d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>1d00dbac-3041-4a87-82f9-b4cac00fb16f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[2]/td[3]/a[1]/img[@class=&quot;dropdown_button dropdown_button_BCCLIPPARTIDAS dropdown_button_BCCLIPPARTIDAS_ALTACA&quot;]</value>
      <webElementGuid>29f9531d-3eba-4d8e-a479-e18a4ff936b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[2]/td[3]/a/img</value>
      <webElementGuid>2274e62d-939a-48bb-a0a3-f2abb65ad6fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Lista de Registros']</value>
      <webElementGuid>dbd6f79b-715c-480e-865b-0f4e7357731d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/img</value>
      <webElementGuid>fb9a90f4-87ed-4172-b2d0-4fd264697502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Lista de Registros' and @src = '../plaf/images/bccl/deal/dropdown.gif']</value>
      <webElementGuid>3f643512-37e4-4b42-a288-25d5c1443cee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
