<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDropDownConcepto</name>
   <tag></tag>
   <elementGuidId>2f607d02-95e5-49c0-84ae-9573def0aa9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[6]/td[4]/a/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d0ceeac-3b2c-4d78-a66b-64ef9c41062a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>291388c6-9332-4de7-8af6-183968b432bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>e52b76e5-faf7-4a52-8fba-b714439ed912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_TELLER dropdown_button_TELLER_INGRESOS</value>
      <webElementGuid>274034ff-9bb4-459a-9d5f-261c0c0a1ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>enquiryDropdown(event)</value>
      <webElementGuid>e226c6de-441e-4a77-91d5-16820c140ad4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lista de Registros</value>
      <webElementGuid>cf39c60e-13e3-48a4-b6ca-77032485114d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/dropdown.gif</value>
      <webElementGuid>23906d4e-3401-47cb-8a10-d81cdb9f1785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>c2a30647-3cfe-4713-a5b0-76df65b9e89a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enquiryfield</name>
      <type>Main</type>
      <value>BCCL.E.EB.CONCEPTOS</value>
      <webElementGuid>b88ec3b5-3db7-41ab-9047-b8b263797fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropfield</name>
      <type>Main</type>
      <value>fieldName:L.EB.CONCEPTO</value>
      <webElementGuid>ec300dac-597b-484e-b0b0-6f2658083d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriafield</name>
      <type>Main</type>
      <value>FT.TT.INFO</value>
      <webElementGuid>c07d4c97-7c9a-4d74-b0e7-4c32d7ca97c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriaopfield</name>
      <type>Main</type>
      <value>EQ</value>
      <webElementGuid>f819e7f2-140e-4fac-a737-06435bdf87d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatafield</name>
      <type>Main</type>
      <value>fieldName:</value>
      <webElementGuid>5e32f418-bb71-45ad-9a87-2ba5c0909822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatastring</name>
      <type>Main</type>
      <value>'1'</value>
      <webElementGuid>fea7c467-6480-41ee-8aad-8abdb29c2af6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enqfieldname</name>
      <type>Main</type>
      <value>fieldName:L.EB.CONCEPTO</value>
      <webElementGuid>cd65eaeb-1a1b-4b5b-85a7-bdb637d75608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>4a40cf0c-b7bb-4bd0-8a5a-d3a3a40dce9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[6]/td[4]/a[1]/img[@class=&quot;dropdown_button dropdown_button_TELLER dropdown_button_TELLER_INGRESOS&quot;]</value>
      <webElementGuid>8a22a6ad-ea5e-4f82-8e86-89f907596435</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[6]/td[4]/a/img</value>
      <webElementGuid>7e0d24f7-a0d3-4e82-ab33-ae7a8bc3eb0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Lista de Registros'])[2]</value>
      <webElementGuid>7c18ab53-be9a-469a-bc3e-975f7e788d6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[4]/a/img</value>
      <webElementGuid>07177db1-5dc5-432f-86f2-b698e5271767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Lista de Registros' and @src = '../plaf/images/bccl/deal/dropdown.gif']</value>
      <webElementGuid>1b4521a9-3749-46d4-a37a-368cd7257f3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
