<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblSucursal</name>
   <tag></tag>
   <elementGuidId>6ce616a7-5784-4cd8-a10c-1ca6a85d1a68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.ENQ-H-DATA.ENQ-H-DATA_BCCLEEBTOTALUSUARIOSME</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='enqheader']/tbody/tr[2]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>aabc67d5-dc31-487a-a855-a8c9774b6f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ENQ-H-DATA ENQ-H-DATA_BCCLEEBTOTALUSUARIOSME</value>
      <webElementGuid>4f0468ed-38d8-4cc9-95e6-8c9d28398757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>001</value>
      <webElementGuid>353554d6-a249-40df-9d4e-32f410161abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqheader&quot;)/tbody[1]/tr[2]/td[@class=&quot;ENQ-H-DATA ENQ-H-DATA_BCCLEEBTOTALUSUARIOSME&quot;]</value>
      <webElementGuid>21b156d7-4ee0-4abe-9885-6ee7d69ec87c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='enqheader']/tbody/tr[2]/td[2]</value>
      <webElementGuid>48d8eead-df69-4e75-8e8a-30815281c214</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch:'])[1]/following::td[1]</value>
      <webElementGuid>a451765b-dd5e-450f-b589-01c09e26a425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codigo Operativo'])[1]/following::td[2]</value>
      <webElementGuid>87415293-e6d5-40af-8044-e446a3d1120a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Centro'])[1]/preceding::td[1]</value>
      <webElementGuid>c1d4dd6c-00c8-47b8-b96d-cf72782d1791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fec. Proceso:'])[1]/preceding::td[2]</value>
      <webElementGuid>d5b1f9f5-e5bb-47a1-be8e-0b3f989c9551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='001']/parent::*</value>
      <webElementGuid>6dcd2031-a12f-4179-8804-12cd5be44d8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>c3716fa5-a5b9-411a-b6ac-71ec3d0b43bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '001' or . = '001')]</value>
      <webElementGuid>5bd4ebe3-f159-4f2a-911c-bdcbbaf87c0b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
