<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblListadoInversores</name>
   <tag></tag>
   <elementGuidId>509d501b-b9d8-4a49-86f0-a637cc0a6fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#enqheader > tbody > tr > td</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='enqheader']/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>89e58e7e-d4e2-4182-a4aa-ddd982f5d60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Listado Principales Inversores</value>
      <webElementGuid>87798393-a0bf-40d2-9af4-66eb07a3542a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqheader&quot;)/tbody[1]/tr[1]/td[1]</value>
      <webElementGuid>9f1d2e8c-049a-4f91-a958-e4581f3d3521</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='enqheader']/tbody/tr/td</value>
      <webElementGuid>df2d45e7-32e2-4fdc-a787-e7d13bde5132</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como XML'])[2]/following::td[3]</value>
      <webElementGuid>257c1ee2-dd2f-450e-9de8-e335543724c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como HTML'])[2]/following::td[4]</value>
      <webElementGuid>fcd1a861-382a-4caa-859d-dc26e515dd22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moneda:'])[1]/preceding::td[1]</value>
      <webElementGuid>b428734a-2df1-4e2f-a509-5c6ebc331c30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[1]/preceding::td[2]</value>
      <webElementGuid>92ecf79c-c3b2-406e-ab75-cbb210484fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Listado Principales Inversores']/parent::*</value>
      <webElementGuid>b7ab5b19-2b29-46aa-9490-02625e0624ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/table/tbody/tr/td</value>
      <webElementGuid>c39f7d36-66a6-47fa-b540-af6e212479a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Listado Principales Inversores' or . = 'Listado Principales Inversores')]</value>
      <webElementGuid>42282424-fee2-4a94-b4a6-4d41d4db200b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
