<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDropdownEstado</name>
   <tag></tag>
   <elementGuidId>a7634b30-3f1b-4f93-9041-76a3be44fb41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.dropdown_button.dropdown_button_BCCLAPPIEZAS.dropdown_button_BCCLAPPIEZAS_BCCLVAPSTSENVIAFILIAL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr/td[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>212aa91a-2083-42ee-894f-416c1ea6edf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>b618014b-4dbf-4f81-a0f6-7c5836cf0c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>85852615-615d-4dab-934e-395319eae152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_BCCLAPPIEZAS dropdown_button_BCCLAPPIEZAS_BCCLVAPSTSENVIAFILIAL</value>
      <webElementGuid>3f38d858-b1ba-42ff-9758-d565c47f3f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>enquiryDropdown(event)</value>
      <webElementGuid>66e5b9ca-0e56-4aa8-acbc-ce7f84a2b4fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lista de Registros</value>
      <webElementGuid>95108e1e-b117-44eb-bf5a-fe974ea1e549</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/dropdown.gif</value>
      <webElementGuid>70cfb18c-52fe-4e90-a423-f317a9d5c638</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>2de11213-c18c-4eee-bdbb-b4c633c1f5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enquiryfield</name>
      <type>Main</type>
      <value>BCCL.E.AP.ESTADOS.PIEZAS.SALIDA</value>
      <webElementGuid>c9467bee-bf3d-4534-b845-f77c3565fa1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropfield</name>
      <type>Main</type>
      <value>fieldName:AP.ESTADO.PIEZA</value>
      <webElementGuid>0e66f0c0-2a5e-4a4b-8ab0-fbdafbb545e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriafield</name>
      <type>Main</type>
      <value>TIPO.MOV</value>
      <webElementGuid>d04b6bcc-c670-40bf-ac97-5f386b9026d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriaopfield</name>
      <type>Main</type>
      <value>EQ</value>
      <webElementGuid>680677ca-5884-4b0c-b689-925ef05fccb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatafield</name>
      <type>Main</type>
      <value>fieldName:</value>
      <webElementGuid>9d0c6fa0-3d34-4921-b252-3220ed8868d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatastring</name>
      <type>Main</type>
      <value>'S'</value>
      <webElementGuid>f06b2299-e382-47dc-9d00-1003297689ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enqfieldname</name>
      <type>Main</type>
      <value>fieldName:AP.ESTADO.PIEZA</value>
      <webElementGuid>0e347d82-f015-4a40-860c-d5c624bdc757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>efb047d2-4fe3-4af7-83bf-25184ad59de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[1]/td[3]/a[1]/img[@class=&quot;dropdown_button dropdown_button_BCCLAPPIEZAS dropdown_button_BCCLAPPIEZAS_BCCLVAPSTSENVIAFILIAL&quot;]</value>
      <webElementGuid>c45dc40e-5458-4a1d-80ac-fb87f9bcee69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td[3]/a/img</value>
      <webElementGuid>81a7991f-f8bf-4447-9710-14660b71bfa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Lista de Registros']</value>
      <webElementGuid>d62a5e93-8992-4ea8-8791-6494abd3ccde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/a/img</value>
      <webElementGuid>9f117637-9609-4c7d-ace1-eeacf25ec177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Lista de Registros' and @src = '../plaf/images/bccl/deal/dropdown.gif']</value>
      <webElementGuid>65479dcc-1bc7-48a8-8b0f-7b1b4c416cc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
