<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDropdownPlastico</name>
   <tag></tag>
   <elementGuidId>d7d20168-563b-4393-bb48-528094624f83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.dropdown_button.dropdown_button_BCCLAPPIEZAS.dropdown_button_BCCLAPPIEZAS_BCCLVAPDENUNCIAINDIVIDUAL</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[7]/td[9]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b9885b6c-31d2-4595-b324-7abe340cb52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>9c6998b0-aa0a-40d5-bb40-a5cda40b6e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>5047c567-7d04-4fae-a177-68013c52f4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_BCCLAPPIEZAS dropdown_button_BCCLAPPIEZAS_BCCLVAPDENUNCIAINDIVIDUAL</value>
      <webElementGuid>8b42c31a-35aa-445d-8e39-329b7c90182d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>enquiryDropdown(event)</value>
      <webElementGuid>30910d31-6031-4a09-97e9-998c4faaec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lista de Registros</value>
      <webElementGuid>b1e9e950-b694-4d4e-bdaa-268e810d94de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/dropdown.gif</value>
      <webElementGuid>bcaf2759-f921-45ce-8840-09c15667a010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>3802469d-d127-4b6e-988f-20d1c10eb9fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enquiryfield</name>
      <type>Main</type>
      <value>BCCL.AP.ESTADO.TAJETAS.TIPO</value>
      <webElementGuid>596511aa-ee10-4d33-ab69-b62ff8b9e60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropfield</name>
      <type>Main</type>
      <value>fieldName:AP.ESTADO.PLAS:1</value>
      <webElementGuid>25d43e2a-9e45-4f49-b844-30d1d691f526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriafield</name>
      <type>Main</type>
      <value>@ID</value>
      <webElementGuid>33d63aae-0080-46ed-a51e-9785228b6d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriaopfield</name>
      <type>Main</type>
      <value>GE</value>
      <webElementGuid>e707c16b-afe1-46c5-b099-8733fc213d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatafield</name>
      <type>Main</type>
      <value>fieldName:</value>
      <webElementGuid>9143a366-4c03-42b1-8b38-5d4581132119</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>criteriadatastring</name>
      <type>Main</type>
      <value>'950'</value>
      <webElementGuid>4d3ab484-77e0-4e4f-856a-0259e13588de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enqfieldname</name>
      <type>Main</type>
      <value>fieldName:AP.ESTADO.PLAS</value>
      <webElementGuid>bd3fb99c-15a5-496a-8193-8ee89b94e5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>0f67f3ac-49bf-4f4d-9c48-d0a1c1441d6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[7]/td[9]/a[1]/img[@class=&quot;dropdown_button dropdown_button_BCCLAPPIEZAS dropdown_button_BCCLAPPIEZAS_BCCLVAPDENUNCIAINDIVIDUAL&quot;]</value>
      <webElementGuid>d78c5ebf-6611-4eca-83ba-28dbe4a11005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[7]/td[9]/a/img</value>
      <webElementGuid>b9b3afba-03aa-456e-a92c-cbc429b721b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Lista de Registros']</value>
      <webElementGuid>1f3bc4f4-4c9d-4440-9532-0f8ae5636bcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[9]/a/img</value>
      <webElementGuid>5f509ac8-ed1b-4d19-8773-bf5017201985</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Lista de Registros' and @src = '../plaf/images/bccl/deal/dropdown.gif']</value>
      <webElementGuid>d5b81c7b-0b1b-4dc3-9902-d90377931fc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
