<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAccion</name>
   <tag></tag>
   <elementGuidId>0382b319-a986-46b5-9165-a1253e670b7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='disabled_AP.ESTADO.PIEZA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>ee2622f9-f2d8-41c3-a67d-293513a2c628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>disabled_AP.ESTADO.PIEZA</value>
      <webElementGuid>d195f5ae-9e01-4474-8ea6-2bfdccfb60d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>disabled_dealbox disabled_dealbox_BCCLAPPIEZAS disabled_dealbox_BCCLAPPIEZAS_BCCLVAPENTREGAALSOCIO</value>
      <webElementGuid>c1ada38c-9a3b-47a3-ae06-cde2a0eca1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>090</value>
      <webElementGuid>706ef56c-858e-4fc1-8921-10d73bd395cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;disabled_AP.ESTADO.PIEZA&quot;)</value>
      <webElementGuid>efd082df-63d8-47e3-9bdc-e6e1145c5d10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='disabled_AP.ESTADO.PIEZA']</value>
      <webElementGuid>9c880563-626d-462b-a4f4-7b4ce37ff9a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td[3]/span</value>
      <webElementGuid>3d451017-e7e3-4e07-949e-974ce995f52d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCION'])[1]/following::span[1]</value>
      <webElementGuid>47eb82ce-9b29-4d14-a400-1575c183f108</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.073 Jujuy)'])[1]/following::span[1]</value>
      <webElementGuid>39b85ae3-ad0c-4d3d-be02-022aef8fdc02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entregada al Socio'])[1]/preceding::span[1]</value>
      <webElementGuid>7ece1bfe-d40a-4661-bd63-398382d48190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sucursal'])[1]/preceding::span[2]</value>
      <webElementGuid>2a0c1159-11c4-48bb-8c9a-9d58fb4383d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='090']/parent::*</value>
      <webElementGuid>1f3bb6c4-c35a-4878-b34d-ba5ef7eedefa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/span</value>
      <webElementGuid>44ee609f-16dd-497a-a027-8303803ce4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'disabled_AP.ESTADO.PIEZA' and (text() = '090' or . = '090')]</value>
      <webElementGuid>9820fd6e-fec6-4a78-b4ef-81840dd4fde6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
