<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnLupa</name>
   <tag></tag>
   <elementGuidId>d8cc68a7-4f1d-4715-94e5-5d49ca883b87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Pantalla de Seleccion&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pane_']/div/div/table/tbody/tr/td[2]/div/table/tbody/tr/td[2]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>256a35d3-e138-4275-8e50-a9f4dcdddc9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/select.gif
															</value>
      <webElementGuid>6b8cd85c-b1c1-4206-8737-da12bc1c10bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Pantalla de Seleccion</value>
      <webElementGuid>a4b936b2-eb58-47cc-b190-7831d1112572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Pantalla de Seleccion</value>
      <webElementGuid>4946dcce-89e0-4b1b-ba0b-377eedfd9f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/div[@class=&quot;denqresponse denqresponse_BCCLECHQCANCELA&quot;]/div[@class=&quot;display_box display_box_BCCLECHQCANCELA&quot;]/table[1]/tbody[1]/tr[1]/td[2]/div[1]/table[1]/tbody[1]/tr[1]/td[2]/a[1]/img[1]</value>
      <webElementGuid>9c765030-6f13-4adc-9ce9-cb88bc814005</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/div/div/table/tbody/tr/td[2]/div/table/tbody/tr/td[2]/a/img</value>
      <webElementGuid>2d25e2d9-8c0c-4f59-9aca-34fe5fc13e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Pantalla de Seleccion']</value>
      <webElementGuid>da9abcd9-2751-4c69-a4ce-f2d419b17d7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/a/img</value>
      <webElementGuid>3de3f580-4f03-4e26-9973-4c6f3a96c72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../plaf/images/bccl/tools/select.gif
															' and @alt = 'Pantalla de Seleccion' and @title = 'Pantalla de Seleccion']</value>
      <webElementGuid>feddd6eb-2813-4c47-b958-588b8bf86cd0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
