<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblMONTOREGISTRADO</name>
   <tag></tag>
   <elementGuidId>9afd8ef8-d184-400d-8918-7d5f8b7ec7ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText7']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText7</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>5341ea4d-0949-4d0b-9dd2-293f0b689130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>fc91ee32-329b-4692-acfa-0215c38f1740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>0f7e636e-2290-4879-ad47-15aaa34a8ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText7</value>
      <webElementGuid>f2b0655b-3f20-4ef3-adfd-eccccbc55ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MONTO REGISTRADO</value>
      <webElementGuid>44a8cb96-97b7-41f6-b7b8-8ccf33fa7c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText7&quot;)</value>
      <webElementGuid>932ef71b-60e1-4361-a804-5b06e247bce4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText7']</value>
      <webElementGuid>eefba0d3-358b-4423-8d78-cc85b3c273a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader7']/table/tbody/tr/th</value>
      <webElementGuid>69607881-8494-48d2-afc7-5465892ea141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MONTO REAL'])[1]/following::th[3]</value>
      <webElementGuid>e78fff06-5d64-466d-bc98-aaa0f3969dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NRO TARJETA'])[1]/following::th[6]</value>
      <webElementGuid>4387e427-e683-4ef5-a77d-52ac1856aec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIFERENCIA'])[1]/preceding::th[2]</value>
      <webElementGuid>5939fdb1-79c5-44bb-8af8-4dc819160d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESTADO'])[1]/preceding::th[5]</value>
      <webElementGuid>89c139e1-e8fc-4f17-923d-37d041de6e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MONTO REGISTRADO']/parent::*</value>
      <webElementGuid>10f0e3aa-a611-42d8-b4aa-ef557b6fd8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/table/tbody/tr/th</value>
      <webElementGuid>919c8c92-cbd0-4339-aa11-6764eb0b5962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText7' and (text() = 'MONTO REGISTRADO' or . = 'MONTO REGISTRADO')]</value>
      <webElementGuid>d8e06de6-4c9f-478e-a8ab-7cf88a4a2859</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
