<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtFechaVigencia</name>
   <tag></tag>
   <elementGuidId>02f1d867-a01e-4af5-a01c-b1f41558da22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:L.FEC.VIGENCIA']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4792e59e-58c6-4a96-900f-78be104fac4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1fd04f3a-9c6e-4631-bf93-1b5461b32db8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>fdfe9eb6-b102-4bc5-8d5b-1937d28908c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:L.FEC.VIGENCIA</value>
      <webElementGuid>2eb1b52c-b60f-4eb1-ae29-5a55a998e4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:L.FEC.VIGENCIA</value>
      <webElementGuid>fcb227f0-a75b-442e-b0e1-c7c6bd17355e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>41824e94-abd7-4318-8787-976017724c0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_FTCOMMISSIONTYPE dealbox_FTCOMMISSIONTYPE_BCCLMODCOM</value>
      <webElementGuid>34b31dbe-a9d5-4dad-b260-36a4a58f1152</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>5cb3736e-6c57-49f5-8a04-f0584267bf6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>monthdesc</name>
      <type>Main</type>
      <value>ENE FEB MAR ABR MAY JUN JUL AGO SEP OCT NOV DIC</value>
      <webElementGuid>0a6c6c0f-ae0a-4a29-a042-f8ea0a70b9da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed591f6d-c964-4850-b4bb-c90a817c7a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fielderror</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>66da224e-3113-4681-9f01-08abe891af9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_L.FEC.VIGENCIA</value>
      <webElementGuid>5d04f628-5a5f-4e0f-a886-2c705a0fe752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'L.FEC.VIGENCIA','issueToken');</value>
      <webElementGuid>07c96bc7-24f4-45bd-8118-b8662b7ed1aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>1501087f-c132-4bb0-be2d-9ca182fd28e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('L.FEC.VIGENCIA','','','issueToken')</value>
      <webElementGuid>ed138a26-be29-4aed-a608-2cc06fc20ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:L.FEC.VIGENCIA&quot;)</value>
      <webElementGuid>3fcba83a-5616-490b-a34d-c6304985430b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:L.FEC.VIGENCIA']</value>
      <webElementGuid>521745d3-2a78-4e70-8d4c-411aa62ba8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[28]/td[4]/input</value>
      <webElementGuid>86526889-c4d9-400a-bac6-b443a31f979e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[28]/td[4]/input</value>
      <webElementGuid>f1a43877-516b-4f0a-b9f2-098f6430a4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:L.FEC.VIGENCIA' and @name = 'fieldName:L.FEC.VIGENCIA' and @type = 'text']</value>
      <webElementGuid>28dab431-2ac8-4cd7-9727-712ed4cc5487</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
