<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblVarios</name>
   <tag></tag>
   <elementGuidId>c000bc35-9e73-453e-9246-2a5b1bdba1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropDownRow26 > td.coloumntddata.coloumntddata_BCCLEMOTIVOTINT > b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dropDownRow26']/td/b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>976b5dd1-89e5-42cc-bb27-fba87d5f34e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VAR</value>
      <webElementGuid>ce92c164-1346-475f-a5ad-572b112f7b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownRow26&quot;)/td[@class=&quot;coloumntddata coloumntddata_BCCLEMOTIVOTINT&quot;]/b[1]</value>
      <webElementGuid>9eed8078-ce43-4b17-ac94-058e5ba3d13f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dropDownRow26']/td/b</value>
      <webElementGuid>0f0749df-4297-4325-a6ce-49fd0201e52f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Suscripcion Obligaciones Negociable'])[2]/following::b[1]</value>
      <webElementGuid>4cae7fef-4e50-4784-9d76-d25234e0802a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SON'])[1]/following::b[1]</value>
      <webElementGuid>10658fdd-51a2-4dff-a9df-167da2241170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Varios'])[1]/preceding::b[1]</value>
      <webElementGuid>a7e58e22-dd29-415b-92b5-2c3f4505fd88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VAR']/parent::*</value>
      <webElementGuid>2a499649-7ecd-4770-a499-a8592c4f766e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[27]/td/b</value>
      <webElementGuid>f5bc6272-46ff-4c25-8889-5b4faa4a9c4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = 'VAR' or . = 'VAR')]</value>
      <webElementGuid>0dfe2edc-db31-4ab3-abc2-67db5b0d76ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
