<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtIddeCuenta</name>
   <tag></tag>
   <elementGuidId>03c36008-100f-4a87-9d50-1e57e9e2e581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:CQ.CTA']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52854623-30d2-441a-b91a-eb57fd3e5fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5c16eb78-8aaa-40af-82fe-00a42fbac230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>7dcb8e3c-b151-4e6e-8c96-b29dff84e5b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:CQ.CTA</value>
      <webElementGuid>db943dcf-9c38-492d-9e9c-20b2569478fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:CQ.CTA</value>
      <webElementGuid>d58c2ff2-4b05-434a-90ab-371353798677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>c8716c61-99c3-4385-81a8-f5de4c0a954b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_BCCLCQSOLICITUD dealbox_BCCLCQSOLICITUD_INGRESOSUC</value>
      <webElementGuid>f31b5eca-32c0-43e8-889d-dcb337ed4aee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>578e2557-0a0a-450f-a732-cc23700a13cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd21b8ff-fa63-404f-bf6b-8bbaebfea44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropdown</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>0ce4e91d-356d-4d34-8743-fd0c5f1b742a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ebr</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>e0bf010f-9415-448e-8151-4a2fa80c8478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_CQ.CTA</value>
      <webElementGuid>fc9824d0-9511-4fdf-9475-4abfba3cc5e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'CQ.CTA','issueToken');</value>
      <webElementGuid>531b1ffb-6995-4a70-8a18-8ca8323cc44f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>61bea4d8-cd13-42ed-a1d7-92e9308eee5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('CQ.CTA','','','issueToken')</value>
      <webElementGuid>df49bd5a-83f5-48fa-ac1e-d13d59d58f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:CQ.CTA&quot;)</value>
      <webElementGuid>f3848df3-c195-41a1-afdf-6de045cd8aba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:CQ.CTA']</value>
      <webElementGuid>07a3d087-867e-450b-a3b4-6ee36d0c5537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td[3]/input</value>
      <webElementGuid>6093c952-adba-4fd4-ae93-865617726222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>006e6341-bac3-4901-9472-9510e6c2561b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:CQ.CTA' and @name = 'fieldName:CQ.CTA' and @type = 'text']</value>
      <webElementGuid>b3845e46-463f-45f2-a0f4-64c762a4858a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
