<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtImporte</name>
   <tag></tag>
   <elementGuidId>a316d136-99fe-4019-b747-28ae3837b5ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:CREDIT.AMOUNT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8f9ba88-025b-4df9-b89d-4874abaced8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a5d34b90-1a1b-47ef-9dab-f43c48478161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>6112df7f-6cc0-407d-a248-32d6d1ddef61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:CREDIT.AMOUNT</value>
      <webElementGuid>49212409-d245-4a95-a8c3-7cb053d1a27c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:CREDIT.AMOUNT</value>
      <webElementGuid>07afd0d4-2461-4e55-b8a5-f11f7e734523</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>32404af2-4aac-4322-bdf6-cfd8305dbbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_FUNDSTRANSFER dealbox_FUNDSTRANSFER_BCCLACCT</value>
      <webElementGuid>3ef66d35-dcd9-4a45-acaa-0a4f3d7991e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>dcf2ca58-d0bd-4aeb-af96-ea7e620f17cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c1b365b7-2580-4a66-82ce-2d3d79604859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_CREDIT.AMOUNT</value>
      <webElementGuid>d4eac427-abbc-4e8c-92b6-2f06c2a3344e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'CREDIT.AMOUNT','issueToken');</value>
      <webElementGuid>8143365f-8b8b-49ad-860b-37b323cf41d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>4226c04e-8ab5-4b06-a9a7-fa9b64cdfed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('CREDIT.AMOUNT','','','issueToken')</value>
      <webElementGuid>4e1f8cd6-1277-4971-b5eb-1761249fb41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:CREDIT.AMOUNT&quot;)</value>
      <webElementGuid>2a062b73-6aa4-4246-9a6d-0a8fb5931c38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:CREDIT.AMOUNT']</value>
      <webElementGuid>950045b3-959b-4b99-9884-d8505845e873</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[3]/td[3]/input</value>
      <webElementGuid>56c69f7d-28c5-4fa9-93b9-d6ce7e5d1178</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/input</value>
      <webElementGuid>062cfabb-4c85-4d7a-b478-9a0cafa66472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:CREDIT.AMOUNT' and @name = 'fieldName:CREDIT.AMOUNT' and @type = 'text']</value>
      <webElementGuid>f9d850a7-c740-483d-b97a-4e36cc3b95cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
