<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>spanModificacion</name>
   <tag></tag>
   <elementGuidId>1dce1861-8422-4e9b-813a-fc63dca9980d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[1][count(. | //*[(text() = 'Modificacion' or . = 'Modificacion')]) = count(//*[(text() = 'Modificacion' or . = 'Modificacion')])]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//span[@onclick='ProcessMouseClick(event)'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5f744c74-5311-4acf-84a3-be340c396a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ProcessMouseClick(event)</value>
      <webElementGuid>a2de7fb2-a3fb-44fd-8a6d-4cffe81f7bc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>ProcessKeyPress(event)</value>
      <webElementGuid>9f2d4776-092b-4c34-baa7-322033dcac7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Modificacion</value>
      <webElementGuid>529ce070-c78c-4d77-a03d-10370814af24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pane_&quot;)/ul[@class=&quot;menuMargin&quot;]/li[@class=&quot;clsHasKids&quot;]/ul[1]/li[@class=&quot;clsHasKids&quot;]/span[1]</value>
      <webElementGuid>fdabdd7c-2894-4d55-88ea-b254ac979a52</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//span[@onclick='ProcessMouseClick(event)'])[3]</value>
      <webElementGuid>d713b847-a828-4ad1-8c60-e3f1a608aec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pane_']/ul/li/ul/li[2]/span</value>
      <webElementGuid>da374b0e-582c-461e-9b2d-d0e01fe45079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alta Persona Fisica Pendiente'])[1]/following::span[1]</value>
      <webElementGuid>a378f3de-5a10-4fa3-b192-22bfa8a20134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alta Persona Fisica'])[1]/following::span[1]</value>
      <webElementGuid>de7abddf-67eb-444c-8ad0-076dbce153a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modificacion datos domicilio y telefono'])[1]/preceding::span[1]</value>
      <webElementGuid>f4306575-d6c3-41c1-8fd0-762abb925e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consulta'])[1]/preceding::span[1]</value>
      <webElementGuid>7b682ebf-ca33-47bb-abde-b1ba022fbba2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Modificacion']/parent::*</value>
      <webElementGuid>352e7264-93d2-4e2a-9042-e6c6dbde2237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/span</value>
      <webElementGuid>2ac6d116-9a8b-4101-bac7-582d357742a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Modificacion' or . = 'Modificacion')]</value>
      <webElementGuid>d8e1d526-a70e-4513-8889-c3cc8a3e65a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
