<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblDolar</name>
   <tag></tag>
   <elementGuidId>cf04b2a6-ba61-44bc-8729-6ac60763c954</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropDownRow3 > td.coloumntddata.coloumntddata_BCCLEAUTOCURRENCY</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dropDownRow3']/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>94009f54-42ad-4f16-a22e-5b034409ffea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coloumntddata coloumntddata_BCCLEAUTOCURRENCY</value>
      <webElementGuid>4f1c0195-68dd-4600-b6b8-fde4897b1368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>USD</value>
      <webElementGuid>06bcbdf5-1da8-45af-b5f6-c78a2b41552d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownRow3&quot;)/td[@class=&quot;coloumntddata coloumntddata_BCCLEAUTOCURRENCY&quot;]</value>
      <webElementGuid>c5c9a438-7a61-4fb0-9e75-12947609d33c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dropDownRow3']/td</value>
      <webElementGuid>31a4f506-3c99-490f-bc9c-231d44045935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Euro'])[1]/following::td[1]</value>
      <webElementGuid>2c7936c7-3c6e-4ba7-b06c-bb5ae12fb67d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EUR'])[1]/following::td[2]</value>
      <webElementGuid>745c587c-68af-434a-b781-10a098174781</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dolar Estadounidense'])[1]/preceding::td[1]</value>
      <webElementGuid>b70a6bc7-ecf5-4b1f-b498-481b21f45086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[4]/td</value>
      <webElementGuid>4fb4a5fb-b9d8-4dbe-82ff-84223c2b395f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'USD' or . = 'USD')]</value>
      <webElementGuid>ff2a731b-8fdf-4e28-8661-d048c1ed0126</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
