<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxConsultarFirmas</name>
   <tag></tag>
   <elementGuidId>618d83d0-7ca1-444f-8f2a-a7c9f7a2605e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drillbox:1_3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;drillbox\:1_3&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f4fc9c70-3ac9-4561-a50d-e4aa4a6c63c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drillbox:1_3</value>
      <webElementGuid>d03be02f-a27b-44e4-a801-541f08d34544</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drillbox drillbox_BCCLEACFIRM</value>
      <webElementGuid>5e18674a-98bd-4d0b-97cf-3488d8a67a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ver CuentaVer FirmantesVer Datos MonetariosConsultar Firmas</value>
      <webElementGuid>315578ee-3e15-4035-b11e-68a9dbbc448a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drillbox:1_3&quot;)</value>
      <webElementGuid>cfe9039d-c358-4e3d-b8a3-8e9306cef924</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drillbox:1_3']</value>
      <webElementGuid>c0fa37c7-c206-4230-a3d9-16f73aad0ee5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r3']/td[8]/table/tbody/tr/td/select</value>
      <webElementGuid>f11792cd-0b9b-40dd-b107-1bbd7b074afc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activa'])[2]/following::select[1]</value>
      <webElementGuid>4fbd631e-f982-48c8-ba93-c9b83a230e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[3]/following::select[1]</value>
      <webElementGuid>cf74f677-8180-477f-b2d3-f3e71e09a652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Favoritos'])[1]/preceding::select[1]</value>
      <webElementGuid>a9006a1a-59c7-4faa-bacd-635d602140ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NRO DE CUENTA'])[1]/preceding::select[1]</value>
      <webElementGuid>696bbba3-c041-4a5e-952a-326e838b38f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[8]/table/tbody/tr/td/select</value>
      <webElementGuid>1acf9562-584e-4d24-b547-0a182bf4f934</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drillbox:1_3' and (text() = 'Ver CuentaVer FirmantesVer Datos MonetariosConsultar Firmas' or . = 'Ver CuentaVer FirmantesVer Datos MonetariosConsultar Firmas')]</value>
      <webElementGuid>9f26e4e7-b0ae-4885-aacd-d545fc214ab8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
