<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTituloEgresosVariosdeCaja</name>
   <tag></tag>
   <elementGuidId>c8a346db-8634-49f7-b0cd-5ab76881ff54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;TELLER,EGRESOS&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dealtitle']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>bd1a6092-dd40-4b6a-a58d-833668270fa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>cb41444c-3027-41cb-b721-3e3a05dedff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>759bfa0d-61ca-46f2-a11d-7a550c5c4f74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>TELLER,EGRESOS</value>
      <webElementGuid>98c6b099-d9b2-4dfe-8acd-44dc1257946f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:help(&quot;TELLER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);</value>
      <webElementGuid>8c2f39fd-0ff5-4582-a7bc-78a257160e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Egresos Varios de Caja</value>
      <webElementGuid>a1b23e25-6482-4194-9535-624ea7eeb364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dealtitle&quot;)/a[1]</value>
      <webElementGuid>051026eb-5405-4550-a22f-44a43859cc28</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dealtitle']/a</value>
      <webElementGuid>4c9385bc-e0fe-41fa-a741-50a961df281b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Egresos Varios de Caja')]</value>
      <webElementGuid>deb725c1-161c-47f9-95c4-8df33d687f39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TT22208834477710'])[1]/preceding::a[1]</value>
      <webElementGuid>cae15bb3-579e-4077-8a0f-b90488a0779a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.089 M.del Plata Ctr)'])[1]/preceding::a[1]</value>
      <webElementGuid>3e547f3b-4aed-48c8-80dd-23d168f328d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Egresos Varios de Caja']/parent::*</value>
      <webElementGuid>29a7c503-2878-44cb-9e84-6e1987debe6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:help(&quot;TELLER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);')]</value>
      <webElementGuid>91bd7255-2aa5-4914-bffb-69f38bb19c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>ea73afe5-3023-402d-9c14-7080183afed6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'TELLER,EGRESOS' and @href = 'javascript:help(&quot;TELLER&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);' and (text() = 'Egresos Varios de Caja' or . = 'Egresos Varios de Caja')]</value>
      <webElementGuid>7863096a-6fb3-41d5-9353-02339d92db0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
