<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblImprentaTitulo</name>
   <tag></tag>
   <elementGuidId>6701028e-559b-40c5-a83f-1d3f49a82fc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='enqheader']/tbody/tr[2]/td</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>td.ENQ-H-TITLE.ENQ-H-TITLE_BCCLECHQSOLIMPRENTA</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e3f1426e-a996-4669-b822-a6a375ec09dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ENQ-H-TITLE ENQ-H-TITLE_BCCLECHQSOLIMPRENTA</value>
      <webElementGuid>b27b85f5-025c-4309-a4a7-e051eadeddc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imprenta:</value>
      <webElementGuid>ef7093da-3628-4bd6-9c0c-7e81e520a228</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqheader&quot;)/tbody[1]/tr[2]/td[@class=&quot;ENQ-H-TITLE ENQ-H-TITLE_BCCLECHQSOLIMPRENTA&quot;]</value>
      <webElementGuid>48802748-8a14-4661-9ee4-3b8b0c644aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1c7a9a06-5af4-4e16-ac95-eeeada2ca11d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ENQ-H-TITLE ENQ-H-TITLE_BCCLECHQSOLIMPRENTA</value>
      <webElementGuid>34d60d7c-28ab-4c1b-8b44-2b48508bb618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Imprenta:</value>
      <webElementGuid>56224baa-4966-40aa-9fd6-6b7ed6a47d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqheader&quot;)/tbody[1]/tr[2]/td[@class=&quot;ENQ-H-TITLE ENQ-H-TITLE_BCCLECHQSOLIMPRENTA&quot;]</value>
      <webElementGuid>7306dfd7-44be-4bfc-b882-07941b145a1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='enqheader']/tbody/tr[2]/td</value>
      <webElementGuid>50072d67-1e31-46f0-90b8-e06ff76c3870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como XML'])[2]/following::td[3]</value>
      <webElementGuid>35092951-b328-4398-b382-16f8234bb58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como HTML'])[2]/following::td[4]</value>
      <webElementGuid>8f3272d8-d940-431f-a585-cd4af601c1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='COOP. LOS ARROYOS'])[1]/preceding::td[1]</value>
      <webElementGuid>2142f94a-9406-4463-bf66-833fbaa4f1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Chequera'])[1]/preceding::td[3]</value>
      <webElementGuid>823bfb2f-8fc5-477b-a5e1-a5c69b677941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Imprenta:']/parent::*</value>
      <webElementGuid>835660b0-19c3-43d9-ba5e-095a83e257f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td</value>
      <webElementGuid>408c62fc-b469-4229-84dd-d980b85a275d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Imprenta:' or . = 'Imprenta:')]</value>
      <webElementGuid>24ff18bc-4889-4ade-bdb7-25dd8952d95b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
