<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbTipoImposicion</name>
   <tag></tag>
   <elementGuidId>23beee74-17a2-4081-8082-d257dbad2725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:L.MM.IMPOSICION']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b5e44cf3-93ec-4523-993f-608a25f34051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_MMMONEYMARKET dealbox_MMMONEYMARKET_BCCLGIN</value>
      <webElementGuid>ac830bdf-faf7-4157-9708-8e60b1236beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:L.MM.IMPOSICION</value>
      <webElementGuid>4e8da146-b312-4f8c-8be4-b7e23f028f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:L.MM.IMPOSICION</value>
      <webElementGuid>4530165b-b644-4c04-bd86-5c28e7a3eb54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>27e3aa3b-666c-4a96-9fa8-2e100fd68c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>af44855e-3313-4843-823e-ef98e807a1af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hot</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>1daed8c2-f62f-48e7-af01-f8260e930b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>55871a8b-4334-46f3-aee4-6db2df326d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>437f9689-5aba-488b-84a9-183291b8c744</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'L.MM.IMPOSICION','issueToken');</value>
      <webElementGuid>4e57b14f-5b15-46e8-82b7-2a2db2d4a985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>enterKeyListener(event);</value>
      <webElementGuid>56e599c7-2f6b-4b64-b01e-e7a281a34b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event); doFieldChangeEvent(event);</value>
      <webElementGuid>03efaa34-0c49-401b-91a3-b3831d7bfec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('L.MM.IMPOSICION','','','issueToken')</value>
      <webElementGuid>e48442b5-ca74-4869-b610-ae1d0e154af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  CAMARACUENTAEFECTIVO</value>
      <webElementGuid>0fb6e45e-347a-4404-b632-fc72bf323fc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:L.MM.IMPOSICION&quot;)</value>
      <webElementGuid>02e9af97-9d21-49e8-9314-26c4db336d1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:L.MM.IMPOSICION']</value>
      <webElementGuid>5581961c-d2fc-48fc-bb62-3ef7eac00bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[15]/td[3]/select</value>
      <webElementGuid>017b1b2c-646a-4900-96a9-151522fb6372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de Imposicion'])[1]/following::select[1]</value>
      <webElementGuid>6d5b1f94-00e2-45b3-a15f-c57b36ee893a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPOSICION'])[1]/following::select[1]</value>
      <webElementGuid>838395b8-7735-45af-9503-4b5b6ba40134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nro. Cuenta Imposicion'])[1]/preceding::select[1]</value>
      <webElementGuid>2818df41-0bf0-4c0d-a65c-7667093f5ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIQUIDACION'])[1]/preceding::select[1]</value>
      <webElementGuid>d507b1e5-31fe-4de4-a0a3-0d8fe03de3b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td[3]/select</value>
      <webElementGuid>59a5637c-f8af-4875-9a29-fcbdb0ce6413</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:L.MM.IMPOSICION' and @id = 'fieldName:L.MM.IMPOSICION' and (text() = '  CAMARACUENTAEFECTIVO' or . = '  CAMARACUENTAEFECTIVO')]</value>
      <webElementGuid>59257f53-c701-4182-a2e3-0b3e7c0c9f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
