<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCustomerId</name>
   <tag></tag>
   <elementGuidId>7e70b3e9-9466-43f6-85ec-9c5e1b2e650c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='fieldCaption:CUSTOMER.ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5dbb9ce9-13cb-4125-8b66-8c7cf38e4ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>df56e95d-208b-4a1a-806b-f58e9305db08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>89962a20-6c53-4082-bcf0-04e43c57a76e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field field_MMMONEYMARKET</value>
      <webElementGuid>baa7f819-2ba6-4794-b8dc-0009a0093358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldCaption:CUSTOMER.ID</value>
      <webElementGuid>07594d47-beee-4caa-89f6-807c8abca810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldCaption:CUSTOMER.ID</value>
      <webElementGuid>2b2c2eae-bbae-46fd-8b79-5437cc2e40ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>ec7613ba-dc93-4426-898e-613ea82e47c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:help('CUSTOMER.ID','','','issueToken')</value>
      <webElementGuid>b6077aca-624b-4e70-a99e-09a69545f7c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Customer Id</value>
      <webElementGuid>04a7a309-006e-4865-a7cc-8c5e38aaf88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Id</value>
      <webElementGuid>8f0ee487-bb5f-4ee5-9132-e57108db5e82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldCaption:CUSTOMER.ID&quot;)</value>
      <webElementGuid>d7395dcc-184f-49a8-a5a0-1f3f1d8384b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='fieldCaption:CUSTOMER.ID']</value>
      <webElementGuid>110b2e3e-a89f-4bb1-bc22-ad5863c39fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td/label/a</value>
      <webElementGuid>a1791b5d-f0d2-428f-a8a8-360bfc7eb581</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customer Id')]</value>
      <webElementGuid>b3ae92e2-313e-48d4-9c17-280a217fc810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(CRECER XXI)'])[1]/following::a[1]</value>
      <webElementGuid>e2d14e84-3001-4b3b-870f-f7dd39749279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MM-23219-45533 [;2] 22 AGO 2024'])[1]/following::a[1]</value>
      <webElementGuid>34e9146a-f6b4-4cdf-9ec4-e62b7f939f0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='J M ELLENA'])[1]/preceding::a[2]</value>
      <webElementGuid>81936bf2-4433-45cd-a9e3-367c002194c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Currency'])[1]/preceding::a[2]</value>
      <webElementGuid>916a5e7c-af3e-482b-807b-cff2efed7cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Id']/parent::*</value>
      <webElementGuid>e7ee50e3-9bc2-4998-ab81-63c6cf6ff3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:help('CUSTOMER.ID','','','issueToken')&quot;)]</value>
      <webElementGuid>407f74a4-4a41-4dbc-93bf-0eac5b36e2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/a</value>
      <webElementGuid>f91dd2be-7f70-4203-9eb9-2ea162932653</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'fieldCaption:CUSTOMER.ID' and @id = 'fieldCaption:CUSTOMER.ID' and @href = concat(&quot;javascript:help(&quot; , &quot;'&quot; , &quot;CUSTOMER.ID&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;issueToken&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Customer Id' and (text() = 'Customer Id' or . = 'Customer Id')]</value>
      <webElementGuid>60dce4ce-370c-4dec-bd51-807a6444307a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
