<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblSeleccion</name>
   <tag></tag>
   <elementGuidId>902dabdb-051a-44d7-81f2-07aeacad2d68</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dropDownRow8']/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>fa008566-f108-4fef-9cab-b8223b978e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>coloumntddata coloumntddata_EBCCLCQMOTRECHCHQ</value>
      <webElementGuid>2e4f150d-9c98-4452-b9ad-8d97392f087e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sin Fondos Suficientes en Cuenta</value>
      <webElementGuid>39f77ea3-a2e1-4025-8cdd-91f5e31f9ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownRow8&quot;)/td[@class=&quot;coloumntddata coloumntddata_EBCCLCQMOTRECHCHQ&quot;]</value>
      <webElementGuid>99da4fc8-b8d8-4766-948d-d418bf1b33b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dropDownRow8']/td[2]</value>
      <webElementGuid>2e682772-8a5f-4403-94c9-667488de8d00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI'])[3]/following::td[2]</value>
      <webElementGuid>3cedb45d-852c-482c-ae30-b883ccaae2fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[11]/following::td[4]</value>
      <webElementGuid>8ea7c97b-6a8d-4dde-ac2e-d30fdf695894</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SI'])[4]/preceding::td[1]</value>
      <webElementGuid>8f58b663-e30f-4e79-937e-5dfa634dab63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NO'])[12]/preceding::td[3]</value>
      <webElementGuid>b2f00492-8bb7-4dd4-8214-a00d7254787c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Sin Fondos Suficientes en Cuenta']/parent::*</value>
      <webElementGuid>14681bf7-3faf-4052-b8c0-67aaaf79cf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]</value>
      <webElementGuid>2ec17298-9418-4c7c-b057-444d73bed9ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Sin Fondos Suficientes en Cuenta' or . = 'Sin Fondos Suficientes en Cuenta')]</value>
      <webElementGuid>bb1371b8-dcda-4ca0-96cd-783dc2f0af6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
