<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNroContrato</name>
   <tag></tag>
   <elementGuidId>d67f03dd-7a1c-445e-b040-9ed1714e3662</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='value:1:1:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2144e197-b0b9-4dd1-b62d-514cbc0cb17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c4e9b361-9b69-4cbc-b444-dfd17a4fe673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>3db65a55-d4ad-4d9e-840c-6ce626914b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>35cd21ab-ab08-45ae-b723-06a7b7de67b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ee9f2b4d-a3b3-438e-9bc5-8362bf09643c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>B.0289</value>
      <webElementGuid>ee99043b-ebdf-4d47-a066-2d27d451f193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frequencydropfieldname</name>
      <type>Main</type>
      <value>value:1:1:1</value>
      <webElementGuid>d8ffdc91-fdeb-4fbd-8d92-bfd3ba3a3fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enqseldata enqseldata_BCCLEEBCONSREVE</value>
      <webElementGuid>ae951913-64bd-4f18-bfc6-c1847caf7651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;value:1:1:1&quot;)</value>
      <webElementGuid>2fa5b1bb-0a30-4ddb-bef5-1c908b93a79e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='value:1:1:1']</value>
      <webElementGuid>e4a72c0d-0aca-493c-a24e-87e7f70f1b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='selectiondisplay']/tbody/tr/td[3]/input</value>
      <webElementGuid>589e3f2c-488b-430b-a449-25854c57d4b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/input</value>
      <webElementGuid>9bffea16-85ff-477f-9c73-d18cccfc05ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'value:1:1:1' and @id = 'value:1:1:1']</value>
      <webElementGuid>e3d21673-257a-491d-b15e-29e6b69b8352</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
