<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnDropdownTipoIdentif(CUIL-CUIT-CDI)</name>
   <tag></tag>
   <elementGuidId>15f27934-cf22-4109-bf7e-d3f3061eaa69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='tab1']/tbody/tr[19]/td[3]/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0fc6a6f8-ffba-4a33-be4d-8ad890be0654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>c0727dcd-488d-4afc-9312-6b47272fbadf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>e2394c9e-98d0-4f04-a2d4-3090e865fcae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown_button dropdown_button_TELLER dropdown_button_TELLER_DEPOSITOEFECTIVOBUZON</value>
      <webElementGuid>c93bb81b-8178-4135-a473-ced56255c981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>mvDropDown(event)</value>
      <webElementGuid>9bb63068-8d43-4790-91b5-61ee968e25e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>a014fb8b-d59c-460d-ae23-84651bcd4812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Lista de Registros</value>
      <webElementGuid>8ef37455-dc5b-435f-8d05-8a4f1356d7ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/deal/dropdown.gif</value>
      <webElementGuid>60a0056f-9649-40c6-9ce4-226bac1c6210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mvapplication</name>
      <type>Main</type>
      <value>BCCL.PER.TCUI</value>
      <webElementGuid>afe05aad-51e2-4f98-9704-0f13650d31ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mvtextfield</name>
      <type>Main</type>
      <value>fieldName:L.TCUI.ORD</value>
      <webElementGuid>de721801-7c41-4052-acf5-36983d2e3a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mvfieldname</name>
      <type>Main</type>
      <value>fieldName:L.TCUI.ORD</value>
      <webElementGuid>82aedf7c-ac4a-4566-9788-cb2fa63b3d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enquiryfield</name>
      <type>Main</type>
      <value>BCCL.PER.TCUI</value>
      <webElementGuid>51d4845e-83a0-4c99-b9eb-312e4d1bc4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dropfield</name>
      <type>Main</type>
      <value>fieldName:L.TCUI.ORD</value>
      <webElementGuid>c90f98bd-1ff6-4de8-9975-b787bf257bf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab1&quot;)/tbody[1]/tr[19]/td[3]/a[1]/img[@class=&quot;dropdown_button dropdown_button_TELLER dropdown_button_TELLER_DEPOSITOEFECTIVOBUZON&quot;]</value>
      <webElementGuid>a3ee34a0-4304-401c-8ece-d9de597c4cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[19]/td[3]/a/img</value>
      <webElementGuid>80df39de-fd38-4a8e-8fdd-1efd30a2bcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@title='Lista de Registros'])[3]</value>
      <webElementGuid>5e9fa74b-2f87-426e-b734-eb715ffc9423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td[3]/a/img</value>
      <webElementGuid>fb5d4bcb-ba1c-49ca-b433-7336b3909c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@title = 'Lista de Registros' and @src = '../plaf/images/bccl/deal/dropdown.gif']</value>
      <webElementGuid>5c584709-a610-4f20-9c92-ea9922a29a4e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
