<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbVerDetallesyBajaOBanco</name>
   <tag></tag>
   <elementGuidId>d1689370-decb-4d67-af84-d164efffa16a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='drillbox:1_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4cdd916c-d140-4a57-a18c-ace8f0988024</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>drillbox:1_1</value>
      <webElementGuid>be96876e-3b27-4a32-834a-4523fdc2340d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>drillbox drillbox_BCCLEBAJASOBRANTEDISPOGEOPPN</value>
      <webElementGuid>c5f8a72f-7010-43db-9d90-42d311c3204c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Baja Sobrante Dispositivo - SocioBaja Sobrante Dispositivo - O BancoBaja Sobrante Disp - Cta ContableReclasificar DifBaja de Sobrante - Prosegur NO MigBaja de Sobrante - Prosegur MigVer DetallesVer Baja de Sobrante</value>
      <webElementGuid>6ee52235-8ace-487e-a3ee-ae5ee3cb5cd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;drillbox:1_1&quot;)</value>
      <webElementGuid>519f3443-c795-43ed-b3bc-f72a19343309</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='drillbox:1_1']</value>
      <webElementGuid>f6f82869-ecd5-4139-87c4-fbd750a74fb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r1']/td[14]/table/tbody/tr/td/select</value>
      <webElementGuid>aa5ca46f-4722-4ff6-8772-5e7760095d75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FILIAL'])[1]/following::select[1]</value>
      <webElementGuid>ca781069-9cbd-4110-ae90-ef5f8fa25f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEPOSITO'])[1]/following::select[1]</value>
      <webElementGuid>1baa7099-151e-4658-b29a-356ae5512167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ARS'])[2]/preceding::select[1]</value>
      <webElementGuid>efd198d1-9c37-4d3b-a2b8-8344c51b00c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEPOSITO'])[2]/preceding::select[1]</value>
      <webElementGuid>7854177e-e92a-4b8b-ba6a-b6432d24565a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>38a754a1-9ab2-410d-b70b-9d42ad3cb0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'drillbox:1_1' and (text() = 'Baja Sobrante Dispositivo - SocioBaja Sobrante Dispositivo - O BancoBaja Sobrante Disp - Cta ContableReclasificar DifBaja de Sobrante - Prosegur NO MigBaja de Sobrante - Prosegur MigVer DetallesVer Baja de Sobrante' or . = 'Baja Sobrante Dispositivo - SocioBaja Sobrante Dispositivo - O BancoBaja Sobrante Disp - Cta ContableReclasificar DifBaja de Sobrante - Prosegur NO MigBaja de Sobrante - Prosegur MigVer DetallesVer Baja de Sobrante')]</value>
      <webElementGuid>81d14e20-2bab-470e-91b5-f884bbb8b1ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
