<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAnualAcumulado</name>
   <tag></tag>
   <elementGuidId>0b99500f-01c4-41c7-ba61-3930c19d01c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='r3']/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3fdbc93f-5469-455b-a613-28cfafc86d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Anual</value>
      <webElementGuid>ccb225b9-1ac4-47c7-a1d2-8dd8cda20206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;r3&quot;)/td[2]</value>
      <webElementGuid>e000ee2b-1124-4288-aff7-ffd9eca4c61c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='r3']/td[2]</value>
      <webElementGuid>143726ff-647c-428a-aa4f-45566c2f4b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mensual'])[1]/following::td[4]</value>
      <webElementGuid>ea3cdfeb-3523-40b4-a5d9-73c3f03de431</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diaria'])[1]/following::td[8]</value>
      <webElementGuid>1f770ce7-5d1e-45a2-acbd-259ad66913e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Compras de Mon. Ext. en el Banco'])[1]/preceding::td[3]</value>
      <webElementGuid>8a5e0426-0463-484c-9b70-d6e270e7e0a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Diaria'])[2]/preceding::td[4]</value>
      <webElementGuid>8af300d8-c85c-4be3-b277-c9be4ae95cc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Anual']/parent::*</value>
      <webElementGuid>a7ff4ac2-b4d6-45ab-ad51-335a8e2ef0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>917ac970-c481-4f26-a3b7-237a185ba180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Anual' or . = 'Anual')]</value>
      <webElementGuid>aa0a87e2-6843-4d4a-9598-0d35cc165cbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
