<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cbxTipoAgrupamiento2</name>
   <tag></tag>
   <elementGuidId>2e2648ef-9cb7-429b-ad37-cff6d239877d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:TIPO.AGRUP:1']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af016617-7138-4b0a-be54-4f75098aa70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_BCCLENQPARAMAGRP dealbox_BCCLENQPARAMAGRP_INPUT</value>
      <webElementGuid>8e32b1c2-bb05-462f-9e9f-98b8a33eacf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:TIPO.AGRUP:2</value>
      <webElementGuid>8554a30e-c038-46aa-bffd-ef97f10125ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:TIPO.AGRUP:2</value>
      <webElementGuid>d9feae99-9ae9-4677-a869-b3214c004dbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b6a8bebb-c661-4ca4-b783-2262db52716a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>e3b8241a-83cb-492c-8a14-6148b13e75ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_TIPO.AGRUP:1</value>
      <webElementGuid>14af418d-069a-4586-9b42-ae20fe74b587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'TIPO.AGRUP','issueToken');</value>
      <webElementGuid>07d34313-c67e-4c7d-b9fe-0d28918617e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>53ae10fc-4dcd-4376-9c54-bc350bd13e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('TIPO.AGRUP','','','issueToken')</value>
      <webElementGuid>fbbe2f05-823f-448e-bdf7-11915b8a7d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMBCOMNOR</value>
      <webElementGuid>a98756e0-3521-4fc7-bb14-eb03d6370851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:TIPO.AGRUP:2&quot;)</value>
      <webElementGuid>dd0d6ed7-0eeb-42b0-8ae3-c0a6b3c4a375</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:TIPO.AGRUP:2']</value>
      <webElementGuid>714a2f15-7a6e-4543-9b48-cef09d0adf10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[27]/td[3]/select</value>
      <webElementGuid>a5e922f4-e4a1-47e9-9d37-40726c722757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo Agrupamiento.2'])[1]/following::select[1]</value>
      <webElementGuid>de07ad35-e0ee-46e5-8478-af7538657f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ECHEQ - Acreditac Valores - C.'])[3]/following::select[1]</value>
      <webElementGuid>98e07966-c924-46c1-9608-58e26339df5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Codigo Agrupamiento.2'])[1]/preceding::select[1]</value>
      <webElementGuid>e0ca9f95-d37d-48a5-896d-d8e69295f127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descripcion Agrupamiento.2'])[1]/preceding::select[1]</value>
      <webElementGuid>a575d4d9-0a5c-4a23-a144-8aa2a2c25362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[27]/td[3]/select</value>
      <webElementGuid>43af60d0-9d4a-428a-8f09-4a8142c08db2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:TIPO.AGRUP:2' and @id = 'fieldName:TIPO.AGRUP:2' and (text() = 'AMBCOMNOR' or . = 'AMBCOMNOR')]</value>
      <webElementGuid>6eba839d-72aa-4fdf-8d09-8d4b6f106ffe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
