<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblAR0011001</name>
   <tag></tag>
   <elementGuidId>3e20a839-18e4-46db-8bdf-db6ceac5d581</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='enqsel']/table/tbody/tr/td[2]/table/tbody/tr[4]/td/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8527cdc1-de10-4d73-aa23-7ec78f29ae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> table-section table-section_BCCLECOTGRALFIL enqsel-ftr enqsel-ftr_BCCLECOTGRALFIL</value>
      <webElementGuid>ffe3bb6e-72ff-44f0-9aa0-0153ade19dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AR0011001 : BCCL.E.COT.GRAL.FIL</value>
      <webElementGuid>860741fa-e9ee-4bd0-b7b1-96b09c47820b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enqsel&quot;)/table[@class=&quot;enqsel-main enqsel-main_BCCLECOTGRALFIL&quot;]/tbody[1]/tr[1]/td[2]/table[@class=&quot;display_box display_box_BCCLECOTGRALFIL enqsel-selections enqsel-selections_BCCLECOTGRALFIL&quot;]/tbody[1]/tr[4]/td[1]/div[@class=&quot;table-section table-section_BCCLECOTGRALFIL enqsel-ftr enqsel-ftr_BCCLECOTGRALFIL&quot;]</value>
      <webElementGuid>fb461da5-4913-468d-99b4-897f25108ea0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='enqsel']/table/tbody/tr/td[2]/table/tbody/tr[4]/td/div</value>
      <webElementGuid>be02a5eb-7687-4cef-9080-4c8a8fa18c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='igual'])[1]/following::div[1]</value>
      <webElementGuid>3e293f7d-7068-46b8-b82d-9b7f340ec03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Moneda'])[4]/following::div[1]</value>
      <webElementGuid>ac1ada8e-2bd2-47be-adf3-82891f96bee7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Capture object:'])[1]/preceding::div[2]</value>
      <webElementGuid>a3abb0e4-98de-4996-a2bc-ca515b8a9ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[1]/preceding::div[2]</value>
      <webElementGuid>d945b0ea-cb71-4861-901c-70ff99e4defc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AR0011001 : BCCL.E.COT.GRAL.FIL']/parent::*</value>
      <webElementGuid>633b514f-b0a7-4d1b-a02f-73f713fcaf6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/div</value>
      <webElementGuid>ef747b4f-4ebd-49a2-92bd-c230b183c330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AR0011001 : BCCL.E.COT.GRAL.FIL' or . = 'AR0011001 : BCCL.E.COT.GRAL.FIL')]</value>
      <webElementGuid>a15d3250-1ce9-4053-80a0-5c35cde71ce7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
