<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>imgMasVerde</name>
   <tag></tag>
   <elementGuidId>45fb6de4-3136-444f-8824-c9a91d715adf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#image1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='image1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>18a0655b-d5e6-44a1-a521-9e06690a2536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>image1</value>
      <webElementGuid>a6cced11-3ae8-4183-9b44-3c931a8b0c32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>columnno</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e52f1ab3-3f05-44f4-9c29-3558386a50a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hideable</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>780c30fc-e886-427f-8f60-ea31f3646a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../plaf/images/bccl/tools/expand.gif</value>
      <webElementGuid>24bc0cbb-5c97-440c-be1c-181feae36d92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7861a7ec-4cf6-4b13-a353-926b0e3c34e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>@ID</value>
      <webElementGuid>f96819ac-9738-4e78-b7c1-4106d17e655b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>@ID</value>
      <webElementGuid>0748ea79-3ff4-405e-9128-152af9556afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;image1&quot;)</value>
      <webElementGuid>4c799949-7db1-45ce-90e8-1f53fc7fbd48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='image1']</value>
      <webElementGuid>74659b78-c1eb-487b-8d8e-3d9d1ea96067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader1']/table/tbody/tr/th[2]/a/img</value>
      <webElementGuid>17e70203-db99-4fa8-a813-06dcf1837533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='@ID']</value>
      <webElementGuid>c5b7d652-5057-45ad-a018-8ae1b2cba229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/a/img</value>
      <webElementGuid>1a0e1752-cd8d-4951-9b48-9d985c3c1e33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'image1' and @src = '../plaf/images/bccl/tools/expand.gif' and @alt = '@ID' and @title = '@ID']</value>
      <webElementGuid>3a681627-1fea-4626-921c-4f1a2fb78adb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
