<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblMONEDA</name>
   <tag></tag>
   <elementGuidId>d4b2f841-e6f6-43a2-b884-f3d303a6de46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText5']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>1cc853d8-1fd3-48f8-b83b-0e301430a939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>b5c89ee9-453c-4ae2-bc01-b3242f77434f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>84df6d67-39a4-4926-9268-f915079ba5c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText5</value>
      <webElementGuid>1bf817fc-9a0f-479f-a953-10fcca4b1fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MONEDA</value>
      <webElementGuid>18322c8c-60c5-4dfc-9048-f389ac4db759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText5&quot;)</value>
      <webElementGuid>d4e8fbcc-e522-4fe9-b268-470d7c7d1153</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText5']</value>
      <webElementGuid>1d548f24-1f9e-4edc-9cd5-a9fb16df20bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader5']/table/tbody/tr/th</value>
      <webElementGuid>92cd264f-f63a-476f-94d3-e6ea826ba8f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUC DESTINO'])[1]/following::th[3]</value>
      <webElementGuid>77c010fd-8d31-4445-9a58-a6ac5f5ca639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SUC ORIGEN'])[1]/following::th[6]</value>
      <webElementGuid>bed0ce4e-0474-432b-93d1-725314935f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IMPORTE'])[1]/preceding::th[2]</value>
      <webElementGuid>7504cd9c-0691-42fc-b1bf-bfd98c031749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TESORO DE ENVIO'])[1]/preceding::th[5]</value>
      <webElementGuid>4d1bffaa-4368-403f-81ff-462860a1b462</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MONEDA']/parent::*</value>
      <webElementGuid>d1a9e32d-53fc-488b-a8d7-847ebe7b1f3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/table/tbody/tr/th</value>
      <webElementGuid>50a20bfb-b431-43da-a4f7-2c4ded9a60aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText5' and (text() = 'MONEDA' or . = 'MONEDA')]</value>
      <webElementGuid>0f4ba1b6-6ba7-4255-ae80-0b21f6d09713</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
