<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtMonto</name>
   <tag></tag>
   <elementGuidId>e11318d3-e7fd-4a88-a386-a1c72d3896ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:AMOUNT.LOCAL.1:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f751a44c-3ea3-4380-8f85-7a757b9ea8b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>6a71e1e4-7955-4fc3-aa79-d3ed01ea25eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>4709a2db-c566-426a-bdf3-7630b72866ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:AMOUNT.LOCAL.1:1</value>
      <webElementGuid>7d6e96d6-8e40-4375-96d1-f7bce4e27f50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:AMOUNT.LOCAL.1:1</value>
      <webElementGuid>6cfa38ab-3ab8-41f3-81af-1ed2fdebd486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>09ca5087-e208-4d1a-9536-bf7b17c4bc6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_TELLER dealbox_TELLER_FALTANTESCAJAUSU</value>
      <webElementGuid>af40cda2-a95c-44ff-8b14-bc562e2e9a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>69322b87-794d-42fd-87e5-faec83400860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c0bd389e-d434-4c5c-bec7-7a8e85229bb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>hot</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>42be0f0a-6480-41f7-afdc-99ec33e64966</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>01c6c63e-8c4e-44a3-bb5b-5f0c147c42a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>d39078d9-d78a-4ec4-b66f-06eec32fa139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'AMOUNT.LOCAL.1','issueToken');</value>
      <webElementGuid>86ea15a9-86eb-4302-badc-2ad0c1666262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>enterKeyListener(event);</value>
      <webElementGuid>5e2985af-e856-4918-aadf-97ec2250b89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event); doFieldChangeEvent(event);</value>
      <webElementGuid>4c46b0a1-b7f2-434d-923b-9ca0b6b234b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('AMOUNT.LOCAL.1','','','issueToken')</value>
      <webElementGuid>1c0ba9f4-663a-4a03-8045-bab9beb5e1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:AMOUNT.LOCAL.1:1&quot;)</value>
      <webElementGuid>432a19a9-9611-49a2-90f3-d3189d44ac68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:AMOUNT.LOCAL.1:1']</value>
      <webElementGuid>9a754498-cb88-4620-be25-918bd70a1c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[3]/td[4]/input</value>
      <webElementGuid>51ae7fc3-6ed4-480e-8041-9bfd88abdef6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[4]/input</value>
      <webElementGuid>ccce03d0-fd26-4d5e-8f2e-9348a4d7da30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:AMOUNT.LOCAL.1:1' and @name = 'fieldName:AMOUNT.LOCAL.1:1' and @type = 'text']</value>
      <webElementGuid>3984386d-4316-4e1a-a305-dbefe1cd1df1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
