<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtPaseDeCajaATesoro</name>
   <tag></tag>
   <elementGuidId>dc584da4-e1cd-4225-b2af-54e15a2067e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@id='transactionId'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d8f5ef7-f4e1-4efc-900b-1d5bafe2c00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>538b2d30-769c-4043-b9cd-d655b83ae23e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>transactionId</value>
      <webElementGuid>5cbd910c-5185-4dfb-98f5-e54a6e93597f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transactionId</value>
      <webElementGuid>16cc08d1-bf6b-4f65-8709-f6adbd9e4dd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>idbox idbox_TELLER idbox_TELLER_ENVIOCAJA</value>
      <webElementGuid>861b1bd2-a7b1-4875-b8c4-8eb44f8ceee9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>38648ff8-5397-4b38-aa14-79f98d3d1569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('','','','issueToken')</value>
      <webElementGuid>d6817f5e-91d4-4168-9db0-0fb78af66ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>doFieldFocusEvent(event)</value>
      <webElementGuid>00318592-294c-435d-9936-7ac3bbb37555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;toolBar&quot;)/table[2]/thead[1]/tr[2]/td[1]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[1]/td[2]/input[@id=&quot;transactionId&quot;]</value>
      <webElementGuid>1111b532-2b18-49bd-aa44-49a2848f91eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//input[@id='transactionId'])[2]</value>
      <webElementGuid>e82325b2-2911-40c5-881c-4e418021b1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='toolBar']/table[2]/thead/tr[2]/td/table/tbody/tr/td[2]/table/tbody/tr/td[2]/input</value>
      <webElementGuid>5c2bb753-5c8e-4f28-80b5-87125689032d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/input</value>
      <webElementGuid>0293fe3f-1891-40ca-af3b-ab308bac2085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'transactionId' and @id = 'transactionId']</value>
      <webElementGuid>8197426e-9ed8-4f9f-9d75-4046739fe1b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
