<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblidValidacionesPago</name>
   <tag></tag>
   <elementGuidId>024150ac-4a5d-4001-b77b-6d75d98dfe02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//tr[@id='dropDownRow1']/td/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>b</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>54c87e48-d124-4b56-b54a-580b8f23f48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>01.01.00.00.02.00.00.00.00</value>
      <webElementGuid>0398005c-d1b3-46dd-bffb-d964aac63014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropDownRow1&quot;)/td[@class=&quot;coloumntddata coloumntddata_EBCCLCQVALIDACIONESPAGOINPUT&quot;]/b[1]</value>
      <webElementGuid>cc9464b0-f431-4b0a-850d-c1036da4a601</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='dropDownRow1']/td/b</value>
      <webElementGuid>15f70973-4ccf-437e-ad71-357636226b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subcausa'])[1]/following::b[1]</value>
      <webElementGuid>c5caa856-ada8-4ad9-95cc-01646ebc1429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Causa'])[1]/following::b[1]</value>
      <webElementGuid>75f79a32-f2f3-4c45-b707-f2ae44a40d0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='01.01.00.00.02.00.00.00.00']/parent::*</value>
      <webElementGuid>a9aa4587-9d4c-470d-9adb-920756116244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>188aead8-b8be-4130-a970-ed9dcd9736c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '01.01.00.00.02.00.00.00.00' or . = '01.01.00.00.02.00.00.00.00')]</value>
      <webElementGuid>b7517455-0266-436b-84a0-7380693e3f96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
