<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNombrePosteo</name>
   <tag></tag>
   <elementGuidId>bf67d18e-2e68-4b5c-8118-8a9e081c79c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'fieldName:CREDIT.AMOUNT']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;fieldName:L.NOMBRE.POSTEO&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fieldName\:DEBIT\.AMOUNT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f7bb8728-4709-46af-a07e-165e87e2d7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7410c3ac-e186-4652-847f-d865281904cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>0d7633cc-6b4f-46e1-8033-0cfe32168f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:CREDIT.AMOUNT</value>
      <webElementGuid>2658c73d-0ae0-46b6-b685-59c5ba5dccc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:CREDIT.AMOUNT</value>
      <webElementGuid>2c2ae2ff-08c0-4c03-84e5-9456c4bf23a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>70d5a9b9-68e7-4deb-bac7-81798968713e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_FUNDSTRANSFER dealbox_FUNDSTRANSFER_POSTEORETIRO</value>
      <webElementGuid>d4ad7d74-b081-4449-baf6-3522900c4eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>042b6af8-bf7e-417f-9573-2df964cf2233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>77adf2f8-732a-4fa4-afb6-1bfac78829d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_CREDIT.AMOUNT</value>
      <webElementGuid>5d6aa7c5-a610-4f5a-8661-c125bc44b931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'CREDIT.AMOUNT','issueToken');</value>
      <webElementGuid>86391b34-f127-4581-b308-887c98ab9b3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>f60cf70b-37e1-461a-ab0b-4b1540e903a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('CREDIT.AMOUNT','','','issueToken')</value>
      <webElementGuid>183a629f-4297-4bd2-84d0-9e9d6c325810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:CREDIT.AMOUNT&quot;)</value>
      <webElementGuid>c2500f28-5c16-4776-a0aa-347e332bf013</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:CREDIT.AMOUNT']</value>
      <webElementGuid>ea62f22e-2598-4667-9b0c-88ace7567136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[5]/td[4]/input</value>
      <webElementGuid>1996adf9-36fe-4f83-9d97-e2d84597069b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[4]/input</value>
      <webElementGuid>fb209a30-b639-466e-8cf4-c8f4e871227c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:CREDIT.AMOUNT' and @name = 'fieldName:CREDIT.AMOUNT' and @type = 'text']</value>
      <webElementGuid>0ff436e8-01a4-422e-8093-5e3edf45f52f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
