<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txtNombreBenef</name>
   <tag></tag>
   <elementGuidId>6ab6861b-604e-4aee-a2f3-73b0677df7ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fieldName:L.DENOM.BEN:1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8234f550-05b2-44f0-bfc7-5a1377037ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>87d29b85-37dc-4774-943d-8d4ba5b25846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>50b7056f-293a-4a09-8b47-a0acbb554dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:L.DENOM.BEN:1</value>
      <webElementGuid>f0870de4-1624-456a-970d-b36b9db33695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:L.DENOM.BEN:1</value>
      <webElementGuid>9a8e161d-e8ec-44bb-9554-3b3fe3b33c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>e3b1eea1-757b-4ca5-8b73-7ab30913394b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_FUNDSTRANSFER dealbox_FUNDSTRANSFER_BCCLTRANSOBANCOS</value>
      <webElementGuid>a2d180e3-b6c4-4305-881b-c5c1a8f369ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>c4bfcf10-e790-41ea-a248-384fca978bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7aac6c58-a125-41f6-b0db-177f81d70f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_L.DENOM.BEN:1</value>
      <webElementGuid>547e3474-e160-425d-9921-c7ee3945154a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'L.DENOM.BEN','issueToken');</value>
      <webElementGuid>57808b89-8166-4a0f-8163-9a2852b5c572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>cf82457b-25c2-48df-b88d-af8e7fc1fca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('L.DENOM.BEN','','','issueToken')</value>
      <webElementGuid>2fa93c84-b59b-4975-ba0c-e6c51b7f36f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:L.DENOM.BEN:1&quot;)</value>
      <webElementGuid>7c5d5c23-e4d8-41cc-821d-a963dce38c0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fieldName:L.DENOM.BEN:1']</value>
      <webElementGuid>c5f88d91-090e-4746-9bfe-2632499ddcae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[16]/td[3]/input</value>
      <webElementGuid>a23a10fe-6aec-409d-9686-009fcc756ac9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[16]/td[3]/input</value>
      <webElementGuid>6ee13773-2549-4cee-9ae8-d2c4823526df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fieldName:L.DENOM.BEN:1' and @name = 'fieldName:L.DENOM.BEN:1' and @type = 'text']</value>
      <webElementGuid>0c39d5da-5ee1-442b-a6cf-6425df5783e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
