<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Estado</name>
   <tag></tag>
   <elementGuidId>739d9e06-51d4-4e80-96a8-1f251ab82110</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fieldName:ESTADO.INHAB']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a059cd93-704c-4928-8d12-603540c7aea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dealbox dealbox_BCCLACINHABPROPIOS dealbox_BCCLACINHABPROPIOS_CAMBEST</value>
      <webElementGuid>b19df480-54e5-44e8-8b70-d236861057b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldName:ESTADO.INHAB</value>
      <webElementGuid>efcd8ea9-eaa9-4785-9357-d4b2d2a69ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldName:ESTADO.INHAB</value>
      <webElementGuid>24c290a6-12a0-4ef1-b2d1-59657e0c69f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>bb8e9256-2ca3-43d6-8f01-df7ef50c5fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabname</name>
      <type>Main</type>
      <value>tab1</value>
      <webElementGuid>559bf20c-b356-4e84-9ebb-404f7fd52bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oldvalue</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>bf1a7403-f1b6-44bc-9528-d2859910b179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-oldvalue</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>0acac5e7-fb7e-4b10-9482-68f66fd490b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fielderror</name>
      <type>Main</type>
      <value>Y</value>
      <webElementGuid>18d31177-cd2d-47da-87a7-47215a052038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enrifieldname</name>
      <type>Main</type>
      <value>enri_ESTADO.INHAB</value>
      <webElementGuid>4faa445f-d049-451d-b4f0-2337daa72b70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>invokeHelp(event,'ESTADO.INHAB','issueToken');</value>
      <webElementGuid>799a8ad0-a800-49d0-83c1-0a3fe045b14c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>clearEnrichment(event); FragmentUtil.formChangeHandler(); FragmentUtil.fieldChangeHandler(event);</value>
      <webElementGuid>cd8cc63f-ac2b-4ba0-a28c-2d3f1ba5959e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ondblclick</name>
      <type>Main</type>
      <value>javascript:help('ESTADO.INHAB','','','issueToken')</value>
      <webElementGuid>54a85b91-1996-4904-b033-e016081b7e26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  INHABILITADOBAJA X CAUSA 51 O 52BAJA X ERROR CAUSA 50FINALIZADO X FILIALBAJA HISTORICANO INHAB X GOP</value>
      <webElementGuid>a4bfd496-d066-40e2-a5a7-e3b550fe9884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldName:ESTADO.INHAB&quot;)</value>
      <webElementGuid>19a1dcf8-8962-4d91-83b6-77a095cf2b6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fieldName:ESTADO.INHAB']</value>
      <webElementGuid>85568dff-3802-483a-871f-b6ac22d337f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr[3]/td[3]/select</value>
      <webElementGuid>f7a17d3e-17ff-4afb-bab2-8093d1b2fdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estado'])[2]/following::select[1]</value>
      <webElementGuid>ca233c07-79ec-4cd8-8c5e-37ef23c6658d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AGUIRRE ALBERTO SALOMON'])[1]/following::select[1]</value>
      <webElementGuid>94c2e04d-64a2-4a23-9337-618db6b0607a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Inicio'])[1]/preceding::select[1]</value>
      <webElementGuid>b94f85b5-1cd3-4c27-8f7f-abef6174305c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fecha Finalizacion'])[1]/preceding::select[1]</value>
      <webElementGuid>23beb086-6dc1-4eea-b40b-6c6624a7e888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0a5f3362-659a-48dc-aa86-7f7aa1de078d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fieldName:ESTADO.INHAB' and @id = 'fieldName:ESTADO.INHAB' and (text() = '  INHABILITADOBAJA X CAUSA 51 O 52BAJA X ERROR CAUSA 50FINALIZADO X FILIALBAJA HISTORICANO INHAB X GOP' or . = '  INHABILITADOBAJA X CAUSA 51 O 52BAJA X ERROR CAUSA 50FINALIZADO X FILIALBAJA HISTORICANO INHAB X GOP')]</value>
      <webElementGuid>54411022-d41d-4b72-b56c-e626f7e6e1e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
