<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblALTASobranteenDispPn099Retiro</name>
   <tag></tag>
   <elementGuidId>139aad5a-5ff2-4694-aa9c-e18b55db81d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='enri_TRANSACTION.CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>4b2b1de5-5594-44f1-ad51-6b9ae4cfedce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>enrichment enrichment_TELLER</value>
      <webElementGuid>b441a93a-187e-411d-9179-9a3fa5b2934e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>enri_TRANSACTION.CODE</value>
      <webElementGuid>4d555710-2738-4174-986f-317eda1a8f37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>enri_TRANSACTION.CODE</value>
      <webElementGuid>8c53b07f-c93c-4420-8e6c-e931be9d0140</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ALTA Sobrante en Disp Pn 099 Retiro</value>
      <webElementGuid>1fb1a2a1-ade3-4a6e-aea9-1ee63a083548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;enri_TRANSACTION.CODE&quot;)</value>
      <webElementGuid>97220789-2a5b-4433-a9f9-295a36a10468</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='enri_TRANSACTION.CODE']</value>
      <webElementGuid>c6eb405a-ef71-4c64-94ce-62ec653bf51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab1']/tbody/tr/td[4]/span</value>
      <webElementGuid>dadbf623-d217-496b-b5eb-08020bc9b37f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transaction Code'])[1]/following::span[2]</value>
      <webElementGuid>ea432c22-cf63-49e6-bb6b-bd411c188df2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.099 Casa Central)'])[1]/following::span[2]</value>
      <webElementGuid>3d7a8166-ebcd-41dd-ad92-f0b38514dc37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teller Id 1'])[1]/preceding::span[1]</value>
      <webElementGuid>44f41ad3-d91a-4883-927e-66bdd81cf378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B.FMASTROIANNI'])[1]/preceding::span[2]</value>
      <webElementGuid>17e96afc-39af-4718-8fdb-5aa68daea978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ALTA Sobrante en Disp Pn 099 Retiro']/parent::*</value>
      <webElementGuid>bcea00ad-4183-418b-90c4-86a7467ea53b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/span</value>
      <webElementGuid>dd1aabc6-5792-4c5f-9f8b-831bd84d227a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'enri_TRANSACTION.CODE' and @name = 'enri_TRANSACTION.CODE' and (text() = 'ALTA Sobrante en Disp Pn 099 Retiro' or . = 'ALTA Sobrante en Disp Pn 099 Retiro')]</value>
      <webElementGuid>8181855e-853d-4773-860b-354b2a557c64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
