<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblTxnCompleta</name>
   <tag></tag>
   <elementGuidId>e0c114fb-ca3d-4800-b3ca-03894fcd4277</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>td.message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3d1644d7-1f65-4a18-a511-f0b057c71784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message</value>
      <webElementGuid>d31134de-e20d-4f7e-bcf5-ccb67815df73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Txn Completa: 254598140 15:23:21 06 JUN 2024 BCCL.CQ.CHEQUES.RECHAZADOS,RCHFIL I </value>
      <webElementGuid>1fcb7b1b-2245-4241-b630-963d98f2c20d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;appreq&quot;)/div[@class=&quot;display_box display_box_BCCLCQCHEQUESRECHAZADOS display_box_BCCLCQCHEQUESRECHAZADOS_RCHFIL&quot;]/table[1]/tbody[1]/tr[1]/td[1]/table[@id=&quot;messages&quot;]/tbody[1]/tr[2]/td[2]/table[2]/tbody[1]/tr[1]/td[@class=&quot;message&quot;]</value>
      <webElementGuid>f2c4692f-14dc-4ffd-87e9-9c8ae918a1a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='messages']/tbody/tr[2]/td[2]/table[2]/tbody/tr/td</value>
      <webElementGuid>4dea1988-45f5-43fe-9b26-c45a46821870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.001 Centro)'])[1]/following::td[7]</value>
      <webElementGuid>b8ebf935-07b1-42da-aee3-8172783693da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rechazo de cheques de caja en filial'])[1]/following::td[14]</value>
      <webElementGuid>ed253ebb-600b-4368-8bc4-503edf551593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ALERTAS PENDIENTES DE AUTORIZACION'])[1]/preceding::td[1]</value>
      <webElementGuid>ebd8159d-ec59-4a7b-9af5-b29a9dc0b7de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Txn Completa: 254598140 15:23:21 06 JUN 2024 BCCL.CQ.CHEQUES.RECHAZADOS,RCHFIL I']/parent::*</value>
      <webElementGuid>53920e4c-3a1a-4915-92de-f5bbb6f256be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td</value>
      <webElementGuid>83977877-83d3-475d-8dc0-74bb315f7e66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'Txn Completa: 254598140 15:23:21 06 JUN 2024 BCCL.CQ.CHEQUES.RECHAZADOS,RCHFIL I ' or . = 'Txn Completa: 254598140 15:23:21 06 JUN 2024 BCCL.CQ.CHEQUES.RECHAZADOS,RCHFIL I ')]</value>
      <webElementGuid>9a884161-5397-4397-8e6c-66736f91c6b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
