<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblProdSubprod</name>
   <tag></tag>
   <elementGuidId>16275902-1253-4e9e-b312-5d4174ab6989</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#columnHeaderText1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//th[@id='columnHeaderText1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
      <webElementGuid>89fea2ca-4df6-4db2-9a71-99795cdec5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scope</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>d0194d1b-2b28-4893-9287-e4195d56044a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>columnHeader</value>
      <webElementGuid>1bbff9cf-3ff5-4a27-9f10-c2e9d62ef026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>columnHeaderText1</value>
      <webElementGuid>2def1f9a-e4e0-48b3-aec9-5e5ad364a48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Prod.Subprod</value>
      <webElementGuid>e076ecb3-69c7-403a-8029-bbaf9ad17b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;columnHeaderText1&quot;)</value>
      <webElementGuid>4f69a15b-b06b-48b3-97c1-3875bc8e932b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//th[@id='columnHeaderText1']</value>
      <webElementGuid>11ceaa46-744e-4623-9916-25f9cb9c2dc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='columnHeader1']/table/tbody/tr/th</value>
      <webElementGuid>046effe4-9395-4cf2-859b-bb535a5c7ba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como XML'])[2]/following::th[3]</value>
      <webElementGuid>69c60a92-5300-470a-b4bb-0220375d8cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Guardar como HTML'])[2]/following::th[3]</value>
      <webElementGuid>396b8da9-834e-43ff-a727-91e216783e15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Denominacion'])[1]/preceding::th[2]</value>
      <webElementGuid>dfeae9ac-9f10-43c6-a2d3-28ad8f1f1c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Habilitado'])[1]/preceding::th[5]</value>
      <webElementGuid>bfa65c81-47be-482f-8bbb-9facd1d6fc01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Prod.Subprod']/parent::*</value>
      <webElementGuid>12478995-cf2c-46bb-80bf-c673ac71bc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tbody/tr/th</value>
      <webElementGuid>199298b7-5e24-4194-ab28-31874223e8ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//th[@id = 'columnHeaderText1' and (text() = 'Prod.Subprod' or . = 'Prod.Subprod')]</value>
      <webElementGuid>6715b1c4-934f-43f3-9e8d-ca1ae556310f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
