<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblFechayHora</name>
   <tag></tag>
   <elementGuidId>28160a44-ca4f-43ab-b53a-a4d3c3f3312c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='fieldCaption:DATE.TIME']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2da43532-5ad3-4c94-a9dc-410bded154e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>46effe11-89e7-4e58-9826-d7eb7f439dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>2a95c4f5-5f95-4cc1-a474-5342508caea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>field field_TELLER field_TELLER_PASEENTRECAJAS</value>
      <webElementGuid>48055e14-7d3e-4837-a417-48dbec39985a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fieldCaption:DATE.TIME</value>
      <webElementGuid>3885d7f4-4411-4e4a-a542-3677171e32db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fieldCaption:DATE.TIME</value>
      <webElementGuid>6e8cbd97-bb6a-4f7c-83dc-7126eee0aab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>53036900-b894-4901-9202-d8e01ba1e412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:help('DATE.TIME','','','issueToken')</value>
      <webElementGuid>a06bbcfd-e82a-4a13-9fc3-a2fd90d229f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Fecha y Hora</value>
      <webElementGuid>4eb125c7-5f66-4d0e-967d-34d6af2947a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Fecha y Hora.1</value>
      <webElementGuid>b5bdd725-1460-4b5c-82ad-94ced70ffcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fieldCaption:DATE.TIME&quot;)</value>
      <webElementGuid>b2bd475a-a16a-49e8-ac00-ef7f4784856c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='fieldCaption:DATE.TIME']</value>
      <webElementGuid>074437af-8c7e-4a0e-957e-6e046c752a05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='tab2']/tbody/tr[5]/td/label/a</value>
      <webElementGuid>227ffe17-7d85-496f-af2f-20df5084ce2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Fecha y Hora.1')]</value>
      <webElementGuid>8cb9fe6f-e127-45f3-b3e8-bbd574adc2d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingresado Por.1'])[1]/following::a[1]</value>
      <webElementGuid>8f7edd9f-e285-47cc-be38-696f8728e50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Actualizacion Nro'])[1]/following::a[2]</value>
      <webElementGuid>a0d1b9fb-c7e0-4edf-860e-ef33d67c7a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cod.Con.'])[1]/preceding::a[1]</value>
      <webElementGuid>01aa9f28-e458-4909-82e1-a04ef291329c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AR-001-1089'])[1]/preceding::a[2]</value>
      <webElementGuid>55776388-621f-4dec-a7a8-16d2cf4e7b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Fecha y Hora.1']/parent::*</value>
      <webElementGuid>05b82741-29d8-4840-a691-2e82d9de7ac4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:help('DATE.TIME','','','issueToken')&quot;)]</value>
      <webElementGuid>a96320cd-41b1-4da7-9337-f1ccaba67174</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[5]/td/label/a</value>
      <webElementGuid>dff81252-3a1f-4712-b794-bcd39daa9298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@name = 'fieldCaption:DATE.TIME' and @id = 'fieldCaption:DATE.TIME' and @href = concat(&quot;javascript:help(&quot; , &quot;'&quot; , &quot;DATE.TIME&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;&quot; , &quot;'&quot; , &quot;,&quot; , &quot;'&quot; , &quot;issueToken&quot; , &quot;'&quot; , &quot;)&quot;) and @title = 'Fecha y Hora' and (text() = 'Fecha y Hora.1' or . = 'Fecha y Hora.1')]</value>
      <webElementGuid>4604d5ad-de66-423f-975e-31f2c3a77563</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
