<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lblCHARGE.REQUEST</name>
   <tag></tag>
   <elementGuidId>ce8dcfd9-d251-4a79-9288-52ae727248e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'AC.CHARGE.REQUEST' or . = 'AC.CHARGE.REQUEST')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='dealtitle']/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;AC.CHARGE.REQUEST&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3a532301-83fc-490a-ac95-827c33bf060e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>focusonKey('inline',event);</value>
      <webElementGuid>f9999e3a-7f2e-4bb1-be09-65513b314bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideTooltip(event);</value>
      <webElementGuid>041a14a8-bb44-4743-af32-465262e252b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AC.CHARGE.REQUEST</value>
      <webElementGuid>204b5af4-44cc-44b6-880f-c218d0b62f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:help(&quot;AC.CHARGE.REQUEST&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);</value>
      <webElementGuid>713cacde-72a0-458c-9e58-1ef721d5bef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AC.CHARGE.REQUEST</value>
      <webElementGuid>956ac156-2257-4627-812e-6351595c0590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dealtitle&quot;)/a[1]</value>
      <webElementGuid>dc024eba-d999-4f36-b1df-cafb2e6c0e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='dealtitle']/a</value>
      <webElementGuid>937059de-3d5c-4129-901e-75dea787c080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'AC.CHARGE.REQUEST')]</value>
      <webElementGuid>3d448861-cd6f-484f-b6f3-ae0ee64e11ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.089 M.del Plata Ctr)'])[1]/preceding::a[3]</value>
      <webElementGuid>2b4053e5-80b2-40f3-a906-850ebf83668c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AC.CHARGE.REQUEST']/parent::*</value>
      <webElementGuid>0db34f74-1d78-4d4a-b1cd-34aa49d8299a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:help(&quot;AC.CHARGE.REQUEST&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);')]</value>
      <webElementGuid>15450218-8d04-41b4-97eb-5d2153d6429b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/a</value>
      <webElementGuid>e84b9680-ed1b-4246-a27d-7aa9764786c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'AC.CHARGE.REQUEST' and @href = 'javascript:help(&quot;AC.CHARGE.REQUEST&quot;,&quot;&quot;,&quot;&quot;,&quot;issueToken&quot;);' and (text() = 'AC.CHARGE.REQUEST' or . = 'AC.CHARGE.REQUEST')]</value>
      <webElementGuid>2d95716a-653e-4fc0-b394-a1ec72baddd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
