<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAudit</name>
   <tag></tag>
   <elementGuidId>fee83629-b38b-457a-bfe9-86b4c580af97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='headtab']/tbody/tr/td[2]/a/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.active-tab > span:nth-child(1)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>06331cdf-e708-4d0f-9193-5223d2d8254f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Audit</value>
      <webElementGuid>40db0212-6924-4886-ae6d-f62322cd1a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;headtab&quot;)/tbody[1]/tr[1]/td[2]/a[@class=&quot;nonactive-tab&quot;]/span[1]</value>
      <webElementGuid>a7f2352d-5a8f-4056-a037-ad85f97c6397</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='headtab']/tbody/tr/td[2]/a/span</value>
      <webElementGuid>46a07326-0b0b-4235-89c5-40ca2f51ecca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nota de Debito por Ajuste'])[2]/following::span[1]</value>
      <webElementGuid>2ececb6c-3d0f-4877-aeec-ed813d5c6e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Fil.043 Villa Mitre)'])[1]/following::span[2]</value>
      <webElementGuid>ede4a34b-0b69-4950-8374-7d8007e41492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nro Cuenta'])[1]/preceding::span[1]</value>
      <webElementGuid>7d61fc61-d3f6-4acc-9179-b92e0b9f5db0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WAKI TINKINA ASMEM JUJUY'])[1]/preceding::span[2]</value>
      <webElementGuid>9c3c1bd6-288c-4c6b-87c0-3e92db01f331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Audit']/parent::*</value>
      <webElementGuid>c4c80644-8155-4f1d-bf1d-0a10e3de1ea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/a/span</value>
      <webElementGuid>0de96a4f-ceb9-4004-8b5b-4bb9fc46df76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Audit' or . = 'Audit')]</value>
      <webElementGuid>e1bfc6e9-2cb0-40d0-a745-01b6c5203464</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
